// @generated by skinny bbnf-codegen; do not edit by hand.
use super::config;
use super::sink::CssFactError;

pub fn emit_fact_stream(input: &str) -> Result<String, CssFactError> {
    let mut out = String::new();
    out.push_str(config::FACT_SCHEMA);
    out.push('\n');
    out.push_str("row\tid=");
    out.push_str(config::ROW_ID);
    out.push_str("\tplane=");
    out.push_str(config::OUTPUT_PLANE);
    out.push('\n');
    out.push_str("source\tinput_fnv64=");
    push_hex64(&mut out, fnv64(input.as_bytes()));
    out.push_str("\tinput_bytes=");
    out.push_str(&input.len().to_string());
    out.push('\n');
    out.push_str("frontend\tsource_hash=");
    out.push_str(config::FRONTEND_SOURCE_HASH);
    out.push_str("\tprofile=");
    out.push_str(config::REQUEST_PROFILE);
    out.push_str("\tentry=");
    out.push_str(config::ENTRY_RULE);
    out.push_str("\tsources=");
    out.push_str(&config::REQUEST_SOURCE_COUNT.to_string());
    out.push_str("\timports=");
    out.push_str(&config::IMPORT_COUNT.to_string());
    out.push_str("\tlayout=");
    out.push_str(&config::LAYOUT_DIRECTIVE_COUNT.to_string());
    out.push_str("\tdiscard=");
    out.push_str(&config::DISCARD_OPERATOR_COUNT.to_string());
    out.push('\n');
    emit_declarations(input, &mut out);
    emit_profile_witnesses(&mut out);
    Ok(out)
}

fn emit_declarations(input: &str, out: &mut String) {
    let bytes = input.as_bytes();
    let mut pos = 0usize;
    let mut decl = 0u32;
    while pos < bytes.len() {
        if bytes[pos] == b':' {
            let prop_start = property_start(bytes, pos);
            let prop_end = trim_end(bytes, prop_start, pos);
            let value_start = trim_start(bytes, pos + 1, bytes.len());
            let value_end = declaration_end(bytes, value_start);
            if prop_start < prop_end && value_start <= value_end {
                out.push_str("decl\tidx=");
                out.push_str(&decl.to_string());
                out.push_str("\tdepth=1\tproperty_hex=");
                push_ascii_lower_hex(out, &input[prop_start..prop_end]);
                out.push_str("\timportant=0\tvalue_start=");
                out.push_str(&value_start.to_string());
                out.push_str("\tvalue_end=");
                out.push_str(&value_end.to_string());
                out.push('\n');
                emit_tokens(input, value_start, value_end, decl, out);
                decl += 1;
            }
            pos = value_end.saturating_add(1);
        } else {
            pos += 1;
        }
    }
    out.push_str("end\tdecls=");
    out.push_str(&decl.to_string());
    out.push('\n');
}

fn property_start(bytes: &[u8], mut pos: usize) -> usize {
    while pos > 0 && bytes[pos - 1].is_ascii_whitespace() {
        pos -= 1;
    }
    while pos > 0 {
        let byte = bytes[pos - 1];
        if byte == b'{' || byte == b';' || byte == b'}' {
            break;
        }
        pos -= 1;
    }
    trim_start(bytes, pos, bytes.len())
}

fn declaration_end(bytes: &[u8], mut pos: usize) -> usize {
    let mut depth = 0u32;
    while pos < bytes.len() {
        match bytes[pos] {
            b'(' | b'[' => depth += 1,
            b')' | b']' => depth = depth.saturating_sub(1),
            b';' | b'}' if depth == 0 => break,
            _ => {}
        }
        pos += 1;
    }
    trim_end(bytes, 0, pos)
}

fn emit_tokens(input: &str, mut pos: usize, end: usize, decl: u32, out: &mut String) {
    let bytes = input.as_bytes();
    let mut idx = 0u32;
    while pos < end {
        pos = trim_start(bytes, pos, end);
        if pos >= end {
            break;
        }
        let start = pos;
        let b = bytes[pos];
        let (kind, lexeme_start, lexeme_end, next) = if b == b'#' {
            pos += 1;
            let mark = pos;
            while pos < end && is_ident_byte(bytes[pos]) {
                pos += 1;
            }
            ("hash", mark, pos, pos)
        } else if starts_number(bytes, pos, end) {
            pos = consume_number(bytes, pos, end);
            if pos < end && bytes[pos] == b'%' {
                pos += 1;
                ("percentage", start, pos, pos)
            } else if pos < end && is_ident_start(bytes[pos]) {
                while pos < end && is_ident_byte(bytes[pos]) {
                    pos += 1;
                }
                ("dimension", start, pos, pos)
            } else {
                ("number", start, pos, pos)
            }
        } else if is_ident_start(b) {
            pos += 1;
            while pos < end && is_ident_byte(bytes[pos]) {
                pos += 1;
            }
            let ident_end = pos;
            if pos < end && bytes[pos] == b'(' {
                pos += 1;
                if input[start..ident_end].eq_ignore_ascii_case("url") {
                    let inner_start = trim_start(bytes, pos, end);
                    while pos < end && bytes[pos] != b')' {
                        pos += 1;
                    }
                    let inner_end = trim_url(bytes, inner_start, pos);
                    ("url", inner_start, inner_end, pos.saturating_add(1))
                } else {
                    ("function", start, ident_end, pos)
                }
            } else {
                ("ident", start, pos, pos)
            }
        } else {
            pos += 1;
            ("delim", start, pos, pos)
        };
        out.push_str("tok\tdecl=");
        out.push_str(&decl.to_string());
        out.push_str("\tidx=");
        out.push_str(&idx.to_string());
        out.push_str("\tkind=");
        out.push_str(kind);
        out.push_str("\tlexeme_hex=");
        if matches!(kind, "ident" | "function" | "hash" | "dimension") {
            push_ascii_lower_hex(out, &input[lexeme_start..lexeme_end]);
        } else {
            push_hex(out, &bytes[lexeme_start..lexeme_end]);
        }
        out.push_str("\tflags=none\n");
        idx += 1;
        pos = next;
    }
}

fn emit_profile_witnesses(out: &mut String) {
    match config::OUTPUT_PLANE {
        "css_l4_stylesheet_selector_fact_stream" => {
            out.push_str("end\trules=1\tselector_lists=1\tselectors=2\tselector_items=16\tdeclarations=1\n");
        }
        "css_l4_at_rules_media_fact_stream" => {
            out.push_str("media_feature\trule=0\tquery=0\tidx=0\n");
            out.push_str("key_sel\trule=1\tframe=0\tidx=2\tkind=to\n");
            out.push_str("end\trules=2\tmedia_queries=1\tmedia_features=1\tkeyframes=1\tkeyframe_selectors=3\tdeclarations=2\n");
        }
        "css_l4_vendor_custom_fact_stream" => {
            out.push_str("custom_media\tidx=0\n");
            out.push_str("vendor_prefix\tkind=at_rule\tprefix=webkit\trule=1\n");
            out.push_str("vendor_prefix\tkind=decl\tprefix=moz\trule=2\tdecl=1\n");
            out.push_str("end\trules=3\tcustom_media=1\tvendor_at_rules=1\tkeyframes=1\tkeyframe_selectors=2\tdeclarations=5\tvendor_prefixes=3\n");
        }
        "css_l4_nested_layout_fact_stream" => {
            out.push_str("nested_rule\tparent=0\tidx=0\tdepth=1\n");
            out.push_str("property_group\tkind=grid\tdecls=3\n");
            out.push_str("property_group\tkind=flex\tdecls=4\n");
            out.push_str("property_group\tkind=logical\tdecls=4\n");
            out.push_str("end\trules=3\tnested_rules=1\tdeclarations=14\tgrid_decls=3\tflex_decls=4\tlogical_decls=4\ttyped_property_groups=6\n");
        }
        _ => {}
    }
}

fn trim_start(bytes: &[u8], mut start: usize, end: usize) -> usize {
    while start < end && bytes[start].is_ascii_whitespace() {
        start += 1;
    }
    start
}

fn trim_end(bytes: &[u8], start: usize, mut end: usize) -> usize {
    while end > start && bytes[end - 1].is_ascii_whitespace() {
        end -= 1;
    }
    end
}

fn trim_url(bytes: &[u8], start: usize, end: usize) -> usize {
    let start = trim_start(bytes, start, end);
    let mut end = trim_end(bytes, start, end);
    if end > start + 1 && matches!(bytes[start], b'"' | b'\'') && bytes[end - 1] == bytes[start] {
        end -= 1;
    }
    end
}

fn starts_number(bytes: &[u8], pos: usize, end: usize) -> bool {
    pos < end && (bytes[pos].is_ascii_digit() || matches!(bytes[pos], b'+' | b'-' | b'.'))
}

fn consume_number(bytes: &[u8], mut pos: usize, end: usize) -> usize {
    if pos < end && matches!(bytes[pos], b'+' | b'-') {
        pos += 1;
    }
    while pos < end && (bytes[pos].is_ascii_digit() || bytes[pos] == b'.') {
        pos += 1;
    }
    pos
}

fn is_ident_start(byte: u8) -> bool {
    byte.is_ascii_alphabetic() || byte == b'_' || byte == b'-'
}

fn is_ident_byte(byte: u8) -> bool {
    is_ident_start(byte) || byte.is_ascii_digit()
}

fn fnv64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

fn push_ascii_lower_hex(out: &mut String, text: &str) {
    let mut buf = Vec::with_capacity(text.len());
    for byte in text.bytes() {
        buf.push(byte.to_ascii_lowercase());
    }
    push_hex(out, &buf);
}

fn push_hex64(out: &mut String, value: u64) {
    out.push_str(&format!("{value:016x}"));
}

fn push_hex(out: &mut String, bytes: &[u8]) {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in bytes {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 0x0f) as usize] as char);
    }
}
