// SERVED MODEL: claude-opus-5-5
import { describe, it, expect } from "vitest";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { check, generate, EMITTER_SHA256 } from "../src/gen.js";

/** `bbnf gen` / `--check` (the API the CLI runs): deterministic output, drift detected byte-exactly. */
describe("bbnf gen", () => {
    const dir = mkdtempSync(join(tmpdir(), "bbnf-gen-"));
    writeFileSync(join(dir, "tokens.bbnf"), `num = /[0-9]+/ ;\nws = /\\s*/ ;\n`);
    writeFileSync(join(dir, "sum.bbnf"), `@import "tokens.bbnf" ;\nsum = num , ( ws >> "+" << ws , num ) * ;\n`);
    const opts = {
        grammar: join(dir, "sum.bbnf"),
        read: (id: string) => readFileSync(id, "utf8"),
        actions: { num: { kind: "text" as const, fn: Number } },
        entries: ["sum"],
    };

    it("two emissions are byte-identical", () => {
        const a = generate(opts), b = generate(opts);
        expect(a.js).toBe(b.js);
        expect(a.dts).toBe(b.dts);
        expect(a.js.split("\n")[1]).toBe(`// sha256(grammar ⊕ emitter) ${a.sha256}`);
        expect(EMITTER_SHA256).toMatch(/^[0-9a-f]{64}$/);
    });

    it("--check passes on the generated bytes, fails after a one-byte grammar edit, passes after regeneration", () => {
        const onDisk = generate(opts);
        expect(check(generate(opts), onDisk)).toEqual([]);
        writeFileSync(join(dir, "tokens.bbnf"), `num = /[0-8]+/ ;\nws = /\\s*/ ;\n`); // an imported module, one byte
        expect(check(generate(opts), onDisk)).toEqual(["js", "d.ts"]);
        const regenerated = generate(opts);
        expect(check(generate(opts), regenerated)).toEqual([]);
        writeFileSync(join(dir, "tokens.bbnf"), `num = /[0-9]+/ ;\nws = /\\s*/ ;\n`);
    });

    it("the module runs: createParser binds the table once, entries answer value | FAIL", async () => {
        const g = generate(opts);
        const file = join(dir, "sum.generated.js");
        writeFileSync(file, g.js);
        const m = await import(file);
        const p = m.createParser({ num: { kind: "text", fn: Number } });
        expect(p.entries.sum("1 + 2+3")).toEqual([1, [["+", 2], ["+", 3]]]);
        expect(p.entries.sum("1 +")).toBe(m.FAIL);
        expect(m.FAIL).toBe(Symbol.for("@mkbabb/bbnf-lang/FAIL"));
        expect(() => m.createParser({})).toThrow(/needs a text action/);
        expect(() => m.createParser({ num: { kind: "map", fn: Number } })).toThrow(/needs a text action/);
        expect(() => m.createParser({ num: { kind: "text", fn: Number }, sum: { kind: "map", fn: String } })).toThrow(/stale/);
    });
});
