// SERVED MODEL: claude-opus-5-5
//
// gen.ts — build-time generation (node): a grammar's module graph → the emitted ES module and its
// `.d.ts`, headed `sha256(grammar ⊕ emitter)`; `check` answers whether files on disk are what the
// grammar and this emitter generate now (`bbnf gen --check`). The action KINDS come from the
// consumer's own action table (each entry `{ kind, fn }`), so the typed `Actions` and the table
// cannot drift apart silently.

import { createHash } from "node:crypto";
import emitSource from "./emit.ts?raw";
import firstSource from "./analysis/first.ts?raw";
import regexSource from "./analysis/regex.ts?raw";
import { emitGrammar } from "./emit.js";
import type { ActionKind } from "./emit.js";
import { loadGrammar } from "./generate.js";
import { dedupGroups } from "./analysis/index.js";
import { dirname, resolve } from "./posix-path.js";

export type GenerateOptions = Readonly<{
    /** The entry grammar's module ID (its `@import`s resolve against it). */
    grammar: string;
    /** The host's reader: module ID → text. */
    read: (id: string) => string;
    /** The consumer's action table: rule → `{ kind }` (the functions are not read). */
    actions: Readonly<Record<string, { readonly kind: ActionKind }>>;
    /** Entry rules (default: every rule). */
    entries?: readonly string[];
    /** Back-edge nesting limit (default: the emitter's). */
    maxDepth?: number;
    /** Evidence builds only: the per-rule profile (`EmitOptions.instrument`); never a shipped module. */
    instrument?: boolean;
}>;

export type Generated = Readonly<{ js: string; dts: string; sha256: string }>;

/** The emitter's identity: its own source and the analysis it compiles from. */
export const EMITTER_SHA256 = sha256(`${emitSource}\u0000${firstSource}\u0000${regexSource}`);

function sha256(text: string): string {
    return createHash("sha256").update(text).digest("hex");
}

/** Generates the module and declarations for a grammar. Deterministic: same inputs, same bytes. */
export function generate(options: GenerateOptions): Generated {
    const texts = new Map<string, string>();
    const read = (id: string) => { const t = options.read(id); texts.set(id, t); return t; };
    const [ast, recovers] = loadGrammar(options.grammar, read);
    dedupGroups(ast);
    // The grammar's identity: every module it reads, by ID relative to the entry's directory.
    const base = dirname(resolve(options.grammar));
    const rel = (id: string) => (id.startsWith(`${base}/`) ? id.slice(base.length + 1) : id);
    const grammarKey = [...texts].map(([id, t]) => [rel(id), t] as const).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([id, t]) => `${id}\u0000${t}`).join("\u0000");
    const digest = sha256(`${sha256(grammarKey)}${EMITTER_SHA256}`);
    const header = `// GENERATED by @mkbabb/bbnf-lang \`bbnf gen\` from ${rel(resolve(options.grammar))} — DO NOT EDIT.\n// sha256(grammar ⊕ emitter) ${digest}\n${
        options.instrument ? "// INSTRUMENTED: an evidence build with the per-rule profile; never ship it.\n" : ""}`;
    const actionKinds = Object.fromEntries(Object.entries(options.actions).map(([n, a]) => [n, a.kind]));
    const e = emitGrammar(ast, { actionKinds, entries: options.entries, recovers, maxDepth: options.maxDepth, header, instrument: options.instrument });
    return { js: e.module, dts: e.dts, sha256: digest };
}

/** Which of the generated files differ from `on disk` (empty: in sync). */
export function check(generated: Generated, onDisk: Readonly<{ js: string | undefined; dts: string | undefined }>): string[] {
    const drift: string[] = [];
    if (onDisk.js !== generated.js) drift.push("js");
    if (onDisk.dts !== generated.dts) drift.push("d.ts");
    return drift;
}
