// @generated by xtask regen-google-sheets; do not edit by hand.
use crate::runtime::google_sheets::arena::{
    SheetsArena, SheetsCompoundId, SheetsCompoundView,
};
use crate::runtime::google_sheets::value::SheetsValue;
use super::SheetsDocument;
#[derive(Debug, Clone, Copy)]
pub struct SheetsView<'a, 'p: 'a> {
    pub(crate) doc: &'a SheetsDocument<'p>,
    pub(crate) focus: SheetsValue<'p>,
}
impl<'a, 'p: 'a> SheetsView<'a, 'p> {
    #[inline]
    pub fn focused(doc: &'a SheetsDocument<'p>, focus: SheetsValue<'p>) -> Self {
        Self { doc, focus }
    }
    #[inline]
    pub fn document(&self) -> &'a SheetsDocument<'p> {
        self.doc
    }
    #[inline]
    pub fn focus(&self) -> SheetsValue<'p> {
        self.focus
    }
    #[inline]
    pub fn root(&self) -> &'a SheetsValue<'p> {
        &self.doc.root
    }
    #[inline]
    pub fn arena(&self) -> &'a SheetsArena<'p> {
        &self.doc.arena
    }
    #[inline]
    pub fn compound(&self, id: SheetsCompoundId) -> SheetsCompoundView<'a, 'p> {
        self.doc.compound(id)
    }
    #[inline]
    pub fn kind(&self) -> SheetsKind {
        match &self.focus {
            SheetsValue::Number(_) => SheetsKind::Number,
            SheetsValue::String(_) => SheetsKind::String,
            SheetsValue::Bool(_) => SheetsKind::Bool,
            SheetsValue::Error(_) => SheetsKind::Error,
            SheetsValue::CellRef(_) => SheetsKind::CellRef,
            SheetsValue::Identifier(_) => SheetsKind::Identifier,
            SheetsValue::SheetPrefix { .. } => SheetsKind::SheetPrefix,
            SheetsValue::Tag(_) => SheetsKind::Tag,
            SheetsValue::Compound(_) => SheetsKind::Compound,
        }
    }
    #[inline]
    pub fn is_compound(&self) -> bool {
        matches!(self.focus, SheetsValue::Compound(_))
    }
    #[inline]
    pub fn is_number(&self) -> bool {
        matches!(self.focus, SheetsValue::Number(_))
    }
    #[inline]
    pub fn is_string(&self) -> bool {
        matches!(
            self.focus, SheetsValue::String(_) | SheetsValue::CellRef(_) |
            SheetsValue::Identifier(_) | SheetsValue::SheetPrefix { .. }
        )
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SheetsKind {
    Number,
    String,
    Bool,
    Error,
    CellRef,
    Identifier,
    SheetPrefix,
    Tag,
    Compound,
}
