[workspace]
members = ["crates/core", "crates/derive", "crates/analysis", "crates/ir", "crates/lsp", "crates/ser", "crates/gorgeous", "crates/bootstrap", "crates/egraph", "crates/egraph-derive", "crates/csp-solver", "crates/bbnf-tape"]
exclude = ["wasm"]
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 1
debug = true
strip = false
split-debuginfo = "packed"

[profile.dev]
incremental = true
codegen-units = 16

[profile.dev.package.bbnf-ir]
opt-level = 1

[profile.dev.package.csp-solver]
opt-level = 1

[profile.dev.package.parse_that]
opt-level = 1
