//! Rule- and grammar-level emission for the TypeScript backend:
//! rule_function / type_definitions / emit_grammar.
//!
//! Each method is `pub(super)` so the trait impl in `mod.rs` can delegate
//! to it via `self.emit_xxx_impl(...)`.

use bbnf_ir::{GrammarIR, IrRule};

use crate::backend::driver::analysis::BackendAnalysis;

use super::{TsCode, TsEmitCtx, TsEmitter, type_desc_to_ts};

impl TsEmitter {
    pub(super) fn emit_rule_function_impl(
        &mut self,
        rule: &IrRule,
        body: TsCode,
        _sync_body: Option<TsCode>,
        ir: &GrammarIR,
        _ctx: &mut TsEmitCtx,
    ) -> TsCode {
        let name = ir.get_string(rule.name);
        let enum_name = &self.enum_name;

        let return_type = ir
            .types
            .iter()
            .find(|(id, _)| *id == rule.id)
            .map(|(_, td)| type_desc_to_ts(td, enum_name, ir))
            .unwrap_or_else(|| "Span".to_string());

        let fn_body = if body.stmts.is_empty() {
            format!("  return {};\n", body.expr)
        } else {
            format!("  {}\n  return {};\n", body.stmts, body.expr)
        };

        if rule.meta.is_transparent {
            TsCode::expr(format!(
                "function __{name}(s: ParserState): {return_type} | null {{\n{fn_body}}}\n"
            ))
        } else {
            TsCode::expr(format!(
                "function __{name}(s: ParserState): {enum_name} | null {{\n\
                 {fn_body}\
                 }}\n"
            ))
        }
    }

    pub(super) fn emit_type_definitions_impl(
        &mut self,
        ir: &GrammarIR,
        _analysis: &BackendAnalysis,
        _ctx: &mut TsEmitCtx,
    ) -> TsCode {
        let enum_name = &self.enum_name;

        let variants: Vec<String> = ir
            .rules
            .iter()
            .filter(|r| !r.meta.is_transparent)
            .map(|r| {
                let name = ir.get_string(r.name);
                let value_type = ir
                    .types
                    .iter()
                    .find(|(id, _)| *id == r.id)
                    .map(|(_, td)| type_desc_to_ts(td, enum_name, ir))
                    .unwrap_or_else(|| "Span".to_string());
                format!("  | {{ tag: \"{name}\"; value: {value_type} }}")
            })
            .collect();

        let union_body = variants.join("\n");

        TsCode::expr(format!(
            "// ── Runtime types ────────────────────────────────────────────────\n\n\
             interface ParserState {{\n  input: string;\n  offset: number;\n}}\n\n\
             interface Span {{\n  start: number;\n  end: number;\n}}\n\n\
             function span(start: number, end: number): Span {{\n  return {{ start, end }};\n}}\n\n\
             function createState(input: string): ParserState {{\n  return {{ input, offset: 0 }};\n}}\n\n\
             // ── Grammar types ───────────────────────────────────────────────\n\n\
             type {enum_name} =\n{union_body};\n\n"
        ))
    }

    pub(super) fn emit_grammar_impl(
        &mut self,
        type_defs: TsCode,
        rule_functions: Vec<TsCode>,
        ir: &GrammarIR,
        ctx: &mut TsEmitCtx,
    ) -> TsCode {
        let entry_name = ir.get_string(ir.rules[ir.entry as usize].name);

        let mut output = String::new();
        output.push_str("// Generated by BBNF — do not edit.\n\n");
        output.push_str(&type_defs.expr);

        if !ctx.hoisted_regexes.is_empty() {
            output.push_str(
                "// ── Hoisted regex constants ──────────────────────────────────────\n\n",
            );
            for decl in &ctx.hoisted_regexes {
                output.push_str(decl);
                output.push('\n');
            }
            output.push('\n');
        }

        output.push_str("// ── Parser functions ─────────────────────────────────────────────\n\n");
        for func in &rule_functions {
            output.push_str(&func.expr);
            output.push('\n');
        }

        output.push_str(&format!(
            "// ── Public API ──────────────────────────────────────────────────\n\n\
             export function parse(input: string): {{ result: {enum_name} | null; offset: number }} {{\n  \
             const s = createState(input);\n  \
             const result = __{entry_name}(s);\n  \
             return {{ result, offset: s.offset }};\n}}\n",
            enum_name = self.enum_name,
        ));

        TsCode::expr(output)
    }
}
