//! Rule-level and grammar-level emission for the WASM backend.
//!
//! Each method is `pub(super)` so the trait impl in `mod.rs` can delegate
//! to it via `self.emit_xxx_impl(...)`.

use bbnf_ir::{GrammarIR, IrRule};

use super::{WasmEmitCtx, WasmEmitter};
use crate::backend::driver::analysis::BackendAnalysis;

impl WasmEmitter {
    pub(super) fn emit_rule_function_impl(
        &mut self,
        rule: &IrRule,
        body: String,
        _sync_body: Option<String>,
        ir: &GrammarIR,
        ctx: &mut WasmEmitCtx,
    ) -> String {
        let name = ir.get_string(rule.name);
        let locals = ctx.drain_locals();
        format!(
            "  (func $__{name} (param $off i32) (param $len i32) (result i32)\n    \
             {locals}\n    \
             {body}\n  )\n"
        )
    }

    pub(super) fn emit_type_definitions_impl(
        &mut self,
        _ir: &GrammarIR,
        _analysis: &BackendAnalysis,
        _ctx: &mut WasmEmitCtx,
    ) -> String {
        "  ;; Host imports: our DFA regex engine + number scanner\n  \
         (import \"host\" \"match_regex\" (func $__match_regex (param i32 i32 i32) (result i32)))\n  \
         (import \"host\" \"number_convert\" (func $__number_convert (param i32 i32) (result i32)))\n  \
         (memory (export \"memory\") 1)\n"
            .to_string()
    }

    pub(super) fn emit_grammar_impl(
        &mut self,
        type_defs: String,
        rule_functions: Vec<String>,
        ir: &GrammarIR,
        _ctx: &mut WasmEmitCtx,
    ) -> String {
        let entry_name = ir.get_string(ir.rules[ir.entry as usize].name);
        let module_name = &self.module_name;

        let mut output = format!(
            ";; Generated by BBNF — do not edit.\n(module ${module_name}\n"
        );
        output.push_str(&type_defs);
        output.push('\n');
        for func in &rule_functions {
            output.push_str(func);
        }
        output.push_str(&format!(
            "\n  (export \"parse\" (func $__{entry_name}))\n"
        ));
        output.push_str(")\n");
        output
    }
}
