// @generated by xtask regen-csv; do not edit by hand.
use crate::runtime::csv::arena::{CsvArena, CsvCompoundId};
use crate::runtime::csv::kind::{CsvCompound, CsvCompoundKind};
use crate::runtime::csv::value::CsvValue;
use crate::runtime::path::{Path, PathSegment};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CsvKind {
    Span,
    Unit,
    Compound,
}
#[derive(Debug)]
pub struct CsvDocument<'p> {
    pub arena: CsvArena<'p>,
    pub root: CsvValue<'p>,
    pub input: &'p str,
}
impl<'p> CsvDocument<'p> {
    #[inline]
    pub fn new(arena: CsvArena<'p>, root: CsvValue<'p>, input: &'p str) -> Self {
        Self { arena, root, input }
    }
    #[inline]
    pub fn root(&self) -> &CsvValue<'p> {
        &self.root
    }
    #[inline]
    pub fn arena(&self) -> &CsvArena<'p> {
        &self.arena
    }
    #[inline]
    pub fn input(&self) -> &'p str {
        self.input
    }
    #[inline]
    pub fn compound(&self, id: CsvCompoundId) -> &CsvCompound<'p> {
        self.arena.compound(id)
    }
    #[inline]
    pub fn view<'a>(&'a self) -> CsvView<'a, 'p> {
        CsvView {
            doc: self,
            focus: self.root,
        }
    }
    #[inline]
    pub fn to_value(&self) -> &CsvValue<'p> {
        &self.root
    }
    #[inline]
    pub fn get<T: CsvPathQuery>(&self, path: Path<'_>) -> Option<T> {
        T::query(self, path)
    }
}
#[derive(Debug, Clone, Copy)]
pub struct CsvView<'a, 'p: 'a> {
    pub(crate) doc: &'a CsvDocument<'p>,
    pub(crate) focus: CsvValue<'p>,
}
impl<'a, 'p: 'a> CsvView<'a, 'p> {
    #[inline]
    pub fn focused(doc: &'a CsvDocument<'p>, focus: CsvValue<'p>) -> Self {
        Self { doc, focus }
    }
    #[inline]
    pub fn document(&self) -> &'a CsvDocument<'p> {
        self.doc
    }
    #[inline]
    pub fn focus(&self) -> CsvValue<'p> {
        self.focus
    }
    #[inline]
    pub fn root(&self) -> &'a CsvValue<'p> {
        &self.doc.root
    }
    #[inline]
    pub fn arena(&self) -> &'a CsvArena<'p> {
        &self.doc.arena
    }
    #[inline]
    pub fn compound(&self, id: CsvCompoundId) -> &'a CsvCompound<'p> {
        self.doc.compound(id)
    }
    #[inline]
    pub fn kind(&self) -> CsvKind {
        match &self.focus {
            CsvValue::Span(_) => CsvKind::Span,
            CsvValue::Unit => CsvKind::Unit,
            CsvValue::Compound(_) => CsvKind::Compound,
        }
    }
    #[inline]
    pub fn is_compound(&self) -> bool {
        matches!(self.focus, CsvValue::Compound(_))
    }
    #[inline]
    pub fn is_span(&self) -> bool {
        matches!(self.focus, CsvValue::Span(_))
    }
    #[inline]
    pub fn input(&self) -> &'p str {
        self.doc.input
    }
    #[inline]
    pub fn compound_kind(&self) -> Option<CsvCompoundKind> {
        match self.focus {
            CsvValue::Compound(id) => Some(self.doc.compound(id).kind),
            _ => None,
        }
    }
}
pub trait CsvPathQuery: Sized {
    fn query<'p>(doc: &CsvDocument<'p>, path: Path<'_>) -> Option<Self>;
}
#[inline]
fn walk_path<'a, 'p>(
    doc: &'a CsvDocument<'p>,
    path: Path<'_>,
) -> Option<&'a CsvValue<'p>> {
    let mut current: &'a CsvValue<'p> = &doc.root;
    for segment in path.iter() {
        current = match (current, segment) {
            (CsvValue::Compound(id), PathSegment::Index(idx)) => {
                let entry = doc.compound(*id);
                entry.children.get(*idx)?
            }
            (CsvValue::Compound(_), PathSegment::Field(_)) => return None,
            _ => return None,
        };
    }
    Some(current)
}
impl CsvPathQuery for &str {
    #[inline]
    fn query<'p>(doc: &CsvDocument<'p>, path: Path<'_>) -> Option<Self> {
        match walk_path(doc, path)? {
            CsvValue::Span(s) => {
                let extended: &'p str = *s;
                Some(unsafe { core::mem::transmute::<&'p str, &str>(extended) })
            }
            _ => None,
        }
    }
}
impl CsvPathQuery for CsvValue<'_> {
    #[inline]
    fn query<'p>(doc: &CsvDocument<'p>, path: Path<'_>) -> Option<Self> {
        let value = walk_path(doc, path)?;
        let copied: CsvValue<'p> = *value;
        Some(unsafe { core::mem::transmute::<CsvValue<'p>, CsvValue<'_>>(copied) })
    }
}
