// @generated by skinny bbnf-codegen; do not edit by hand.
use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CssFactError {
    pub offset: usize,
    pub message: &'static str,
}

impl fmt::Display for CssFactError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} at byte {}", self.message, self.offset)
    }
}

impl std::error::Error for CssFactError {}
