// @generated by skinny bbnf-codegen; do not edit by hand.
use super::config;
use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CssFactError {
    pub offset: usize,
    pub message: &'static str,
}

impl fmt::Display for CssFactError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} at byte {}", self.message, self.offset)
    }
}

impl std::error::Error for CssFactError {}

pub struct FactSink<'i> {
    input: &'i str,
}

impl<'i> FactSink<'i> {
    pub fn new(input: &'i str) -> Self {
        Self { input }
    }

    pub fn unsupported(&mut self, offset: usize) -> Result<String, CssFactError> {
        let _ = (
            config::ROW_ID,
            config::OUTPUT_PLANE,
            config::FACT_SCHEMA,
            self.input,
        );
        Err(CssFactError {
            offset,
            message: "unsupported CSS nested/layout fixture",
        })
    }
}
