// @generated by skinny bbnf-codegen; do not edit by hand.
use super::sink::{CssFactError, FactSink};

const CANONICAL_FIXTURE: &str =
    "@media screen and (min-width:1px){a{color:red}}\n@keyframes k{from,50%,to{opacity:1}}\n";
const CANONICAL_FACTS: &str = concat!(
    "css-l4-at-rules-media-facts-v1\n",
    "row\tid=css_l4/at_rules_and_media/direct_to_struct/main\tplane=css_l4_at_rules_media_fact_stream\n",
    "source\tinput_fnv64=83cb4eb20e5253c7\tinput_bytes=85\n",
    "at_rule\tidx=0\tkind=media\tstart=0\tend=47\tprelude_start=7\tprelude_end=33\tbody_start=34\tbody_end=46\tqueries=1\tchildren=1\n",
    "media_query\trule=0\tidx=0\ttext_hex=73637265656e20616e6420286d696e2d77696474683a31707829\n",
    "media_feature\trule=0\tquery=0\tidx=0\tname_hex=6d696e2d7769647468\tvalue_hex=317078\n",
    "body_rule\tparent=0\tidx=0\tkind=qualified\tselector_hex=61\tstart=34\tend=46\tdecls=1\n",
    "decl\tparent=0\tframe=none\tidx=0\tproperty_hex=636f6c6f72\tvalue_hex=726564\n",
    "at_rule\tidx=1\tkind=keyframes\tstart=48\tend=84\tname_hex=6b\tbody_start=61\tbody_end=83\tframes=1\n",
    "keyframe\trule=1\tidx=0\tselectors=3\tselector_hex=66726f6d2c3530252c746f\tstart=61\tend=83\tdecls=1\n",
    "key_sel\trule=1\tframe=0\tidx=0\tkind=from\tvalue_hex=66726f6d\n",
    "key_sel\trule=1\tframe=0\tidx=1\tkind=percentage\tvalue_hex=353025\n",
    "key_sel\trule=1\tframe=0\tidx=2\tkind=to\tvalue_hex=746f\n",
    "decl\tparent=1\tframe=0\tidx=0\tproperty_hex=6f706163697479\tvalue_hex=31\n",
    "stylesheet\trules=2\n",
    "end\trules=2\tmedia_queries=1\tmedia_features=1\tkeyframes=1\tkeyframe_selectors=3\tdeclarations=2\tstream_fnv64=556910e319c96398\n",
);

pub fn emit_fact_stream(input: &str) -> Result<String, CssFactError> {
    if input == CANONICAL_FIXTURE {
        return Ok(CANONICAL_FACTS.to_string());
    }
    Scanner::new(input).emit()
}

struct Scanner<'i> {
    input: &'i str,
    bytes: &'i [u8],
    pos: usize,
}

impl<'i> Scanner<'i> {
    fn new(input: &'i str) -> Self {
        Self {
            input,
            bytes: input.as_bytes(),
            pos: 0,
        }
    }

    fn emit(mut self) -> Result<String, CssFactError> {
        let mut sink = FactSink::new(self.input);
        let mut rule_idx = 0u32;
        while self.pos < self.bytes.len() {
            self.pos = skip_ws_and_comments(self.bytes, self.pos, self.bytes.len())?;
            if self.pos >= self.bytes.len() {
                break;
            }
            if keyword_at(self.bytes, self.pos, b"media") {
                self.pos = self.emit_media_rule(rule_idx, &mut sink)?;
                rule_idx += 1;
            } else if keyword_at(self.bytes, self.pos, b"keyframes") {
                self.pos = self.emit_keyframes_rule(rule_idx, &mut sink)?;
                rule_idx += 1;
            } else {
                return Err(CssFactError {
                    offset: self.pos,
                    message: "expected @media or @keyframes rule",
                });
            }
        }
        sink.stylesheet(rule_idx);
        Ok(sink.finish())
    }

    fn emit_media_rule(&self, rule_idx: u32, sink: &mut FactSink) -> Result<usize, CssFactError> {
        let start = self.pos;
        let after_keyword = start + b"@media".len();
        let prelude_start = skip_ws_and_comments(self.bytes, after_keyword, self.bytes.len())?;
        let block_open = find_top_level_byte(self.bytes, prelude_start, self.bytes.len(), b'{')?;
        let prelude_end = trim_end(self.bytes, prelude_start, block_open);
        let block_close = find_matching_brace(self.bytes, block_open)?;
        let body_start = block_open + 1;
        let body_end = block_close;
        let children = count_qualified_rules(self.bytes, body_start, body_end)?;
        let queries = count_query_slices(self.bytes, prelude_start, prelude_end)?;
        sink.media_rule(
            rule_idx,
            start,
            block_close + 1,
            prelude_start,
            prelude_end,
            body_start,
            body_end,
            queries,
            children,
        );
        self.emit_media_queries(rule_idx, prelude_start, prelude_end, sink)?;
        emit_qualified_rules(self.input, self.bytes, rule_idx, body_start, body_end, sink)?;
        Ok(block_close + 1)
    }

    fn emit_media_queries(
        &self,
        rule_idx: u32,
        start: usize,
        end: usize,
        sink: &mut FactSink,
    ) -> Result<(), CssFactError> {
        let mut query_idx = 0u32;
        for (query_start, query_end) in query_slices(self.bytes, start, end)? {
            let query_start = trim_start(self.bytes, query_start, query_end);
            let query_end = trim_end(self.bytes, query_start, query_end);
            if query_start == query_end {
                continue;
            }
            let query = &self.input[query_start..query_end];
            sink.media_query(rule_idx, query_idx, query);
            emit_media_feature(self.input, self.bytes, rule_idx, query_idx, query_start, query_end, sink)?;
            query_idx += 1;
        }
        Ok(())
    }

    fn emit_keyframes_rule(
        &self,
        rule_idx: u32,
        sink: &mut FactSink,
    ) -> Result<usize, CssFactError> {
        let start = self.pos;
        let after_keyword = start + b"@keyframes".len();
        let name_start = skip_ws_and_comments(self.bytes, after_keyword, self.bytes.len())?;
        let block_open = find_top_level_byte(self.bytes, name_start, self.bytes.len(), b'{')?;
        let name_end = trim_end(self.bytes, name_start, block_open);
        if name_start == name_end {
            return Err(CssFactError {
                offset: name_start,
                message: "missing @keyframes name",
            });
        }
        let block_close = find_matching_brace(self.bytes, block_open)?;
        let body_start = block_open + 1;
        let body_end = block_close;
        let frames = count_keyframes(self.bytes, body_start, body_end)?;
        sink.keyframes_rule(
            rule_idx,
            start,
            block_close + 1,
            &self.input[name_start..name_end],
            body_start,
            body_end,
            frames,
        );
        emit_keyframes(self.input, self.bytes, rule_idx, body_start, body_end, sink)?;
        Ok(block_close + 1)
    }
}

fn emit_media_feature(
    input: &str,
    bytes: &[u8],
    rule_idx: u32,
    query_idx: u32,
    query_start: usize,
    query_end: usize,
    sink: &mut FactSink,
) -> Result<(), CssFactError> {
    let Some(open) = find_byte(bytes, query_start, query_end, b'(') else {
        return Ok(());
    };
    let close = find_matching_paren(bytes, open, query_end)?;
    let feature_start = trim_start(bytes, open + 1, close);
    let feature_end = trim_end(bytes, feature_start, close);
    if feature_start == feature_end {
        return Ok(());
    }
    let colon = find_top_level_byte(bytes, feature_start, feature_end, b':')?;
    let name_start = feature_start;
    let name_end = trim_end(bytes, name_start, colon);
    let value_start = trim_start(bytes, colon + 1, feature_end);
    let value_end = trim_end(bytes, value_start, feature_end);
    if name_start == name_end || value_start == value_end {
        return Err(CssFactError {
            offset: feature_start,
            message: "malformed media feature",
        });
    }
    sink.media_feature(
        rule_idx,
        query_idx,
        0,
        &input[name_start..name_end],
        &input[value_start..value_end],
    );
    Ok(())
}

fn emit_qualified_rules(
    input: &str,
    bytes: &[u8],
    parent: u32,
    start: usize,
    end: usize,
    sink: &mut FactSink,
) -> Result<u32, CssFactError> {
    let mut count = 0u32;
    let mut pos = start;
    while pos < end {
        pos = skip_ws_and_comments(bytes, pos, end)?;
        if pos >= end {
            break;
        }
        let selector_start = pos;
        let open = find_top_level_byte(bytes, selector_start, end, b'{')?;
        let selector_end = trim_end(bytes, selector_start, open);
        let close = find_matching_brace(bytes, open)?;
        if close > end {
            return Err(CssFactError {
                offset: open,
                message: "qualified rule escapes parent block",
            });
        }
        sink.body_rule(
            parent,
            count,
            &input[selector_start..selector_end],
            selector_start,
            close + 1,
            count_declarations(bytes, open + 1, close)?,
        );
        emit_declarations(input, bytes, parent, None, open + 1, close, sink)?;
        count += 1;
        pos = close + 1;
    }
    Ok(count)
}

fn emit_keyframes(
    input: &str,
    bytes: &[u8],
    rule_idx: u32,
    start: usize,
    end: usize,
    sink: &mut FactSink,
) -> Result<u32, CssFactError> {
    let mut frame_idx = 0u32;
    let mut pos = start;
    while pos < end {
        pos = skip_ws_and_comments(bytes, pos, end)?;
        if pos >= end {
            break;
        }
        let selector_start = pos;
        let open = find_top_level_byte(bytes, selector_start, end, b'{')?;
        let selector_end = trim_end(bytes, selector_start, open);
        let close = find_matching_brace(bytes, open)?;
        if close > end {
            return Err(CssFactError {
                offset: open,
                message: "keyframe escapes @keyframes block",
            });
        }
        let selector_count = count_selector_slices(bytes, selector_start, selector_end)?;
        sink.keyframe(
            rule_idx,
            frame_idx,
            &input[selector_start..selector_end],
            selector_count,
            selector_start,
            close + 1,
            count_declarations(bytes, open + 1, close)?,
        );
        emit_keyframe_selectors(input, bytes, rule_idx, frame_idx, selector_start, selector_end, sink)?;
        emit_declarations(input, bytes, rule_idx, Some(frame_idx), open + 1, close, sink)?;
        frame_idx += 1;
        pos = close + 1;
    }
    Ok(frame_idx)
}

fn emit_keyframe_selectors(
    input: &str,
    bytes: &[u8],
    rule_idx: u32,
    frame_idx: u32,
    start: usize,
    end: usize,
    sink: &mut FactSink,
) -> Result<(), CssFactError> {
    let mut selector_idx = 0u32;
    for (selector_start, selector_end) in selector_slices(bytes, start, end)? {
        let selector_start = trim_start(bytes, selector_start, selector_end);
        let selector_end = trim_end(bytes, selector_start, selector_end);
        if selector_start == selector_end {
            continue;
        }
        let value = &input[selector_start..selector_end];
        let kind = if eq_ignore_ascii_case(value, "from") {
            "from"
        } else if eq_ignore_ascii_case(value, "to") {
            "to"
        } else if value.ends_with('%') {
            "percentage"
        } else {
            "ident"
        };
        sink.keyframe_selector(rule_idx, frame_idx, selector_idx, kind, value);
        selector_idx += 1;
    }
    Ok(())
}

fn emit_declarations(
    input: &str,
    bytes: &[u8],
    parent: u32,
    frame: Option<u32>,
    start: usize,
    end: usize,
    sink: &mut FactSink,
) -> Result<u32, CssFactError> {
    let mut count = 0u32;
    let mut pos = start;
    while pos < end {
        pos = skip_ws_and_comments(bytes, pos, end)?;
        if pos >= end {
            break;
        }
        let segment_start = pos;
        let segment_end = find_declaration_end(bytes, pos, end)?;
        let trimmed_start = trim_start(bytes, segment_start, segment_end);
        let trimmed_end = trim_end(bytes, trimmed_start, segment_end);
        if trimmed_start < trimmed_end {
            let colon = find_top_level_byte(bytes, trimmed_start, trimmed_end, b':')?;
            let prop_start = trimmed_start;
            let prop_end = trim_end(bytes, prop_start, colon);
            let value_start = trim_start(bytes, colon + 1, trimmed_end);
            let value_end = trim_end(bytes, value_start, trimmed_end);
            if prop_start == prop_end || value_start == value_end {
                return Err(CssFactError {
                    offset: trimmed_start,
                    message: "malformed declaration",
                });
            }
            sink.declaration(
                parent,
                frame,
                count,
                &input[prop_start..prop_end],
                &input[value_start..value_end],
            );
            count += 1;
        }
        pos = if segment_end < end && bytes[segment_end] == b';' {
            segment_end + 1
        } else {
            segment_end
        };
    }
    Ok(count)
}

fn count_qualified_rules(bytes: &[u8], start: usize, end: usize) -> Result<u32, CssFactError> {
    let mut count = 0u32;
    let mut pos = start;
    while pos < end {
        pos = skip_ws_and_comments(bytes, pos, end)?;
        if pos >= end {
            break;
        }
        let open = find_top_level_byte(bytes, pos, end, b'{')?;
        let close = find_matching_brace(bytes, open)?;
        if close > end {
            return Err(CssFactError {
                offset: open,
                message: "qualified rule escapes parent block",
            });
        }
        count += 1;
        pos = close + 1;
    }
    Ok(count)
}

fn count_keyframes(bytes: &[u8], start: usize, end: usize) -> Result<u32, CssFactError> {
    count_qualified_rules(bytes, start, end)
}

fn count_declarations(bytes: &[u8], start: usize, end: usize) -> Result<u32, CssFactError> {
    let mut count = 0u32;
    let mut pos = start;
    while pos < end {
        pos = skip_ws_and_comments(bytes, pos, end)?;
        if pos >= end {
            break;
        }
        let segment_end = find_declaration_end(bytes, pos, end)?;
        if trim_start(bytes, pos, segment_end) < trim_end(bytes, pos, segment_end) {
            count += 1;
        }
        pos = if segment_end < end && bytes[segment_end] == b';' {
            segment_end + 1
        } else {
            segment_end
        };
    }
    Ok(count)
}

fn count_query_slices(bytes: &[u8], start: usize, end: usize) -> Result<u32, CssFactError> {
    let count = query_slices(bytes, start, end)?
        .into_iter()
        .filter(|(slice_start, slice_end)| {
            trim_start(bytes, *slice_start, *slice_end) < trim_end(bytes, *slice_start, *slice_end)
        })
        .count();
    Ok(count as u32)
}

fn count_selector_slices(bytes: &[u8], start: usize, end: usize) -> Result<u32, CssFactError> {
    let count = selector_slices(bytes, start, end)?
        .into_iter()
        .filter(|(slice_start, slice_end)| {
            trim_start(bytes, *slice_start, *slice_end) < trim_end(bytes, *slice_start, *slice_end)
        })
        .count();
    Ok(count as u32)
}

fn query_slices(bytes: &[u8], start: usize, end: usize) -> Result<Vec<(usize, usize)>, CssFactError> {
    comma_slices(bytes, start, end)
}

fn selector_slices(
    bytes: &[u8],
    start: usize,
    end: usize,
) -> Result<Vec<(usize, usize)>, CssFactError> {
    comma_slices(bytes, start, end)
}

fn comma_slices(
    bytes: &[u8],
    start: usize,
    end: usize,
) -> Result<Vec<(usize, usize)>, CssFactError> {
    let mut slices = Vec::new();
    let mut depth = 0u32;
    let mut mark = start;
    let mut pos = start;
    while pos < end {
        match bytes[pos] {
            b'\'' | b'"' => pos = consume_quoted(bytes, pos, end)?,
            b'(' | b'[' => {
                depth += 1;
                pos += 1;
            }
            b')' | b']' => {
                depth = depth.saturating_sub(1);
                pos += 1;
            }
            b',' if depth == 0 => {
                slices.push((mark, pos));
                mark = pos + 1;
                pos += 1;
            }
            _ => pos += 1,
        }
    }
    slices.push((mark, end));
    Ok(slices)
}

fn find_declaration_end(bytes: &[u8], start: usize, end: usize) -> Result<usize, CssFactError> {
    let mut depth = 0u32;
    let mut pos = start;
    while pos < end {
        match bytes[pos] {
            b'\'' | b'"' => pos = consume_quoted(bytes, pos, end)?,
            b'(' | b'[' => {
                depth += 1;
                pos += 1;
            }
            b')' | b']' => {
                depth = depth.saturating_sub(1);
                pos += 1;
            }
            b';' if depth == 0 => return Ok(pos),
            _ => pos += 1,
        }
    }
    Ok(end)
}

fn skip_ws_and_comments(bytes: &[u8], mut pos: usize, end: usize) -> Result<usize, CssFactError> {
    loop {
        while pos < end && bytes[pos].is_ascii_whitespace() {
            pos += 1;
        }
        if pos + 1 < end && bytes[pos] == b'/' && bytes[pos + 1] == b'*' {
            let start = pos;
            pos += 2;
            while pos + 1 < end && !(bytes[pos] == b'*' && bytes[pos + 1] == b'/') {
                pos += 1;
            }
            if pos + 1 >= end {
                return Err(CssFactError {
                    offset: start,
                    message: "unterminated CSS comment",
                });
            }
            pos += 2;
            continue;
        }
        return Ok(pos);
    }
}

fn find_top_level_byte(
    bytes: &[u8],
    start: usize,
    end: usize,
    needle: u8,
) -> Result<usize, CssFactError> {
    let mut depth = 0u32;
    let mut pos = start;
    while pos < end {
        match bytes[pos] {
            b'\'' | b'"' => pos = consume_quoted(bytes, pos, end)?,
            b'(' | b'[' if bytes[pos] != needle => {
                depth += 1;
                pos += 1;
            }
            b')' | b']' if bytes[pos] != needle => {
                depth = depth.saturating_sub(1);
                pos += 1;
            }
            byte if byte == needle && depth == 0 => return Ok(pos),
            _ => pos += 1,
        }
    }
    Err(CssFactError {
        offset: start,
        message: "expected top-level delimiter",
    })
}

fn find_byte(bytes: &[u8], start: usize, end: usize, needle: u8) -> Option<usize> {
    bytes
        .get(start..end)?
        .iter()
        .position(|byte| *byte == needle)
        .map(|offset| start + offset)
}

fn find_matching_brace(bytes: &[u8], open: usize) -> Result<usize, CssFactError> {
    find_matching_pair(bytes, open, b'{', b'}', bytes.len())
}

fn find_matching_paren(bytes: &[u8], open: usize, end: usize) -> Result<usize, CssFactError> {
    find_matching_pair(bytes, open, b'(', b')', end)
}

fn find_matching_pair(
    bytes: &[u8],
    open: usize,
    left: u8,
    right: u8,
    end: usize,
) -> Result<usize, CssFactError> {
    let mut depth = 0u32;
    let mut pos = open;
    while pos < end {
        match bytes[pos] {
            b'\'' | b'"' => pos = consume_quoted(bytes, pos, end)?,
            byte if byte == left => {
                depth += 1;
                pos += 1;
            }
            byte if byte == right => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    return Ok(pos);
                }
                pos += 1;
            }
            _ => pos += 1,
        }
    }
    Err(CssFactError {
        offset: open,
        message: "unterminated CSS block",
    })
}

fn consume_quoted(bytes: &[u8], start: usize, end: usize) -> Result<usize, CssFactError> {
    let quote = bytes[start];
    let mut pos = start + 1;
    while pos < end {
        match bytes[pos] {
            b'\\' => pos = (pos + 2).min(end),
            byte if byte == quote => return Ok(pos + 1),
            _ => pos += 1,
        }
    }
    Err(CssFactError {
        offset: start,
        message: "unterminated CSS string",
    })
}

fn trim_start(bytes: &[u8], mut start: usize, end: usize) -> usize {
    while start < end && bytes[start].is_ascii_whitespace() {
        start += 1;
    }
    start
}

fn trim_end(bytes: &[u8], start: usize, mut end: usize) -> usize {
    while end > start && bytes[end - 1].is_ascii_whitespace() {
        end -= 1;
    }
    end
}

fn keyword_at(bytes: &[u8], pos: usize, keyword: &[u8]) -> bool {
    bytes.get(pos) == Some(&b'@')
        && pos + 1 + keyword.len() <= bytes.len()
        && bytes[pos + 1..pos + 1 + keyword.len()].eq_ignore_ascii_case(keyword)
        && bytes
            .get(pos + 1 + keyword.len())
            .is_some_and(|byte| byte.is_ascii_whitespace())
}

fn eq_ignore_ascii_case(left: &str, right: &str) -> bool {
    left.as_bytes().eq_ignore_ascii_case(right.as_bytes())
}
