// @generated by skinny bbnf-codegen; do not edit by hand.
pub(crate) const FACT_SCHEMA: &str = "css-l4-declaration-value-extended-facts-v1";
pub(crate) const ROW_ID: &str = "css_l4/declaration_values_extended/direct_to_struct/main";
pub(crate) const OUTPUT_PLANE: &str = "css_l4_declaration_value_extended_fact_stream";
