// @generated by skinny bbnf-codegen; do not edit by hand.
pub(crate) mod config;
pub mod generated;
pub mod parser;
pub mod sink;

pub use generated::{
    CssDeclaration, CssDocument, CssNode, CssNodeKind, CssRichSummary, CssRule, CssSummary,
    CssTypedNode, CssTypedValue,
};
pub use parser::{parse, parse_bytes, rich_summary, rich_summary_bytes, summary, summary_bytes};
pub use sink::CssFactError;
