// @generated by skinny bbnf-codegen; do not edit by hand.
pub(crate) mod config;
pub mod generated;
pub mod parser;
pub mod sink;

pub use generated::{CssDocument, CssNode, CssNodeKind, CssSummary};
pub use parser::{parse, parse_bytes, summary, summary_bytes};
pub use sink::CssFactError;
