// @generated by skinny bbnf-codegen; do not edit by hand.
use super::generated::{self, CssDocument, CssRichSummary, CssSummary};
use super::sink::CssFactError;

/// Track-1 admission entry: recognize the stylesheet directly into the
/// EXISTING skinny offset tape and return the lazy tape-backed document.
/// The retired fact-stream `String` plane is gone from this path.
pub fn parse(input: &str) -> Result<CssDocument<'_>, CssFactError> {
    generated::parse_into_tape(input)
}

pub fn parse_bytes(input: &[u8]) -> Result<CssDocument<'_>, CssFactError> {
    let input = std::str::from_utf8(input).map_err(|error| CssFactError {
        offset: error.valid_up_to(),
        message: "invalid UTF-8",
    })?;
    parse(input)
}

/// The lazy 4-field structural summary projected from the tape — the typed
/// product the equality oracle checks (kind from source byte, zero payload).
pub fn summary(input: &str) -> Result<CssSummary, CssFactError> {
    Ok(parse(input)?.summary())
}

pub fn summary_bytes(input: &[u8]) -> Result<CssSummary, CssFactError> {
    Ok(parse_bytes(input)?.summary())
}

/// The RICH typed-CSSOM summary projected lazily from the tape — the fair
/// full-materialization product compared against lightningcss (selectors +
/// typed value-node counts atop the 4 structural fields).
pub fn rich_summary(input: &str) -> Result<CssRichSummary, CssFactError> {
    Ok(parse(input)?.rich_summary())
}

pub fn rich_summary_bytes(input: &[u8]) -> Result<CssRichSummary, CssFactError> {
    Ok(parse_bytes(input)?.rich_summary())
}

pub fn parse_full(input: &str) -> Result<String, CssFactError> {
    generated::emit_full_parse(input)
}

pub fn parse_full_bytes(input: &[u8]) -> Result<String, CssFactError> {
    let input = std::str::from_utf8(input).map_err(|error| CssFactError {
        offset: error.valid_up_to(),
        message: "invalid UTF-8",
    })?;
    parse_full(input)
}
