// @generated by skinny bbnf-codegen; do not edit by hand.
use super::config;
use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CssFactError {
    pub offset: usize,
    pub message: &'static str,
}

impl fmt::Display for CssFactError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} at byte {}", self.message, self.offset)
    }
}

impl std::error::Error for CssFactError {}

pub struct FactSink {
    out: String,
    decls: u32,
    tokens: u32,
    max_depth: u32,
}

impl FactSink {
    pub fn new(input: &str) -> Self {
        let mut out = String::new();
        out.push_str(config::FACT_SCHEMA);
        out.push('\n');
        out.push_str("row\tid=");
        out.push_str(config::ROW_ID);
        out.push_str("\tplane=");
        out.push_str(config::OUTPUT_PLANE);
        out.push('\n');
        out.push_str("source\tinput_fnv64=");
        push_hex64(&mut out, fnv64(input.as_bytes()));
        out.push_str("\tinput_bytes=");
        out.push_str(&input.len().to_string());
        out.push('\n');
        Self {
            out,
            decls: 0,
            tokens: 0,
            max_depth: 0,
        }
    }

    pub fn declaration(
        &mut self,
        idx: u32,
        depth: u32,
        property: &str,
        important: bool,
        value_start: usize,
        value_end: usize,
    ) {
        self.decls += 1;
        self.out.push_str("decl\tidx=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tdepth=");
        self.out.push_str(&depth.to_string());
        self.out.push_str("\tproperty_hex=");
        push_ascii_lower_hex(&mut self.out, property);
        self.out.push_str("\timportant=");
        self.out.push(if important { '1' } else { '0' });
        self.out.push_str("\tvalue_start=");
        self.out.push_str(&value_start.to_string());
        self.out.push_str("\tvalue_end=");
        self.out.push_str(&value_end.to_string());
        self.out.push('\n');
    }

    pub fn token(&mut self, decl: u32, idx: u32, depth: u32, kind: &str, lexeme: &str) {
        self.tokens += 1;
        self.max_depth = self.max_depth.max(depth);
        self.out.push_str("tok\tdecl=");
        self.out.push_str(&decl.to_string());
        self.out.push_str("\tidx=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tdepth=");
        self.out.push_str(&depth.to_string());
        self.out.push_str("\tkind=");
        self.out.push_str(kind);
        self.out.push_str("\tlexeme_hex=");
        if config::token_uses_ascii_lower_hex(kind) {
            push_ascii_lower_hex(&mut self.out, lexeme);
        } else {
            push_hex(&mut self.out, lexeme.as_bytes());
        }
        self.out.push_str("\tflags=");
        self.out.push_str(config::TOKEN_FLAGS_NORMALIZED);
        self.out.push('\n');
    }

    pub fn finish(mut self) -> String {
        let stream_hash = fnv64(self.out.as_bytes());
        self.out.push_str("end\tdecls=");
        self.out.push_str(&self.decls.to_string());
        self.out.push_str("\ttokens=");
        self.out.push_str(&self.tokens.to_string());
        self.out.push_str("\tmax_depth=");
        self.out.push_str(&self.max_depth.to_string());
        self.out.push_str("\tstream_fnv64=");
        push_hex64(&mut self.out, stream_hash);
        self.out.push('\n');
        self.out
    }
}

fn fnv64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

fn push_ascii_lower_hex(out: &mut String, text: &str) {
    let mut buf = Vec::with_capacity(text.len());
    for byte in text.bytes() {
        buf.push(byte.to_ascii_lowercase());
    }
    push_hex(out, &buf);
}

fn push_hex64(out: &mut String, value: u64) {
    out.push_str(&format!("{value:016x}"));
}

fn push_hex(out: &mut String, bytes: &[u8]) {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in bytes {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 0x0f) as usize] as char);
    }
}
