// @generated by xtask regen-bbnf; do not edit by hand.
use bbnf_ir::registry::{StructLayout, StructRegistry};
use crate::runtime::bbnf::value::BbnfValue;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BbnfCompoundKind {
    Rule,
    Term,
    Factor,
    MappedFactor,
    BinaryFactor,
    Concatenation,
    Alternation,
    Closure,
    Rhs,
    Lhs,
    CallArg,
    ImportPath,
    ImportItems,
    ImportDirective,
    RecoverDirective,
    PrettyHint,
    PrettyDirective,
    WsDirective,
    TokenDirective,
    DebugDirective,
    HostDirective,
    Directive,
    GrammarItem,
    Grammar,
    ValueExpr,
    ValueClosure,
    ValueOr,
    ValueAnd,
    ValueCmp,
    ValueAdd,
    ValueMul,
    ValueUnary,
    ValueAtom,
    ValuePath,
    ValueInput,
    ValueFnCall,
    TypeAnnotation,
    Other,
}
impl BbnfCompoundKind {
    pub fn from_layout(layout: &StructLayout) -> Self {
        match StructRegistry::compound_kind_for_layout(layout) {
            "import_path" => Self::ImportPath,
            "import_items" => Self::ImportItems,
            "pretty_hint" => Self::PrettyHint,
            "token_directive" => Self::TokenDirective,
            "debug_directive" => Self::DebugDirective,
            "host_directive" => Self::HostDirective,
            "ws_directive" => Self::WsDirective,
            "import_directive" => Self::ImportDirective,
            "pretty_directive" => Self::PrettyDirective,
            "alternation" => Self::Alternation,
            "call_arg" => Self::CallArg,
            "concatenation" => Self::Concatenation,
            "closure" => Self::Closure,
            "term" => Self::Term,
            "binary_factor" => Self::BinaryFactor,
            "factor" => Self::Factor,
            "mapped_factor" => Self::MappedFactor,
            "rule" => Self::Rule,
            "recover_directive" => Self::RecoverDirective,
            "grammar_item" => Self::GrammarItem,
            "grammar" => Self::Grammar,
            "value_path" => Self::ValuePath,
            "value_input" => Self::ValueInput,
            "type_annotation" => Self::TypeAnnotation,
            "value_mul" => Self::ValueMul,
            "value_or" => Self::ValueOr,
            "value_add" => Self::ValueAdd,
            "value_cmp" => Self::ValueCmp,
            "value_and" => Self::ValueAnd,
            "value_closure" => Self::ValueClosure,
            "value_fn_call" => Self::ValueFnCall,
            "value_atom" => Self::ValueAtom,
            "value_unary" => Self::ValueUnary,
            _ => Self::Other,
        }
    }
}
#[derive(Debug, Clone)]
pub struct BbnfCompound<'p> {
    pub kind: BbnfCompoundKind,
    pub branch_tag: Option<u32>,
    pub bounds: Option<(u32, u32)>,
    pub children: Vec<BbnfValue<'p>>,
}
impl<'p> Default for BbnfCompound<'p> {
    fn default() -> Self {
        Self {
            kind: BbnfCompoundKind::Other,
            branch_tag: None,
            bounds: None,
            children: Vec::new(),
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct BbnfCompoundId(u32);
impl BbnfCompoundId {
    pub const EMPTY: Self = Self(0);
    #[inline]
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }
    #[inline]
    fn slab_index(self) -> Option<usize> {
        if self.0 == 0 { None } else { Some((self.0 - 1) as usize) }
    }
}
#[derive(Debug, Default)]
pub struct BbnfArena<'p> {
    compounds: Vec<BbnfCompound<'p>>,
    empty: BbnfCompound<'p>,
}
impl<'p> BbnfArena<'p> {
    #[inline]
    pub fn new() -> Self {
        Self::default()
    }
    #[inline]
    pub fn with_capacity(compounds: usize) -> Self {
        Self {
            compounds: Vec::with_capacity(compounds),
            empty: BbnfCompound::default(),
        }
    }
    #[inline]
    pub fn push_compound(&mut self, compound: BbnfCompound<'p>) -> BbnfCompoundId {
        self.compounds.push(compound);
        BbnfCompoundId(self.compounds.len() as u32)
    }
    #[inline]
    pub fn compound(&self, id: BbnfCompoundId) -> &BbnfCompound<'p> {
        match id.slab_index() {
            None => &self.empty,
            Some(i) => &self.compounds[i],
        }
    }
    #[inline]
    pub fn compound_count(&self) -> usize {
        self.compounds.len()
    }
    #[inline]
    pub fn truncate(&mut self, compounds: usize) {
        self.compounds.truncate(compounds);
    }
}
