// @generated by xtask regen-bbnf; do not edit by hand.
use super::document::{BbnfDocument, BbnfPathQuery};
use crate::grammar::generated::bbnf::__path_plan;
use crate::grammar::generated::bbnf::{
    __shape_support_BbnfBootstrap, parse_BbnfBootstrap_grammar,
};
use crate::path::cursor::Decision;
use crate::path::executor::PathExecutor;
use crate::path::ir::{PathSegment as TypedSegment, TypedPath};
use crate::path::markers::Bbnf;
use crate::runtime::bbnf::BbnfStructBuilder;
use crate::runtime::path::{Path, PathSegment};
fn lower<'a>(seg: &TypedSegment<'a>) -> Option<PathSegment<'a>> {
    match seg {
        TypedSegment::Field(s) => Some(PathSegment::Field(s)),
        TypedSegment::Index(i) => Some(PathSegment::Index(*i)),
        TypedSegment::VariantName(s) => Some(PathSegment::Field(s)),
        TypedSegment::Wildcard => None,
    }
}
pub fn parse_with<T>(input: &str, path: &TypedPath<Bbnf, T>) -> Option<T>
where
    T: BbnfPathQuery,
{
    PathExecutor::execute(
        input,
        path,
        |rule_id, kind, _idx| {
            __path_plan::lookup(rule_id, kind)
                .map(|e| e.decision)
                .unwrap_or(Decision::ParseFully)
        },
        |src, cursor| {
            let mut state = __shape_support_BbnfBootstrap::ScanState::new();
            let mut builder = BbnfStructBuilder::new();
            let mut pos: usize = 0;
            parse_BbnfBootstrap_grammar(
                    src.as_bytes(),
                    &mut pos,
                    &mut state,
                    &mut builder,
                    cursor,
                )
                .ok()?;
            if path.is_empty() {
                let bytes = src.as_bytes();
                let mut leading = 0usize;
                while let Some(&b) = bytes.get(leading) {
                    if matches!(b, b' ' | b'\t' | b'\n' | b'\r') {
                        leading += 1;
                    } else {
                        break;
                    }
                }
                if pos <= leading && leading < bytes.len() {
                    return None;
                }
            }
            let doc: BbnfDocument<'_> = builder.finalise(src);
            let mut segments: Vec<PathSegment<'_>> = Vec::with_capacity(path.len());
            for owned in path.owned_segments() {
                segments.push(lower(&owned.as_borrowed())?);
            }
            doc.get::<T>(Path::new(&segments))
        },
    )
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::path::ir::TypedPath;
    use crate::runtime::bbnf::value::BbnfValue;
    #[test]
    fn parse_with_resolves_root_value() {
        let path: TypedPath<Bbnf, BbnfValue<'_>> = TypedPath::from_owned(Vec::new());
        let out = parse_with::<BbnfValue<'_>>("a = b ;\n", &path);
        assert!(out.is_some(), "Bbnf root should resolve as identity");
    }
    #[test]
    fn parse_with_returns_none_on_invalid_input() {
        let path: TypedPath<Bbnf, BbnfValue<'_>> = TypedPath::from_owned(Vec::new());
        let out = parse_with::<BbnfValue<'_>>("@@@ not bbnf @@@", &path);
        assert!(out.is_none());
    }
}
