// @generated by xtask regen-bbnf; do not edit by hand.
use crate::runtime::RuntimeView;
use crate::runtime::bbnf::arena::{BbnfCompound, BbnfCompoundKind};
use crate::runtime::bbnf::document::{BbnfDocument, BbnfKind, BbnfView};
use crate::runtime::bbnf::value::BbnfValue;
impl<'a, 'p: 'a> RuntimeView<'p> for BbnfView<'a, 'p> {
    type Kind = BbnfKind;
    #[inline]
    fn kind(&self) -> Self::Kind {
        match self.focus {
            BbnfValue::Int(_) => BbnfKind::Int,
            BbnfValue::Float(_) => BbnfKind::Float,
            BbnfValue::Bool(_) => BbnfKind::Bool,
            BbnfValue::Span(_) => BbnfKind::Span,
            BbnfValue::Tag(_) => BbnfKind::Tag,
            BbnfValue::Unit => BbnfKind::Unit,
            BbnfValue::Compound(_) => BbnfKind::Compound,
        }
    }
    #[inline]
    fn span(&self) -> Option<&'p str> {
        match self.focus {
            BbnfValue::Span(s) => Some(s),
            _ => None,
        }
    }
    #[inline]
    fn input(&self) -> &'p str {
        self.doc.input
    }
    fn children(&self) -> impl Iterator<Item = Self> + '_ {
        let doc = self.doc;
        let focus = self.focus;
        BbnfChildrenIter {
            doc,
            focus,
            index: 0,
        }
    }
}
impl<'a, 'p: 'a> BbnfView<'a, 'p> {
    pub fn byte_span(&self) -> Option<(u32, u32)> {
        compute_byte_span(self.doc, self.focus)
    }
    #[inline]
    pub fn span_text(&self) -> &'p str {
        match self.byte_span() {
            Some((lo, hi)) if hi >= lo => &self.doc.input[lo as usize..hi as usize],
            _ => "",
        }
    }
    #[inline]
    pub fn span_text_opt(&self) -> Option<&'p str> {
        match self.byte_span() {
            Some((lo, hi)) if hi >= lo => Some(&self.doc.input[lo as usize..hi as usize]),
            _ => None,
        }
    }
    #[inline]
    pub fn span_bounds(&self) -> Option<(u32, u32)> {
        self.byte_span()
    }
    pub fn child(&self, i: usize) -> Option<BbnfView<'a, 'p>> {
        match self.focus {
            BbnfValue::Compound(id) => {
                self.doc
                    .compound(id)
                    .children
                    .get(i)
                    .map(|v| BbnfView::focused(self.doc, *v))
            }
            _ => None,
        }
    }
    #[inline]
    pub fn compound_kind(&self) -> Option<BbnfCompoundKind> {
        match self.focus {
            BbnfValue::Compound(id) => Some(self.doc.compound(id).kind),
            _ => None,
        }
    }
    #[inline]
    pub fn branch_tag(&self) -> Option<u32> {
        match self.focus {
            BbnfValue::Compound(id) => self.doc.compound(id).branch_tag,
            _ => None,
        }
    }
    #[inline]
    pub fn is_compound_kind(&self, kind: BbnfCompoundKind) -> bool {
        self.compound_kind() == Some(kind)
    }
    #[inline]
    pub fn compound_identity(&self) -> Option<usize> {
        match self.focus {
            BbnfValue::Compound(id) => Some(self.doc.compound(id) as *const _ as usize),
            _ => None,
        }
    }
    #[inline]
    pub fn compound_entry(&self) -> Option<&'a BbnfCompound<'p>> {
        match self.focus {
            BbnfValue::Compound(id) => Some(self.doc.compound(id)),
            _ => None,
        }
    }
}
fn compute_byte_span<'p>(
    doc: &BbnfDocument<'p>,
    focus: BbnfValue<'p>,
) -> Option<(u32, u32)> {
    match focus {
        BbnfValue::Span(s) => {
            let input_ptr = doc.input.as_ptr() as usize;
            let s_ptr = s.as_ptr() as usize;
            if s_ptr < input_ptr {
                return None;
            }
            let lo = (s_ptr - input_ptr) as u32;
            let hi = lo + s.len() as u32;
            Some((lo, hi))
        }
        BbnfValue::Compound(id) => {
            let entry = doc.compound(id);
            if let Some(bounds) = entry.bounds {
                return Some(bounds);
            }
            let mut lo: Option<u32> = None;
            let mut hi: Option<u32> = None;
            for child in &entry.children {
                if let Some((clo, chi)) = compute_byte_span(doc, *child) {
                    lo = Some(lo.map_or(clo, |existing| existing.min(clo)));
                    hi = Some(hi.map_or(chi, |existing| existing.max(chi)));
                }
            }
            match (lo, hi) {
                (Some(l), Some(h)) => Some((l, h)),
                _ => None,
            }
        }
        _ => None,
    }
}
pub struct BbnfChildrenIter<'a, 'p: 'a> {
    doc: &'a BbnfDocument<'p>,
    focus: BbnfValue<'p>,
    index: usize,
}
impl<'a, 'p: 'a> Iterator for BbnfChildrenIter<'a, 'p> {
    type Item = BbnfView<'a, 'p>;
    fn next(&mut self) -> Option<Self::Item> {
        match self.focus {
            BbnfValue::Compound(id) => {
                let entry = self.doc.compound(id);
                let item = entry.children.get(self.index)?;
                self.index += 1;
                Some(BbnfView::focused(self.doc, *item))
            }
            _ => None,
        }
    }
}
