/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hover_at_offset: (a: number, b: number, c: number) => any;
export const completions: (a: number, b: number) => any;
export const semantic_tokens_full: (a: number, b: number) => any;
export const inlay_hints: (a: number, b: number, c: number, d: number) => any;
export const goto_definition: (a: number, b: number, c: number) => any;
export const document_symbols: (a: number, b: number) => any;
export const folding_ranges: (a: number, b: number) => any;
export const selection_ranges: (a: number, b: number, c: number, d: number) => any;
export const code_actions: (a: number, b: number, c: number, d: number) => any;
export const code_lens: (a: number, b: number) => any;
export const find_references: (a: number, b: number, c: number) => any;
export const prepare_rename: (a: number, b: number, c: number) => any;
export const rename_symbol: (a: number, b: number, c: number, d: number, e: number) => any;
export const format_document: (a: number, b: number) => any;
export const format_range: (a: number, b: number, c: number, d: number) => any;
export const on_type_format: (a: number, b: number, c: number) => any;
export const full_sync: (a: number, b: number) => any;
export const init_panic_hook: () => void;
export const format_json: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const format_css: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const format_bnf: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const format_ebnf: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const format_bbnf: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const compile_grammar: (a: number, b: number, c: number, d: number) => [number, number, number];
export const parse_with_grammar: (a: number, b: number, c: number) => [number, number, number];
export const parse_check: (a: number, b: number, c: number) => [number, number, number];
export const format_with_grammar: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const free_grammar: (a: number) => void;
export const analyze_grammar: (a: number, b: number) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
