// @generated by xtask regen-bnf; do not edit by hand.
use crate::runtime::RuntimeView;
use crate::runtime::bnf::document::{BnfDocument, BnfKind, BnfView};
use crate::runtime::bnf::value::BnfValue;
impl<'a, 'p: 'a> RuntimeView<'p> for BnfView<'a, 'p> {
    type Kind = BnfKind;
    #[inline]
    fn kind(&self) -> Self::Kind {
        match self.focus {
            BnfValue::Span(_) => BnfKind::Span,
            BnfValue::Unit => BnfKind::Unit,
            BnfValue::Compound(_) => BnfKind::Compound,
        }
    }
    #[inline]
    fn span(&self) -> Option<&'p str> {
        match self.focus {
            BnfValue::Span(s) => Some(s),
            _ => None,
        }
    }
    #[inline]
    fn input(&self) -> &'p str {
        self.doc.input
    }
    fn children(&self) -> impl Iterator<Item = Self> + '_ {
        let doc = self.doc;
        let focus = self.focus;
        BnfChildrenIter {
            doc,
            focus,
            index: 0,
        }
    }
}
pub struct BnfChildrenIter<'a, 'p: 'a> {
    doc: &'a BnfDocument<'p>,
    focus: BnfValue<'p>,
    index: usize,
}
impl<'a, 'p: 'a> Iterator for BnfChildrenIter<'a, 'p> {
    type Item = BnfView<'a, 'p>;
    fn next(&mut self) -> Option<Self::Item> {
        match self.focus {
            BnfValue::Compound(id) => {
                let entry = self.doc.compound(id);
                let item = entry.children.get(self.index)?;
                self.index += 1;
                Some(BnfView::focused(self.doc, *item))
            }
            _ => None,
        }
    }
}
