// @generated by skinny bbnf-codegen; do not edit by hand.
use crate::tape::OffsetFlags;

pub(crate) const STRUCTURAL_BYTES: &[u8] = b"{}[],:\"";
pub(crate) const STRING_NEEDS_DECODE: u8 = OffsetFlags::GRAMMAR_BIT0;
pub(crate) const TINY_STRING_CAP: usize = 16;
pub(crate) const DIRECT_TINY_STRING_CAP: usize = 8;
pub(crate) const TRUE_LITERAL: &[u8] = b"true";
pub(crate) const FALSE_LITERAL: &[u8] = b"false";
pub(crate) const NULL_LITERAL: &[u8] = b"null";

#[inline(always)]
pub(crate) fn needs_decode_flags() -> OffsetFlags {
    OffsetFlags::NONE.with(STRING_NEEDS_DECODE)
}

#[inline(always)]
pub(crate) fn string_needs_decode(flags: OffsetFlags) -> bool {
    flags.contains(STRING_NEEDS_DECODE)
}

pub(crate) const W7_DIRECT_BACKEND_SHAPE: &str = "SinkOnly";
pub(crate) const W7_SUBSTRATE_TARGET: &str = "direct_sink";
pub(crate) const W7_RETENTION_LIFETIME: &str = "generated_function";
pub(crate) const W7_POLICY_OWNER: &str = "generated_grammar";
pub(crate) const W7_SAME_SUBSTRATE_UNION: &str = "pass";

#[inline(always)]
pub(crate) fn w7_direct_policy_triad() -> (&'static str, &'static str, &'static str) {
(W7_SUBSTRATE_TARGET, W7_RETENTION_LIFETIME, W7_POLICY_OWNER)
}
