// @generated by skinny bbnf-codegen; do not edit by hand.
use super::parser::ParserState;
use super::value::{JsonNodeKind, ParseError, ParseErrorKind};
use crate::tape::OffsetFlags;
use parse_that_regex::{
    match_json_number_from_first, match_json_string_at_quote_trusted_utf8, skip_json_whitespace,
    JsonNumberMatch, JsonStringMatch, RegexErrorKind,
};

const STRUCTURAL_ALPHABET_JSON: &[u8] = b"{}[],:\"";

// recognizer: SimdScan Exact PreEntry alphabet="{}[],:\""

pub(crate) fn attach_structural_index(state: &mut ParserState<'_>) {
    debug_assert_eq!(STRUCTURAL_ALPHABET_JSON, b"{}[],:\"");
    let _ = state;
}

#[inline(always)]
pub(crate) fn parse_json<'i>(state: &mut ParserState<'i>) -> Result<(), ParseError<'i>> {
    parse_value(state)?;
    skip_ws(state);
    if state.cursor != state.bytes.len() {
        return Err(error(state, ParseErrorKind::TrailingCharacters));
    }
    Ok(())
}

#[inline(always)]
fn parse_value<'i>(state: &mut ParserState<'i>) -> Result<(), ParseError<'i>> {
    skip_ws(state);
    parse_value_at(state)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_value_at<'i>(state: &mut ParserState<'i>) -> Result<(), ParseError<'i>> {
    if state.cursor >= state.bytes.len() {
        return Err(error(state, ParseErrorKind::ExpectedValue));
    }
    let byte = unsafe { *state.bytes.get_unchecked(state.cursor) };
    dispatch_value(state, byte)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn dispatch_value<'i>(state: &mut ParserState<'i>, byte: u8) -> Result<(), ParseError<'i>> {
    match byte {
        b'{' => parse_object(state),
        b'[' => parse_array(state),
        b'"' => parse_string(state),
        b'-' | b'0'..=b'9' => parse_number(state, byte),
        b't' => parse_literal(state, b"true", JsonNodeKind::True),
        b'f' => parse_literal(state, b"false", JsonNodeKind::False),
        b'n' => parse_literal(state, b"null", JsonNodeKind::Null),
        _ => return Err(error(state, ParseErrorKind::ExpectedValue)),
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_object<'i>(state: &mut ParserState<'i>) -> Result<(), ParseError<'i>> {
    if consume_structural(state, b'{').is_none() {
        return Err(error(state, ParseErrorKind::ExpectedValue));
    }
    skip_ws(state);

    if consume(state, b'}') {
        return Ok(());
    }

    loop {
        parse_pair(state)?;
        if consume_container_next(state, b'}', ParseErrorKind::ExpectedCommaOrObjectEnd)? {
            continue;
        }
        return Ok(());
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_pair<'i>(state: &mut ParserState<'i>) -> Result<(), ParseError<'i>> {
    parse_key_colon(state)?;
    parse_value_at(state)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_key_colon<'i>(state: &mut ParserState<'i>) -> Result<(), ParseError<'i>> {
    let start = state.cursor;
    let Some(open_cursor) = consume_quote_at_cursor(state) else {
        return Err(error(state, ParseErrorKind::ExpectedValue));
    };
    if let Some(raw_end) = match_tiny_plain_string(state.bytes, start) {
        state.cursor = raw_end;
    } else {
        let span = match_string_at_quote(state, start)?;
        if span.needs_unescape {
            state.patch_flags(open_cursor, OffsetFlags::NONE.with(OffsetFlags::HAS_ESC));
        }
        state.cursor = span.raw_end;
    }

    let colon = if state.cursor < state.bytes.len()
        && unsafe { *state.bytes.get_unchecked(state.cursor) } == b':'
    {
        state.cursor
    } else {
        skip_json_whitespace(state.bytes, state.cursor)
    };
    if colon >= state.bytes.len() || unsafe { *state.bytes.get_unchecked(colon) } != b':' {
        return Err(error(state, ParseErrorKind::ExpectedColon));
    }
    state.cursor = skip_json_whitespace(state.bytes, colon + 1);
    Ok(())
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_array<'i>(state: &mut ParserState<'i>) -> Result<(), ParseError<'i>> {
    if consume_structural(state, b'[').is_none() {
        return Err(error(state, ParseErrorKind::ExpectedValue));
    }
    skip_ws(state);

    if consume(state, b']') {
        return Ok(());
    }

    loop {
        parse_value_at(state)?;
        if consume_container_next(state, b']', ParseErrorKind::ExpectedCommaOrArrayEnd)? {
            continue;
        }
        return Ok(());
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_string<'i>(state: &mut ParserState<'i>) -> Result<(), ParseError<'i>> {
    let start = state.cursor;
    let Some(open_cursor) = consume_quote_at_cursor(state) else {
        return Err(error(state, ParseErrorKind::ExpectedValue));
    };
    if let Some(raw_end) = match_tiny_plain_string(state.bytes, start) {
        state.cursor = raw_end;
        return Ok(());
    }
    let span = match_string_at_quote(state, start)?;
    if span.needs_unescape {
        state.patch_flags(open_cursor, OffsetFlags::NONE.with(OffsetFlags::HAS_ESC));
    }
    state.cursor = span.raw_end;
    Ok(())
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn match_tiny_plain_string(input: &[u8], offset: usize) -> Option<usize> {
    let mut cursor = offset + 1;
    let limit = (cursor + 8).min(input.len());
    while cursor < limit {
        match input[cursor] {
            b'"' => return Some(cursor + 1),
            b'\\' | 0x00..=0x1f => return None,
            _ => cursor += 1,
        }
    }
    None
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn match_string_at_quote<'i>(
    state: &ParserState<'i>,
    start: usize,
) -> Result<JsonStringMatch, ParseError<'i>> {
    match_json_string_at_quote_trusted_utf8(state.bytes, start).map_err(|err| ParseError {
        input: state.input,
        offset: err.offset,
        kind: match err.kind {
            RegexErrorKind::ExpectedString => ParseErrorKind::ExpectedValue,
            _ => ParseErrorKind::InvalidString,
        },
    })
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_number<'i>(state: &mut ParserState<'i>, first: u8) -> Result<(), ParseError<'i>> {
    let number = match_number_at_digit(state.bytes, state.cursor, first)
        .ok_or_else(|| error(state, ParseErrorKind::InvalidNumber))?;
    state.emit_plain_offset(number.start);
    state.cursor = number.end;
    Ok(())
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn match_number_at_digit(input: &[u8], cursor: usize, first: u8) -> Option<JsonNumberMatch> {
    match_json_number_from_first(input, cursor, first)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_literal<'i>(
    state: &mut ParserState<'i>,
    literal: &'static [u8],
    _kind: JsonNodeKind,
) -> Result<(), ParseError<'i>> {
    let start = state.cursor;
    if state.bytes.get(start..start + literal.len()) != Some(literal) {
        return Err(error(
            state,
            ParseErrorKind::InvalidLiteral(
                std::str::from_utf8(literal).expect("literal is UTF-8"),
            ),
        ));
    }
    state.emit_plain_offset(start);
    state.cursor += literal.len();
    Ok(())
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn skip_ws(state: &mut ParserState<'_>) {
    state.cursor = skip_json_whitespace(state.bytes, state.cursor);
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn consume_delimiter(state: &mut ParserState<'_>, byte: u8) -> bool {
    let offset = if state.cursor < state.bytes.len()
        && unsafe { *state.bytes.get_unchecked(state.cursor) } == byte
    {
        state.cursor
    } else {
        skip_json_whitespace(state.bytes, state.cursor)
    };
    if offset >= state.bytes.len() || unsafe { *state.bytes.get_unchecked(offset) } != byte {
        return false;
    }
    state.cursor = offset + 1;
    true
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn consume_quote_at_cursor(state: &mut ParserState<'_>) -> Option<u32> {
    let offset = state.cursor;
    if offset >= state.bytes.len() || unsafe { *state.bytes.get_unchecked(offset) } != b'"' {
        return None;
    }
    let cursor = state.emit_plain_offset(offset);
    state.cursor = offset + 1;
    Some(cursor)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn consume(state: &mut ParserState<'_>, byte: u8) -> bool {
    if matches!(byte, b':' | b',') {
        return consume_delimiter(state, byte);
    }
    if matches!(byte, b'{' | b'}' | b'[' | b']' | b':' | b',' | b'"') {
        return consume_structural(state, byte).is_some();
    }
    if peek(state) == Some(byte) {
        state.cursor += 1;
        true
    } else {
        false
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn consume_structural(state: &mut ParserState<'_>, byte: u8) -> Option<u32> {
    let offset = if state.cursor < state.bytes.len()
        && unsafe { *state.bytes.get_unchecked(state.cursor) } == byte
    {
        state.cursor
    } else {
        skip_json_whitespace(state.bytes, state.cursor)
    };
    if offset >= state.bytes.len() || unsafe { *state.bytes.get_unchecked(offset) } != byte {
        return None;
    }
    let cursor = state.emit_plain_offset(offset);
    state.cursor = offset + 1;
    Some(cursor)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn consume_container_next<'i>(
    state: &mut ParserState<'i>,
    close: u8,
    error_kind: ParseErrorKind,
) -> Result<bool, ParseError<'i>> {
    let current = if state.cursor < state.bytes.len() {
        Some(unsafe { *state.bytes.get_unchecked(state.cursor) })
    } else {
        None
    };
    let offset = if current == Some(b',') || current == Some(close) {
        state.cursor
    } else {
        skip_json_whitespace(state.bytes, state.cursor)
    };
    if offset >= state.bytes.len() {
        return Err(error(state, error_kind));
    }
    let byte = unsafe { *state.bytes.get_unchecked(offset) };
    if byte == b',' {
        state.cursor = skip_json_whitespace(state.bytes, offset + 1);
        return Ok(true);
    }
    if byte == close {
        state.emit_plain_offset(offset);
        state.cursor = offset + 1;
        return Ok(false);
    }
    Err(error(state, error_kind))
}

#[inline(always)]
fn peek(state: &ParserState<'_>) -> Option<u8> {
    state.bytes.get(state.cursor).copied()
}

#[cold]
#[inline(never)]
fn error<'i>(state: &ParserState<'i>, kind: ParseErrorKind) -> ParseError<'i> {
    ParseError {
        input: state.input,
        offset: state.cursor,
        kind,
    }
}

// sink-only lowered from BackendIr: entry=json direct_shapes=JsonArray,JsonBool,JsonNull,JsonNumber,JsonObject,JsonPair,JsonString dispatch_alt_count=8

use super::sink::JsonSink;
use parse_that_regex::number::{
    materialize_f64, materialize_i64, materialize_u64, match_number_span_from_first, NumberSpan,
};

struct ParsedString<'i> {
    raw: &'i str,
    needs_unescape: bool,
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
pub fn parse_direct<'i, S: JsonSink>(input: &'i str, sink: &mut S) -> Result<(), ParseError<'i>> {
    let bytes = input.as_bytes();
    let mut cursor = 0;
    parse_value_direct(input, bytes, &mut cursor, sink)?;
    cursor = skip_json_whitespace(bytes, cursor);
    if cursor == bytes.len() {
        Ok(())
    } else {
        Err(direct_error(
            input,
            cursor,
            ParseErrorKind::TrailingCharacters,
        ))
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_value_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    sink: &mut S,
) -> Result<(), ParseError<'i>> {
    *cursor = skip_json_whitespace(bytes, *cursor);
    let Some(byte) = bytes.get(*cursor).copied() else {
        return Err(direct_error(input, *cursor, ParseErrorKind::ExpectedValue));
    };
    match byte {
        b'{' => parse_object_direct(input, bytes, cursor, sink),
        b'[' => parse_array_direct(input, bytes, cursor, sink),
        b'"' => {
            let value = parse_string_direct(input, bytes, cursor)?;
            sink.string_source(value.raw, value.needs_unescape)
                .map_err(|err| string_error(input, err))?;
            Ok(())
        }
        b'-' | b'0'..=b'9' => parse_number_direct(input, bytes, cursor, sink, byte),
        b't' => {
            consume_literal_direct(input, bytes, cursor, b"true")?;
            sink.bool(true);
            Ok(())
        }
        b'f' => {
            consume_literal_direct(input, bytes, cursor, b"false")?;
            sink.bool(false);
            Ok(())
        }
        b'n' => {
            consume_literal_direct(input, bytes, cursor, b"null")?;
            sink.null();
            Ok(())
        }
        _ => Err(direct_error(input, *cursor, ParseErrorKind::ExpectedValue)),
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_object_value_at_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    sink: &mut S,
) -> Result<(), ParseError<'i>> {
    let Some(byte) = bytes.get(*cursor).copied() else {
        return Err(direct_error(input, *cursor, ParseErrorKind::ExpectedValue));
    };
    match byte {
        b'{' => parse_object_direct(input, bytes, cursor, sink),
        b'[' => parse_array_direct(input, bytes, cursor, sink),
        b'"' => {
            let value = parse_string_direct(input, bytes, cursor)?;
            sink.object_string_source(value.raw, value.needs_unescape)
                .map_err(|err| string_error(input, err))?;
            Ok(())
        }
        b'-' | b'0'..=b'9' => parse_number_object_direct(input, bytes, cursor, sink, byte),
        b't' => {
            consume_literal_direct(input, bytes, cursor, b"true")?;
            sink.object_bool(true);
            Ok(())
        }
        b'f' => {
            consume_literal_direct(input, bytes, cursor, b"false")?;
            sink.object_bool(false);
            Ok(())
        }
        b'n' => {
            consume_literal_direct(input, bytes, cursor, b"null")?;
            sink.object_null();
            Ok(())
        }
        _ => Err(direct_error(input, *cursor, ParseErrorKind::ExpectedValue)),
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_array_element_at_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    sink: &mut S,
) -> Result<(), ParseError<'i>> {
    let Some(byte) = bytes.get(*cursor).copied() else {
        return Err(direct_error(input, *cursor, ParseErrorKind::ExpectedValue));
    };
    match byte {
        b'{' => parse_object_direct(input, bytes, cursor, sink),
        b'[' => parse_array_direct(input, bytes, cursor, sink),
        b'"' => {
            let value = parse_string_direct(input, bytes, cursor)?;
            sink.array_string_source(value.raw, value.needs_unescape)
                .map_err(|err| string_error(input, err))?;
            Ok(())
        }
        b'-' | b'0'..=b'9' => parse_number_array_direct(input, bytes, cursor, sink, byte),
        b't' => {
            consume_literal_direct(input, bytes, cursor, b"true")?;
            sink.array_bool(true);
            Ok(())
        }
        b'f' => {
            consume_literal_direct(input, bytes, cursor, b"false")?;
            sink.array_bool(false);
            Ok(())
        }
        b'n' => {
            consume_literal_direct(input, bytes, cursor, b"null")?;
            sink.array_null();
            Ok(())
        }
        _ => Err(direct_error(input, *cursor, ParseErrorKind::ExpectedValue)),
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_object_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    sink: &mut S,
) -> Result<(), ParseError<'i>> {
    consume_direct(input, bytes, cursor, b'{', ParseErrorKind::ExpectedValue)?;
    sink.begin_object();
    *cursor = skip_json_whitespace(bytes, *cursor);
    if take_direct(bytes, cursor, b'}') {
        sink.end_object();
        return Ok(());
    }
    loop {
        let key = parse_string_direct(input, bytes, cursor)?;
        sink.key_source(key.raw, key.needs_unescape)
            .map_err(|err| string_error(input, err))?;
        *cursor = skip_json_whitespace(bytes, *cursor);
        consume_direct(input, bytes, cursor, b':', ParseErrorKind::ExpectedColon)?;
        *cursor = skip_json_whitespace(bytes, *cursor);
        parse_object_value_at_direct(input, bytes, cursor, sink)?;
        *cursor = skip_json_whitespace(bytes, *cursor);
        if take_direct(bytes, cursor, b',') {
            *cursor = skip_json_whitespace(bytes, *cursor);
            continue;
        }
        consume_direct(input, bytes, cursor, b'}', ParseErrorKind::ExpectedCommaOrObjectEnd)?;
        sink.end_object();
        return Ok(());
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_array_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    sink: &mut S,
) -> Result<(), ParseError<'i>> {
    consume_direct(input, bytes, cursor, b'[', ParseErrorKind::ExpectedValue)?;
    sink.begin_array();
    *cursor = skip_json_whitespace(bytes, *cursor);
    if take_direct(bytes, cursor, b']') {
        sink.end_array();
        return Ok(());
    }
    loop {
        parse_array_element_at_direct(input, bytes, cursor, sink)?;
        *cursor = skip_json_whitespace(bytes, *cursor);
        if take_direct(bytes, cursor, b',') {
            *cursor = skip_json_whitespace(bytes, *cursor);
            continue;
        }
        consume_direct(input, bytes, cursor, b']', ParseErrorKind::ExpectedCommaOrArrayEnd)?;
        sink.end_array();
        return Ok(());
    }
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_string_direct<'i>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
) -> Result<ParsedString<'i>, ParseError<'i>> {
    let span =
        parse_that_regex::match_json_string_at_quote_trusted_utf8(bytes, *cursor).map_err(|err| {
            ParseError {
                input,
                offset: err.offset,
                kind: match err.kind {
                    RegexErrorKind::ExpectedString => ParseErrorKind::ExpectedValue,
                    _ => ParseErrorKind::InvalidString,
                },
            }
        })?;
    let raw = unsafe { std::str::from_utf8_unchecked(&bytes[span.content_start..span.content_end]) };
    *cursor = span.raw_end;
    Ok(ParsedString {
        raw,
        needs_unescape: span.needs_unescape,
    })
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_number_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    sink: &mut S,
    first: u8,
) -> Result<(), ParseError<'i>> {
    let span = match_number_span_from_first(bytes, *cursor, first)
        .ok_or_else(|| direct_error(input, *cursor, ParseErrorKind::InvalidNumber))?;
    *cursor = span.end;
    emit_number_direct(input, bytes, &span, sink)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_number_object_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    sink: &mut S,
    first: u8,
) -> Result<(), ParseError<'i>> {
    let span = match_number_span_from_first(bytes, *cursor, first)
        .ok_or_else(|| direct_error(input, *cursor, ParseErrorKind::InvalidNumber))?;
    *cursor = span.end;
    emit_number_object_direct(input, bytes, &span, sink)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn parse_number_array_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    sink: &mut S,
    first: u8,
) -> Result<(), ParseError<'i>> {
    let span = match_number_span_from_first(bytes, *cursor, first)
        .ok_or_else(|| direct_error(input, *cursor, ParseErrorKind::InvalidNumber))?;
    *cursor = span.end;
    emit_number_array_direct(input, bytes, &span, sink)
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn emit_number_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    span: &NumberSpan,
    sink: &mut S,
) -> Result<(), ParseError<'i>> {
    let raw = &bytes[span.start..span.end];
    if span.is_integer {
        if span.negative {
            if raw == b"-0" {
                sink.f64(-0.0);
                return Ok(());
            }
            if let Ok(value) = materialize_i64(bytes, span) {
                sink.i64(value);
                return Ok(());
            }
        } else if let Ok(value) = materialize_u64(bytes, span) {
            sink.u64(value);
            return Ok(());
        }
    }
    let value = materialize_f64(bytes, span)
        .map_err(|_| direct_error(input, span.start, ParseErrorKind::InvalidNumber))?;
    sink.f64(value);
    Ok(())
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn emit_number_object_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    span: &NumberSpan,
    sink: &mut S,
) -> Result<(), ParseError<'i>> {
    let raw = &bytes[span.start..span.end];
    if span.is_integer {
        if span.negative {
            if raw == b"-0" {
                sink.object_f64(-0.0);
                return Ok(());
            }
            if let Ok(value) = materialize_i64(bytes, span) {
                sink.object_i64(value);
                return Ok(());
            }
        } else if let Ok(value) = materialize_u64(bytes, span) {
            sink.object_u64(value);
            return Ok(());
        }
    }
    let value = materialize_f64(bytes, span)
        .map_err(|_| direct_error(input, span.start, ParseErrorKind::InvalidNumber))?;
    sink.object_f64(value);
    Ok(())
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn emit_number_array_direct<'i, S: JsonSink>(
    input: &'i str,
    bytes: &'i [u8],
    span: &NumberSpan,
    sink: &mut S,
) -> Result<(), ParseError<'i>> {
    let raw = &bytes[span.start..span.end];
    if span.is_integer {
        if span.negative {
            if raw == b"-0" {
                sink.array_f64(-0.0);
                return Ok(());
            }
            if let Ok(value) = materialize_i64(bytes, span) {
                sink.array_i64(value);
                return Ok(());
            }
        } else if let Ok(value) = materialize_u64(bytes, span) {
            sink.array_u64(value);
            return Ok(());
        }
    }
    let value = materialize_f64(bytes, span)
        .map_err(|_| direct_error(input, span.start, ParseErrorKind::InvalidNumber))?;
    sink.array_f64(value);
    Ok(())
}

#[cfg_attr(feature = "parse-attribution", inline(never))]
#[cfg_attr(not(feature = "parse-attribution"), inline(always))]
fn consume_literal_direct<'i>(
    input: &'i str,
    bytes: &'i [u8],
    cursor: &mut usize,
    literal: &'static [u8],
) -> Result<(), ParseError<'i>> {
    let start = *cursor;
    if bytes.get(start..start + literal.len()) != Some(literal) {
        return Err(direct_error(
            input,
            start,
            ParseErrorKind::InvalidLiteral(
                std::str::from_utf8(literal).expect("literal is UTF-8"),
            ),
        ));
    }
    *cursor += literal.len();
    Ok(())
}

fn consume_direct<'i>(
    input: &'i str,
    bytes: &[u8],
    cursor: &mut usize,
    byte: u8,
    kind: ParseErrorKind,
) -> Result<(), ParseError<'i>> {
    if take_direct(bytes, cursor, byte) {
        Ok(())
    } else {
        Err(direct_error(input, *cursor, kind))
    }
}

fn take_direct(bytes: &[u8], cursor: &mut usize, byte: u8) -> bool {
    if bytes.get(*cursor) == Some(&byte) {
        *cursor += 1;
        true
    } else {
        false
    }
}

fn direct_error<'i>(input: &'i str, offset: usize, kind: ParseErrorKind) -> ParseError<'i> {
    ParseError {
        input,
        offset,
        kind,
    }
}

fn string_error<'i>(input: &'i str, err: parse_that_regex::RegexError) -> ParseError<'i> {
    ParseError {
        input,
        offset: err.offset,
        kind: ParseErrorKind::InvalidString,
    }
}
