// @generated by skinny bbnf-codegen; do not edit by hand.
use super::generated;
use super::value::{ParseError, ParseErrorKind};
use super::view::JsonRoot;
use crate::tape::{CapacityPlan, OffsetFlags, TapeBuilder};

pub(crate) struct ParserState<'i> {
    pub input: &'i str,
    pub bytes: &'i [u8],
    pub cursor: usize,
    pub tape: TapeBuilder<'i>,
}

impl<'i> ParserState<'i> {
    #[inline(always)]
    pub fn new(input: &'i str) -> Self {
        let plan = CapacityPlan::from_env();
        let capacity = super::scan::structural_capacity_for(plan, input.as_bytes());
        Self {
            input,
            bytes: input.as_bytes(),
            cursor: 0,
            tape: TapeBuilder::new(input.as_bytes(), capacity),
        }
    }

    #[inline(always)]
    pub fn finish(self) -> JsonRoot<'i> {
        let tape = self.tape.finish();
        JsonRoot::from_tape(self.input, tape)
    }

    #[cfg_attr(feature = "parse-attribution", inline(never))]
    #[cfg_attr(not(feature = "parse-attribution"), inline(always))]
    pub fn emit_plain_offset(&mut self, offset: usize) -> u32 {
        self.tape.push_plain_offset(offset)
    }

    #[cfg_attr(feature = "parse-attribution", inline(never))]
    #[cfg_attr(not(feature = "parse-attribution"), inline(always))]
    pub fn patch_flags(&mut self, cursor: u32, flags: OffsetFlags) {
        self.tape.patch_flags(cursor, flags);
    }
}

#[inline(always)]
pub fn parse<'i>(input: &'i str) -> Result<JsonRoot<'i>, ParseError<'i>> {
    let mut state = ParserState::new(input);
    generated::attach_structural_index(&mut state);
    generated::parse_json(&mut state)?;
    Ok(state.finish())
}

#[inline]
pub fn parse_bytes(input: &[u8]) -> Result<JsonRoot<'_>, ParseError<'_>> {
    match std::str::from_utf8(input) {
        Ok(input) => parse(input),
        Err(error) => {
            let offset = error.valid_up_to();
            Err(ParseError {
                input: "",
                offset,
                kind: ParseErrorKind::InvalidUtf8,
            })
        }
    }
}

pub const RECOGNIZER_COUNT: usize = 1;

#[inline(always)]
pub fn parse_only<'i>(input: &'i str) -> Result<(), ParseError<'i>> {
    generated::parse_only(input)
}

#[inline]
pub fn parse_only_bytes(input: &[u8]) -> Result<(), ParseError<'_>> {
    match std::str::from_utf8(input) {
        Ok(input) => parse_only(input),
        Err(error) => {
            let offset = error.valid_up_to();
            Err(ParseError {
                input: "",
                offset,
                kind: ParseErrorKind::InvalidUtf8,
            })
        }
    }
}
