// @generated by skinny bbnf-codegen; do not edit by hand.
use super::generated;
use super::value::ParseError;
use super::view::JsonRoot;
use crate::tape::TapeBuilder;

pub(crate) struct ParserState<'i> {
    pub input: &'i str,
    pub bytes: &'i [u8],
    pub cursor: usize,
    pub structural_offsets: Vec<u32>,
    pub structural_cursor: usize,
    pub string_escape_offsets: Vec<u32>,
    pub string_escape_cursor: usize,
    pub string_control_offsets: Vec<u32>,
    pub string_control_cursor: usize,
    pub tape: TapeBuilder<'i>,
}

impl<'i> ParserState<'i> {
    pub fn new(input: &'i str) -> Self {
        Self {
            input,
            bytes: input.as_bytes(),
            cursor: 0,
            structural_offsets: Vec::new(),
            structural_cursor: 0,
            string_escape_offsets: Vec::new(),
            string_escape_cursor: 0,
            string_control_offsets: Vec::new(),
            string_control_cursor: 0,
            tape: TapeBuilder::new(input.as_bytes()),
        }
    }

    pub fn finish(self) -> JsonRoot<'i> {
        JsonRoot::from_tape(self.input, self.tape.finish())
    }
}

pub fn parse<'i>(input: &'i str) -> Result<JsonRoot<'i>, ParseError<'i>> {
    let mut state = ParserState::new(input);
    generated::attach_structural_index(&mut state);
    generated::parse_json(&mut state)?;
    Ok(state.finish())
}

pub const RECOGNIZER_COUNT: usize = 1;

