// @generated by skinny bbnf-codegen; do not edit by hand.
use std::borrow::Cow;

use parse_that_regex::unescape_json_string;

use crate::tape::{DocumentView, Tape, TapeId, TokenFlags, ValueRef};

use super::value::{value_from_ref, JsonNodeKind, JsonToken, JsonValue};
use super::visitor::{walk_value, JsonVisitor};

pub struct JsonRoot<'input> {
    document: JsonDocument<'input>,
}

impl<'input> JsonRoot<'input> {
    pub fn from_tape(input: &'input str, tape: Tape<'input>) -> Self {
        Self {
            document: JsonDocument {
                tape,
                source_str: input,
            },
        }
    }

    pub fn value(&self) -> JsonValue<'_, 'input> {
        let root = ValueRef::<RootKind>::new(&self.document.tape, 0);
        let value_index = root.index() + 1;
        value_from_ref(ValueRef::new(&self.document.tape, value_index))
    }

    pub fn document(&self) -> &JsonDocument<'input> {
        &self.document
    }

    pub fn tape(&self) -> &Tape<'input> {
        &self.document.tape
    }

    pub fn source(&self) -> &'input str {
        self.document.source_str
    }

    pub fn token_stream(&self) -> impl Iterator<Item = JsonToken> + '_ {
        self.document.tape.tokens().iter().map(|token| JsonToken {
            kind: JsonNodeKind::from_id(token.kind).expect("parser emits only JSON node kinds"),
            flags: token.flags,
            start: token.start,
            end: token.end,
            payload_or_skip: token.payload_or_skip,
        })
    }

    pub fn tokens(&self) -> &[crate::tape::TapeToken] {
        self.document.tape.tokens()
    }

    pub fn to_canonical_string(&self) -> String {
        self.value().to_canonical_string()
    }

    pub fn visit<V>(&self, visitor: &mut V)
    where
        V: JsonVisitor,
    {
        walk_value(&self.value(), visitor);
    }
}

pub struct JsonDocument<'input> {
    tape: Tape<'input>,
    source_str: &'input str,
}

impl<'input> DocumentView<'input> for JsonDocument<'input> {
    type Root = ValueRef<'input, 'input, RootKind>;

    fn root_value(&'input self) -> Self::Root {
        ValueRef::new(&self.tape, 0)
    }

    fn tape_id(&self) -> TapeId {
        self.tape.id()
    }

    fn source(&'input self) -> &'input [u8] {
        self.tape.source()
    }
}

#[derive(Copy, Clone)]
pub struct JsonObject<'doc, 'input: 'doc> {
    pub(crate) inner: ValueRef<'doc, 'input, ObjectKind>,
}

impl<'doc, 'input: 'doc> JsonObject<'doc, 'input> {
    pub fn pairs(&self) -> JsonObjectPairs<'doc, 'input> {
        let end = self.inner.index() + self.inner.token().payload_or_skip;
        JsonObjectPairs {
            tape: self.inner.tape(),
            cursor: self.inner.index() + 1,
            end,
        }
    }

    pub fn len(&self) -> usize {
        self.pairs().count()
    }

    pub fn is_empty(&self) -> bool {
        self.pairs().next().is_none()
    }

    pub fn get(&self, key: &str) -> Option<JsonValue<'doc, 'input>> {
        self.pairs().find_map(|pair| {
            if pair.key().as_str().as_ref() == key {
                Some(pair.value())
            } else {
                None
            }
        })
    }

    pub fn to_canonical_string(&self) -> String {
        let mut output = String::from("{");
        let mut pairs: Vec<_> = self.pairs().collect();
        pairs.sort_by(|left, right| {
            left.key()
                .as_str()
                .as_ref()
                .cmp(right.key().as_str().as_ref())
        });
        for (index, pair) in pairs.into_iter().enumerate() {
            if index > 0 {
                output.push(',');
            }
            output.push_str(
                &serde_json::to_string(pair.key().as_str().as_ref())
                    .expect("JSON string serialization cannot fail"),
            );
            output.push(':');
            output.push_str(&pair.value().to_canonical_string());
        }
        output.push('}');
        output
    }
}

#[derive(Copy, Clone)]
pub struct JsonArray<'doc, 'input: 'doc> {
    pub(crate) inner: ValueRef<'doc, 'input, ArrayKind>,
}

impl<'doc, 'input: 'doc> JsonArray<'doc, 'input> {
    pub fn values(&self) -> JsonArrayValues<'doc, 'input> {
        let end = self.inner.index() + self.inner.token().payload_or_skip;
        JsonArrayValues {
            tape: self.inner.tape(),
            cursor: self.inner.index() + 1,
            end,
        }
    }

    pub fn len(&self) -> usize {
        self.values().count()
    }

    pub fn is_empty(&self) -> bool {
        self.values().next().is_none()
    }

    pub fn to_canonical_string(&self) -> String {
        let mut output = String::from("[");
        for (index, value) in self.values().enumerate() {
            if index > 0 {
                output.push(',');
            }
            output.push_str(&value.to_canonical_string());
        }
        output.push(']');
        output
    }
}

#[derive(Copy, Clone)]
pub struct JsonPair<'doc, 'input: 'doc> {
    pub(crate) inner: ValueRef<'doc, 'input, PairKind>,
}

impl<'doc, 'input: 'doc> JsonPair<'doc, 'input> {
    pub fn key(&self) -> JsonString<'doc, 'input> {
        JsonString {
            inner: ValueRef::new(self.inner.tape(), self.inner.index() + 1),
        }
    }

    pub fn value(&self) -> JsonValue<'doc, 'input> {
        value_from_ref(ValueRef::new(self.inner.tape(), self.inner.index() + 2))
    }
}

#[derive(Copy, Clone)]
pub struct JsonString<'doc, 'input: 'doc> {
    pub(crate) inner: ValueRef<'doc, 'input, StringKind>,
}

impl<'doc, 'input: 'doc> JsonString<'doc, 'input> {
    pub fn raw(&self) -> &'input str {
        let token = self.inner.token();
        std::str::from_utf8(&self.inner.tape().source()[token.start as usize..token.end as usize])
            .expect("parser input is UTF-8")
    }

    pub fn as_str(&self) -> Cow<'input, str> {
        if self
            .inner
            .token()
            .flags
            .contains(TokenFlags::STRING_NEEDS_UNESCAPE)
        {
            unescape_json_string(self.raw()).expect("parser validated JSON string escapes")
        } else {
            Cow::Borrowed(self.raw())
        }
    }
}

#[derive(Copy, Clone)]
pub struct JsonNumber<'doc, 'input: 'doc> {
    pub(crate) inner: ValueRef<'doc, 'input, NumberKind>,
}

impl<'doc, 'input: 'doc> JsonNumber<'doc, 'input> {
    pub fn raw(&self) -> &'input str {
        let token = self.inner.token();
        std::str::from_utf8(&self.inner.tape().source()[token.start as usize..token.end as usize])
            .expect("parser input is UTF-8")
    }

    pub fn as_f64(&self) -> Result<f64, std::num::ParseFloatError> {
        self.raw().parse()
    }

    pub fn as_i64(&self) -> Result<i64, std::num::ParseIntError> {
        self.raw().parse()
    }
}

#[derive(Copy, Clone)]
pub struct JsonBool<'doc, 'input: 'doc> {
    pub(crate) inner: ValueRef<'doc, 'input, BoolKind>,
    pub(crate) value: bool,
}

impl JsonBool<'_, '_> {
    pub fn value(&self) -> bool {
        self.value
    }
}

#[derive(Copy, Clone)]
pub struct JsonNull<'doc, 'input: 'doc> {
    pub(crate) inner: ValueRef<'doc, 'input, NullKind>,
}

pub struct JsonObjectPairs<'doc, 'input: 'doc> {
    tape: &'doc Tape<'input>,
    cursor: u32,
    end: u32,
}

impl<'doc, 'input: 'doc> Iterator for JsonObjectPairs<'doc, 'input> {
    type Item = JsonPair<'doc, 'input>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.cursor >= self.end {
            return None;
        }
        let index = self.cursor;
        let token = self.tape.token(index);
        self.cursor += token.payload_or_skip;
        Some(JsonPair {
            inner: ValueRef::new(self.tape, index),
        })
    }
}

pub struct JsonArrayValues<'doc, 'input: 'doc> {
    tape: &'doc Tape<'input>,
    cursor: u32,
    end: u32,
}

impl<'doc, 'input: 'doc> Iterator for JsonArrayValues<'doc, 'input> {
    type Item = JsonValue<'doc, 'input>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.cursor >= self.end {
            return None;
        }
        let index = self.cursor;
        let token = self.tape.token(index);
        self.cursor += token.subtree_skip() as u32;
        Some(value_from_ref(ValueRef::new(self.tape, index)))
    }
}

pub enum RootKind {}
pub enum ObjectKind {}
pub enum ArrayKind {}
pub enum PairKind {}
pub enum StringKind {}
pub enum NumberKind {}
pub enum BoolKind {}
pub enum NullKind {}
