// @generated by skinny bbnf-codegen; do not edit by hand.
pub(crate) const ROW_ID: &str = "css_l4/vendor_and_custom_atrules/direct_to_struct/main";
pub(crate) const REQUEST_PROFILE: &str = "css_l4_vendor_and_custom_atrules";
pub(crate) const ENTRY_RULE: &str = "stylesheet";
pub(crate) const FRONTEND_SOURCE_HASH: &str = "1ab6ec80688a4b19";
pub(crate) const REQUEST_SOURCE_COUNT: usize = 15;
pub(crate) const IMPORT_COUNT: usize = 24;
pub(crate) const LAYOUT_DIRECTIVE_COUNT: usize = 1;
pub(crate) const DISCARD_OPERATOR_COUNT: usize = 107;
