// @generated by skinny bbnf-codegen; do not edit by hand.
pub(crate) const FACT_SCHEMA: &str = "css-l4-vendor-custom-facts-v1";
pub(crate) const ROW_ID: &str = "css_l4/vendor_and_custom_atrules/direct_to_struct/main";
pub(crate) const OUTPUT_PLANE: &str = "css_l4_vendor_custom_fact_stream";
