use crate::grammar_profile::{GrammarProfile, RuntimeProvider};
use std::collections::BTreeMap;

static RUNTIME_PROFILE: GrammarProfile = GrammarProfile::new(
    "css_l4_declaration_values",
    &["config.rs", "generated.rs", "mod.rs", "parser.rs"],
    RuntimeProvider::CssL4DeclarationValues,
);

pub(crate) fn runtime_profile() -> &'static GrammarProfile {
    &RUNTIME_PROFILE
}

pub(crate) fn emit_runtime_files() -> BTreeMap<String, String> {
    BTreeMap::from([
        (
            "config.rs".into(),
            render(include_str!(
                "css_l4_declaration_values_templates/config.rs"
            )),
        ),
        (
            "generated.rs".into(),
            render(include_str!(
                "css_l4_declaration_values_templates/generated.rs"
            )),
        ),
        (
            "mod.rs".into(),
            render(include_str!("css_l4_declaration_values_templates/mod.rs")),
        ),
        (
            "parser.rs".into(),
            render(include_str!(
                "css_l4_declaration_values_templates/parser.rs"
            )),
        ),
    ])
}

fn render(source: &str) -> String {
    let mut out = String::from("// @generated by skinny bbnf-codegen; do not edit by hand.\n");
    out.push_str(source.trim_matches('\n'));
    out.push('\n');
    out
}
