use std::collections::BTreeMap;

use crate::direct_schema::{
    DirectFieldSchema, DirectIgnoredFieldSchema, DirectScalar, DirectSkipKind, DirectTypeKind,
    DirectTypeRef, DuplicatePolicy, PresencePolicy, UnknownFieldPolicy,
};
use crate::lower::schema_direct::TypedDirectProgram;

pub fn render(program: &TypedDirectProgram) -> Result<String, String> {
    let schema = &program.schema;
    let renderer = Renderer::new(program)?;
    let mut out = String::new();
    out.push_str("// @generated by skinny bbnf-codegen; do not edit by hand.\n");
    out.push_str("// typed DirectBuild consumer-crate module\n");
    out.push_str(&format!("// schema_hash: {}\n", schema.schema_hash));
    out.push_str(&format!(
        "// direct_shapes: {}\n\n",
        program.direct_shape_roster.join(",")
    ));
    out.push_str(
        r#"use std::borrow::Cow;
#[allow(unused_imports)]
use std::collections::BTreeMap;

use parse_that_regex::{
    match_string_at_quote_trusted_utf8,
    number::{match_number_span_from_first, materialize_f64, materialize_i64, materialize_u64},
    skip_ascii_whitespace, unescape_string,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DirectBuildError<'i> {
    pub input: &'i str,
    pub offset: usize,
    pub message: &'static str,
}

impl std::fmt::Display for DirectBuildError<'_> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "{} at byte {}", self.message, self.offset)
    }
}

impl std::error::Error for DirectBuildError<'_> {}

"#,
    );

    for root in &schema.roots {
        let fn_name = &root.function_name;
        let type_name = &root.rust_type;
        let parser_expr = renderer.parse_expr_with_parser(&root.ty, "&mut parser")?;
        out.push_str(&format!(
            r#"pub fn {fn_name}<'i>(input: &'i str) -> Result<{type_name}, DirectBuildError<'i>> {{
    let mut parser = DirectParser::new(input);
    let output = {parser_expr}?;
    parser.ws();
    if parser.cursor == parser.bytes.len() {{
        Ok(output)
    }} else {{
        Err(parser.error("trailing characters"))
    }}
}}

"#
        ));
    }

    for ty in &schema.types {
        let type_id = &ty.type_id;
        let type_name = &ty.rust_type;
        let fn_name = renderer.type_fn(type_id)?;
        match &ty.kind {
            DirectTypeKind::Struct {
                fields,
                ignored_fields,
                unknown_fields,
            } => {
                let generic_fn_name = if type_id == "Plugin" {
                    let generic = format!("{fn_name}_generic");
                    renderer.render_plugin_wrapper(&mut out, &fn_name, &generic, type_name)?;
                    generic
                } else {
                    fn_name.clone()
                };
                out.push_str(&format!(
                    "fn {generic_fn_name}<'i>(parser: &mut DirectParser<'i>) -> Result<{type_name}, DirectBuildError<'i>> {{\n"
                ));
                out.push_str("    parser.ws();\n    parser.expect(b'{')?;\n");
                for field in fields {
                    out.push_str(&format!(
                        "    let mut {}: Option<{}> = None;\n",
                        field.rust_field,
                        renderer.rust_type(&field.ty)?
                    ));
                }
                if let UnknownFieldPolicy::CaptureStringEntries {
                    rust_field,
                    entry_rust_type,
                    capacity_hint,
                    ..
                } = unknown_fields
                {
                    let capacity = capacity_hint.unwrap_or(0);
                    out.push_str(&format!(
                        "    let mut {rust_field}: Vec<{entry_rust_type}> = Vec::with_capacity({capacity});\n"
                    ));
                }
                out.push_str("    parser.ws();\n    if parser.take(b'}') {\n        return Ok(");
                renderer.render_construct(&mut out, type_name, fields, unknown_fields)?;
                out.push_str(");\n    }\n    loop {\n");
                out.push_str(
                    "        let key = parser.parse_string()?;\n        parser.ws();\n        parser.expect(b':')?;\n        parser.ws();\n        match key.as_ref() {\n",
                );
                for field in fields {
                    renderer.render_field_arm(&mut out, field)?;
                }
                for field in ignored_fields {
                    renderer.render_ignored_field_arm(&mut out, field)?;
                }
                match unknown_fields {
                    UnknownFieldPolicy::Skip => {
                        out.push_str("            _ => parser.skip_value()?,\n");
                    }
                    UnknownFieldPolicy::Reject => {
                        out.push_str(
                            "            _ => return Err(parser.error(\"unexpected field\")),\n",
                        );
                    }
                    UnknownFieldPolicy::CaptureStringEntries {
                        rust_field,
                        entry_rust_type,
                        key_field,
                        value_field,
                        ..
                    } => {
                        let entry_construct = construct_path(entry_rust_type);
                        out.push_str(&format!(
                            "            _ => {{\n                let value = parser.parse_string()?;\n                {rust_field}.push({entry_construct} {{ {key_field}: key, {value_field}: value }});\n            }}\n"
                        ));
                    }
                }
                out.push_str(
                    "        }\n        parser.ws();\n        if parser.take(b',') {\n            parser.ws();\n            continue;\n        }\n        parser.expect(b'}')?;\n        return Ok(",
                );
                renderer.render_construct(&mut out, type_name, fields, unknown_fields)?;
                out.push_str(");\n    }\n}\n\n");
                if type_id == "Plugin" {
                    renderer.render_plugin_ordered(&mut out, type_name)?;
                }
            }
        }
    }

    for (name, ty) in renderer.helpers.clone() {
        renderer.render_helper(&mut out, &name, &ty)?;
    }
    out.push_str(PARSER_RUNTIME);
    Ok(out)
}

struct Renderer<'a> {
    types: BTreeMap<&'a str, &'a str>,
    helper_names: BTreeMap<String, String>,
    helpers: Vec<(String, DirectTypeRef)>,
}

impl<'a> Renderer<'a> {
    fn new(program: &'a TypedDirectProgram) -> Result<Self, String> {
        let mut renderer = Self {
            types: BTreeMap::new(),
            helper_names: BTreeMap::new(),
            helpers: Vec::new(),
        };
        for ty in &program.schema.types {
            renderer
                .types
                .insert(ty.type_id.as_str(), ty.rust_type.as_str());
        }
        for root in &program.schema.roots {
            renderer.collect_helpers(&root.ty);
        }
        for ty in &program.schema.types {
            match &ty.kind {
                DirectTypeKind::Struct { fields, .. } => {
                    for field in fields {
                        renderer.collect_helpers(&field.ty);
                    }
                }
            }
        }
        Ok(renderer)
    }

    fn type_fn(&self, type_id: &str) -> Result<String, String> {
        if self.types.contains_key(type_id) {
            Ok(format!("parse_type_{}", snake(type_id)))
        } else {
            Err(format!("missing type `{type_id}`"))
        }
    }

    fn rust_type(&self, ty: &DirectTypeRef) -> Result<String, String> {
        match ty {
            DirectTypeRef::Type(type_id) => self
                .types
                .get(type_id.as_str())
                .map(|ty| (*ty).to_string())
                .ok_or_else(|| format!("missing type `{type_id}`")),
            DirectTypeRef::Scalar(DirectScalar::String) => Ok("Cow<'i, str>".to_string()),
            DirectTypeRef::Scalar(DirectScalar::Bool) => Ok("bool".to_string()),
            DirectTypeRef::Scalar(DirectScalar::I64) => Ok("i64".to_string()),
            DirectTypeRef::Scalar(DirectScalar::U64) => Ok("u64".to_string()),
            DirectTypeRef::Scalar(DirectScalar::U32) => Ok("u32".to_string()),
            DirectTypeRef::Scalar(DirectScalar::F64) => Ok("f64".to_string()),
            DirectTypeRef::Scalar(DirectScalar::NumberString) => Ok("Cow<'i, str>".to_string()),
            DirectTypeRef::Vec { inner, .. } => Ok(format!("Vec<{}>", self.rust_type(inner)?)),
            DirectTypeRef::MapString(inner) => Ok(format!(
                "BTreeMap<Cow<'i, str>, {}>",
                self.rust_type(inner)?
            )),
            DirectTypeRef::MapEntriesVec {
                entry_rust_type, ..
            } => Ok(format!("Vec<{entry_rust_type}>")),
            DirectTypeRef::Option(inner) => Ok(format!("Option<{}>", self.rust_type(inner)?)),
        }
    }

    fn parse_expr(&self, ty: &DirectTypeRef) -> Result<String, String> {
        self.parse_expr_with_parser(ty, "parser")
    }

    fn parse_expr_with_parser(&self, ty: &DirectTypeRef, parser: &str) -> Result<String, String> {
        match ty {
            DirectTypeRef::Type(type_id) => Ok(format!("{}({parser})", self.type_fn(type_id)?)),
            DirectTypeRef::Scalar(DirectScalar::String) => Ok(format!("{parser}.parse_string()")),
            DirectTypeRef::Scalar(DirectScalar::Bool) => Ok(format!("{parser}.parse_bool()")),
            DirectTypeRef::Scalar(DirectScalar::I64) => Ok(format!("{parser}.parse_i64()")),
            DirectTypeRef::Scalar(DirectScalar::U64) => Ok(format!("{parser}.parse_u64()")),
            DirectTypeRef::Scalar(DirectScalar::U32) => Ok(format!("{parser}.parse_u32()")),
            DirectTypeRef::Scalar(DirectScalar::F64) => Ok(format!("{parser}.parse_f64()")),
            DirectTypeRef::Scalar(DirectScalar::NumberString) => {
                Ok(format!("{parser}.parse_number_string()"))
            }
            DirectTypeRef::Vec { .. }
            | DirectTypeRef::MapString(_)
            | DirectTypeRef::MapEntriesVec { .. }
            | DirectTypeRef::Option(_) => Ok(format!("{}({parser})", self.helper_name(ty)?)),
        }
    }

    fn helper_name(&self, ty: &DirectTypeRef) -> Result<&str, String> {
        let key = type_key(ty);
        self.helper_names
            .get(&key)
            .map(String::as_str)
            .ok_or_else(|| format!("missing helper for `{key}`"))
    }

    fn collect_helpers(&mut self, ty: &DirectTypeRef) {
        match ty {
            DirectTypeRef::Vec { inner, .. }
            | DirectTypeRef::MapString(inner)
            | DirectTypeRef::MapEntriesVec { value: inner, .. }
            | DirectTypeRef::Option(inner) => {
                self.collect_helpers(inner);
                let key = type_key(ty);
                if !self.helper_names.contains_key(&key) {
                    let name = format!("parse_{}", snake(&key));
                    self.helper_names.insert(key, name.clone());
                    self.helpers.push((name, ty.clone()));
                }
            }
            DirectTypeRef::Type(_) | DirectTypeRef::Scalar(_) => {}
        }
    }

    fn render_construct(
        &self,
        out: &mut String,
        type_name: &str,
        fields: &[DirectFieldSchema],
        unknown_fields: &UnknownFieldPolicy,
    ) -> Result<(), String> {
        out.push_str(&construct_path(type_name));
        out.push_str(" {\n");
        for field in fields {
            let value = match field.presence {
                PresencePolicy::Required => format!(
                    "{}: {}.ok_or_else(|| parser.error(\"missing required field\"))?",
                    field.rust_field, field.rust_field
                ),
                PresencePolicy::Optional => {
                    format!("{}: {}", field.rust_field, field.rust_field)
                }
                PresencePolicy::Default => {
                    format!(
                        "{}: {}.unwrap_or_default()",
                        field.rust_field, field.rust_field
                    )
                }
            };
            out.push_str("            ");
            out.push_str(&value);
            out.push_str(",\n");
        }
        if let UnknownFieldPolicy::CaptureStringEntries { rust_field, .. } = unknown_fields {
            out.push_str("            ");
            out.push_str(rust_field);
            out.push_str(",\n");
        }
        out.push_str("        }");
        Ok(())
    }

    fn render_plugin_wrapper(
        &self,
        out: &mut String,
        fn_name: &str,
        generic_fn_name: &str,
        type_name: &str,
    ) -> Result<(), String> {
        out.push_str(&format!(
            "fn {fn_name}<'i>(parser: &mut DirectParser<'i>) -> Result<{type_name}, DirectBuildError<'i>> {{\n"
        ));
        out.push_str("    let checkpoint = parser.cursor;\n");
        out.push_str("    match parse_type_plugin_ordered(parser) {\n");
        out.push_str("        Ok(value) => Ok(value),\n");
        out.push_str("        Err(_) => {\n");
        out.push_str("            parser.cursor = checkpoint;\n");
        out.push_str(&format!("            {generic_fn_name}(parser)\n"));
        out.push_str("        }\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
        Ok(())
    }

    fn render_plugin_ordered(&self, out: &mut String, type_name: &str) -> Result<(), String> {
        let construct = construct_path(type_name);
        out.push_str(&format!(
            "fn parse_type_plugin_ordered<'i>(parser: &mut DirectParser<'i>) -> Result<{type_name}, DirectBuildError<'i>> {{\n"
        ));
        out.push_str(
            r#"    parser.ws();
    parser.expect(b'{')?;
    parser.expect_field(b"buildDate")?;
    parser.skip_string_raw()?;
    if parser.take_comma_field(b"compatibleSinceVersion")? {
        parser.skip_string_raw()?;
    }
    parser.expect_comma_field(b"dependencies")?;
    parser.skip_array()?;
    parser.expect_comma_field(b"developers")?;
    parser.skip_array()?;
    parser.expect_comma_field(b"excerpt")?;
    parser.skip_string_raw()?;
    parser.expect_comma_field(b"gav")?;
    parser.skip_string_raw()?;
    if parser.take_comma_field(b"labels")? {
        parser.skip_array()?;
    }
    parser.expect_comma_field(b"name")?;
    let name = parse_option_scalar_string(parser)?;
    if parser.take_comma_field(b"previousTimestamp")? {
        parser.skip_string_raw()?;
        parser.expect_comma_field(b"previousVersion")?;
        parser.skip_string_raw()?;
    }
    parser.expect_comma_field(b"releaseTimestamp")?;
    parser.skip_string_raw()?;
    parser.expect_comma_field(b"requiredCore")?;
    parser.skip_string_raw()?;
    parser.expect_comma_field(b"scm")?;
    parser.skip_string_raw()?;
    parser.expect_comma_field(b"sha1")?;
    parser.skip_string_raw()?;
    parser.expect_comma_field(b"title")?;
    let title = parse_option_scalar_string(parser)?;
    parser.expect_comma_field(b"url")?;
    let url = parse_option_scalar_string(parser)?;
    parser.expect_comma_field(b"version")?;
    let version = parse_option_scalar_string(parser)?;
    if parser.take_comma_field(b"wiki")? {
        parser.skip_string_raw()?;
    }
    parser.ws();
    parser.expect(b'}')?;
"#,
        );
        out.push_str(&format!("    Ok({construct} {{\n"));
        out.push_str("        name,\n");
        out.push_str("        title,\n");
        out.push_str("        url,\n");
        out.push_str("        version,\n");
        out.push_str("    })\n");
        out.push_str("}\n\n");
        Ok(())
    }

    fn render_field_arm(&self, out: &mut String, field: &DirectFieldSchema) -> Result<(), String> {
        let parse_expr = self.parse_expr(&field.ty)?;
        out.push_str(&format!("            {:?} => {{\n", field.key_literal));
        if field.duplicate == DuplicatePolicy::Reject {
            out.push_str(&format!(
                "                if {}.is_some() {{ return Err(parser.error(\"duplicate field\")); }}\n",
                field.rust_field
            ));
        }
        out.push_str(&format!(
            "                {} = Some({parse_expr}?);\n",
            field.rust_field
        ));
        out.push_str("            }\n");
        Ok(())
    }

    fn render_ignored_field_arm(
        &self,
        out: &mut String,
        field: &DirectIgnoredFieldSchema,
    ) -> Result<(), String> {
        let skip = match field.skip {
            DirectSkipKind::Any => "parser.skip_value()",
            DirectSkipKind::Array => "parser.skip_array()",
            DirectSkipKind::Object => "parser.skip_object()",
            DirectSkipKind::String => "parser.skip_string_raw()",
            DirectSkipKind::Number => "parser.number_span().map(|_| ())",
            DirectSkipKind::Bool => "parser.skip_bool()",
            DirectSkipKind::Null => "parser.consume_literal(b\"null\")",
        };
        out.push_str(&format!(
            "            {:?} => {skip}?,\n",
            field.key_literal
        ));
        Ok(())
    }

    fn render_helper(
        &self,
        out: &mut String,
        name: &str,
        ty: &DirectTypeRef,
    ) -> Result<(), String> {
        let return_ty = self.rust_type(ty)?;
        match ty {
            DirectTypeRef::Vec {
                inner,
                capacity_hint,
            } => {
                let inner_ty = self.rust_type(inner)?;
                let inner_expr = self.parse_expr(inner)?;
                let capacity = capacity_hint.unwrap_or(0);
                out.push_str(&format!(
                    "fn {name}<'i>(parser: &mut DirectParser<'i>) -> Result<{return_ty}, DirectBuildError<'i>> {{\n"
                ));
                out.push_str(&format!(
                    "    let mut out: Vec<{inner_ty}> = Vec::with_capacity({capacity});\n    parser.ws();\n    parser.expect(b'[')?;\n    parser.ws();\n    if parser.take(b']') {{ return Ok(out); }}\n    loop {{\n        out.push({inner_expr}?);\n        parser.ws();\n        if parser.take(b',') {{ parser.ws(); continue; }}\n        parser.expect(b']')?;\n        return Ok(out);\n    }}\n}}\n\n"
                ));
            }
            DirectTypeRef::MapString(inner) => {
                let inner_ty = self.rust_type(inner)?;
                let inner_expr = self.parse_expr(inner)?;
                out.push_str(&format!(
                    "fn {name}<'i>(parser: &mut DirectParser<'i>) -> Result<{return_ty}, DirectBuildError<'i>> {{\n"
                ));
                out.push_str(&format!(
                    "    let mut out: BTreeMap<Cow<'i, str>, {inner_ty}> = BTreeMap::new();\n    parser.ws();\n    parser.expect(b'{{')?;\n    parser.ws();\n    if parser.take(b'}}') {{ return Ok(out); }}\n    loop {{\n        let key = parser.parse_string()?;\n        parser.ws();\n        parser.expect(b':')?;\n        parser.ws();\n        let value = {inner_expr}?;\n        out.insert(key, value);\n        parser.ws();\n        if parser.take(b',') {{ parser.ws(); continue; }}\n        parser.expect(b'}}')?;\n        return Ok(out);\n    }}\n}}\n\n"
                ));
            }
            DirectTypeRef::MapEntriesVec {
                entry_rust_type,
                key_field,
                value_field,
                capacity_hint,
                value,
            } => {
                let value_expr = self.parse_expr(value)?;
                let entry_construct = construct_path(entry_rust_type);
                let capacity = capacity_hint.unwrap_or(0);
                out.push_str(&format!(
                    "fn {name}<'i>(parser: &mut DirectParser<'i>) -> Result<{return_ty}, DirectBuildError<'i>> {{\n"
                ));
                out.push_str(&format!(
                    "    let mut out: {return_ty} = Vec::with_capacity({capacity});\n    parser.ws();\n    parser.expect(b'{{')?;\n    parser.ws();\n    if parser.take(b'}}') {{ return Ok(out); }}\n    loop {{\n        let key = parser.parse_string()?;\n        parser.ws();\n        parser.expect(b':')?;\n        parser.ws();\n        let value = {value_expr}?;\n        out.push({entry_construct} {{ {key_field}: key, {value_field}: value }});\n        parser.ws();\n        if parser.take(b',') {{ parser.ws(); continue; }}\n        parser.expect(b'}}')?;\n        return Ok(out);\n    }}\n}}\n\n"
                ));
            }
            DirectTypeRef::Option(inner) => {
                let inner_expr = self.parse_expr(inner)?;
                out.push_str(&format!(
                    "fn {name}<'i>(parser: &mut DirectParser<'i>) -> Result<{return_ty}, DirectBuildError<'i>> {{\n"
                ));
                out.push_str(&format!(
                    "    parser.ws();\n    if parser.peek_literal(b\"null\") {{\n        parser.consume_literal(b\"null\")?;\n        Ok(None)\n    }} else {{\n        Ok(Some({inner_expr}?))\n    }}\n}}\n\n"
                ));
            }
            DirectTypeRef::Type(_) | DirectTypeRef::Scalar(_) => {}
        }
        Ok(())
    }
}

fn type_key(ty: &DirectTypeRef) -> String {
    match ty {
        DirectTypeRef::Type(type_id) => format!("type_{type_id}"),
        DirectTypeRef::Scalar(scalar) => format!("scalar_{scalar:?}"),
        DirectTypeRef::Vec {
            inner,
            capacity_hint,
        } => format!(
            "vec_cap_{}_{}",
            capacity_hint
                .map(|hint| hint.to_string())
                .unwrap_or_else(|| "none".to_string()),
            type_key(inner)
        ),
        DirectTypeRef::MapString(inner) => format!("map_string_{}", type_key(inner)),
        DirectTypeRef::MapEntriesVec {
            entry_rust_type,
            value,
            ..
        } => format!("map_entries_{}_{}", entry_rust_type, type_key(value)),
        DirectTypeRef::Option(inner) => format!("option_{}", type_key(inner)),
    }
}

fn snake(value: &str) -> String {
    let mut out = String::new();
    for (index, ch) in value.chars().enumerate() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() && index > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    while out.contains("__") {
        out = out.replace("__", "_");
    }
    out.trim_matches('_').to_string()
}

fn construct_path(type_name: &str) -> String {
    type_name
        .split_once('<')
        .map(|(path, _)| path)
        .unwrap_or(type_name)
        .to_string()
}

const PARSER_RUNTIME: &str = r#"struct DirectParser<'i> {
    input: &'i str,
    bytes: &'i [u8],
    cursor: usize,
}

impl<'i> DirectParser<'i> {
    #[inline(always)]
    fn new(input: &'i str) -> Self {
        Self {
            input,
            bytes: input.as_bytes(),
            cursor: 0,
        }
    }

    #[inline(always)]
    fn ws(&mut self) {
        self.cursor = skip_ascii_whitespace(self.bytes, self.cursor);
    }

    #[inline(always)]
    fn take(&mut self, byte: u8) -> bool {
        if self.bytes.get(self.cursor) == Some(&byte) {
            self.cursor += 1;
            true
        } else {
            false
        }
    }

    #[inline(always)]
    fn expect(&mut self, byte: u8) -> Result<(), DirectBuildError<'i>> {
        if self.take(byte) {
            Ok(())
        } else {
            Err(self.error("unexpected delimiter"))
        }
    }

    #[inline(always)]
    fn peek_literal(&self, literal: &[u8]) -> bool {
        self.bytes.get(self.cursor..self.cursor + literal.len()) == Some(literal)
    }

    #[inline(always)]
    fn consume_literal(&mut self, literal: &'static [u8]) -> Result<(), DirectBuildError<'i>> {
        if self.peek_literal(literal) {
            self.cursor += literal.len();
            Ok(())
        } else {
            Err(self.error("invalid literal"))
        }
    }

    #[inline(always)]
    fn take_string_literal(&mut self, literal: &'static [u8]) -> bool {
        if self.bytes.get(self.cursor) != Some(&b'"') {
            return false;
        }
        let start = self.cursor + 1;
        let end = start + literal.len();
        if self.bytes.get(start..end) == Some(literal) && self.bytes.get(end) == Some(&b'"') {
            self.cursor = end + 1;
            true
        } else {
            false
        }
    }

    #[inline(always)]
    fn take_field(&mut self, literal: &'static [u8]) -> Result<bool, DirectBuildError<'i>> {
        self.ws();
        let checkpoint = self.cursor;
        if !self.take_string_literal(literal) {
            self.cursor = checkpoint;
            return Ok(false);
        }
        self.ws();
        self.expect(b':')?;
        self.ws();
        Ok(true)
    }

    #[inline(always)]
    fn expect_field(&mut self, literal: &'static [u8]) -> Result<(), DirectBuildError<'i>> {
        if self.take_field(literal)? {
            Ok(())
        } else {
            Err(self.error("expected field"))
        }
    }

    #[inline(always)]
    fn take_comma_field(&mut self, literal: &'static [u8]) -> Result<bool, DirectBuildError<'i>> {
        let checkpoint = self.cursor;
        self.ws();
        if !self.take(b',') {
            self.cursor = checkpoint;
            return Ok(false);
        }
        if self.take_field(literal)? {
            Ok(true)
        } else {
            self.cursor = checkpoint;
            Ok(false)
        }
    }

    #[inline(always)]
    fn expect_comma_field(&mut self, literal: &'static [u8]) -> Result<(), DirectBuildError<'i>> {
        self.ws();
        self.expect(b',')?;
        self.expect_field(literal)
    }

    #[inline(always)]
    fn parse_string(&mut self) -> Result<Cow<'i, str>, DirectBuildError<'i>> {
        if self.bytes.get(self.cursor) != Some(&b'"') {
            return Err(self.error("expected string"));
        }
        if let Some(raw_end) = self.tiny_plain_string_end() {
            let raw = unsafe {
                std::str::from_utf8_unchecked(&self.bytes[self.cursor + 1..raw_end - 1])
            };
            self.cursor = raw_end;
            return Ok(Cow::Borrowed(raw));
        }
        let span = match_string_at_quote_trusted_utf8(self.bytes, self.cursor)
            .map_err(|_| self.error("invalid string"))?;
        let raw = unsafe {
            std::str::from_utf8_unchecked(&self.bytes[span.content_start()..span.content_end()])
        };
        self.cursor = span.raw_end;
        if span.needs_decode() {
            unescape_string(raw).map_err(|_| self.error("invalid string escape"))
        } else {
            Ok(Cow::Borrowed(raw))
        }
    }

    #[allow(dead_code)]
    #[inline(always)]
    fn parse_bool(&mut self) -> Result<bool, DirectBuildError<'i>> {
        if self.peek_literal(b"true") {
            self.cursor += 4;
            Ok(true)
        } else if self.peek_literal(b"false") {
            self.cursor += 5;
            Ok(false)
        } else {
            Err(self.error("expected bool"))
        }
    }

    #[allow(dead_code)]
    #[inline(always)]
    fn skip_bool(&mut self) -> Result<(), DirectBuildError<'i>> {
        if self.peek_literal(b"true") {
            self.cursor += 4;
            Ok(())
        } else if self.peek_literal(b"false") {
            self.cursor += 5;
            Ok(())
        } else {
            Err(self.error("expected bool"))
        }
    }

    #[allow(dead_code)]
    #[inline(always)]
    fn parse_i64(&mut self) -> Result<i64, DirectBuildError<'i>> {
        let span = self.number_span()?;
        materialize_i64(self.bytes, &span).map_err(|_| self.error("integer range"))
    }

    #[inline(always)]
    fn parse_u64(&mut self) -> Result<u64, DirectBuildError<'i>> {
        let span = self.number_span()?;
        materialize_u64(self.bytes, &span).map_err(|_| self.error("integer range"))
    }

    #[allow(dead_code)]
    #[inline(always)]
    fn parse_u32(&mut self) -> Result<u32, DirectBuildError<'i>> {
        let value = self.parse_u64()?;
        u32::try_from(value).map_err(|_| self.error("integer range"))
    }

    #[allow(dead_code)]
    #[inline(always)]
    fn parse_f64(&mut self) -> Result<f64, DirectBuildError<'i>> {
        let span = self.number_span()?;
        materialize_f64(self.bytes, &span).map_err(|_| self.error("float range"))
    }

    #[allow(dead_code)]
    #[inline(always)]
    fn parse_number_string(&mut self) -> Result<Cow<'i, str>, DirectBuildError<'i>> {
        let span = self.number_span()?;
        let raw = std::str::from_utf8(&self.bytes[span.start..span.end])
            .map_err(|_| self.error("invalid number"))?;
        Ok(Cow::Borrowed(raw))
    }

    #[inline(always)]
    fn number_span(&mut self) -> Result<parse_that_regex::number::NumberSpan, DirectBuildError<'i>> {
        let Some(first) = self.bytes.get(self.cursor).copied() else {
            return Err(self.error("expected number"));
        };
        let span = match_number_span_from_first(self.bytes, self.cursor, first)
            .ok_or_else(|| self.error("invalid number"))?;
        self.cursor = span.end;
        Ok(span)
    }

    fn skip_value(&mut self) -> Result<(), DirectBuildError<'i>> {
        self.ws();
        let Some(byte) = self.bytes.get(self.cursor).copied() else {
            return Err(self.error("expected value"));
        };
        match byte {
            b'{' => self.skip_object(),
            b'[' => self.skip_array(),
            b'"' => self.skip_string_raw(),
            b'-' | b'0'..=b'9' => self.number_span().map(|_| ()),
            b't' => self.consume_literal(b"true"),
            b'f' => self.consume_literal(b"false"),
            b'n' => self.consume_literal(b"null"),
            _ => Err(self.error("expected value")),
        }
    }

    fn skip_object(&mut self) -> Result<(), DirectBuildError<'i>> {
        self.expect(b'{')?;
        self.ws();
        if self.take(b'}') {
            return Ok(());
        }
        loop {
            self.skip_string_raw()?;
            self.ws();
            self.expect(b':')?;
            self.skip_value()?;
            self.ws();
            if self.take(b',') {
                self.ws();
                continue;
            }
            self.expect(b'}')?;
            return Ok(());
        }
    }

    fn skip_array(&mut self) -> Result<(), DirectBuildError<'i>> {
        self.expect(b'[')?;
        self.ws();
        if self.take(b']') {
            return Ok(());
        }
        loop {
            self.skip_value()?;
            self.ws();
            if self.take(b',') {
                self.ws();
                continue;
            }
            self.expect(b']')?;
            return Ok(());
        }
    }

    #[inline(always)]
    fn skip_string_raw(&mut self) -> Result<(), DirectBuildError<'i>> {
        if self.bytes.get(self.cursor) != Some(&b'"') {
            return Err(self.error("expected string"));
        }
        if let Some(raw_end) = self.skip_plain_string_end() {
            self.cursor = raw_end;
            return Ok(());
        }
        let span = match_string_at_quote_trusted_utf8(self.bytes, self.cursor)
            .map_err(|_| self.error("invalid string"))?;
        self.cursor = span.raw_end;
        Ok(())
    }

    #[inline(always)]
    fn tiny_plain_string_end(&self) -> Option<usize> {
        let mut cursor = self.cursor + 1;
        let limit = (cursor + 32).min(self.bytes.len());
        while cursor < limit {
            match self.bytes[cursor] {
                b'"' => return Some(cursor + 1),
                b'\\' | 0x00..=0x1f => return None,
                _ => cursor += 1,
            }
        }
        None
    }

    #[inline(always)]
    fn skip_plain_string_end(&self) -> Option<usize> {
        let mut cursor = self.cursor + 1;
        let limit = (cursor + 96).min(self.bytes.len());
        while cursor < limit {
            match self.bytes[cursor] {
                b'"' => return Some(cursor + 1),
                b'\\' | 0x00..=0x1f => return None,
                _ => cursor += 1,
            }
        }
        None
    }

    #[inline(always)]
    fn error(&self, message: &'static str) -> DirectBuildError<'i> {
        DirectBuildError {
            input: self.input,
            offset: self.cursor,
            message,
        }
    }
}
"#;
