use crate::CodegenError;
use ir::BackendIr;

pub(crate) fn ensure_runtime_profile(backend: &BackendIr) -> Result<(), CodegenError> {
    if backend.grammar_name == "json" {
        Ok(())
    } else {
        Err(CodegenError::Lowering(format!(
            "runtime emission currently supports grammar profile `json`, found `{}`",
            backend.grammar_name
        )))
    }
}

pub(crate) fn mod_rs() -> String {
    normalize(
        r#"
        pub mod generated;
        pub mod host;
        pub mod parser;
        pub mod scan;
        pub mod sink;
        pub mod value;
        pub mod view;
        pub mod visitor;

        pub use parser::{parse, parse_bytes, RECOGNIZER_COUNT};
        pub use generated::parse_direct;
        pub use sink::JsonSink;
        pub use value::{JsonNodeKind, JsonToken, JsonValue, ParseError, ParseErrorKind};
        pub use view::{
            JsonArray, JsonBool, JsonDocument, JsonNull, JsonNumber, JsonObject, JsonPair,
            JsonRoot, JsonString,
        };
        pub use visitor::JsonVisitor;
        "#,
    )
}

pub(crate) fn host_rs() -> String {
    normalize(
        r#"
        // JSON is host-fn-free in the skinny compiler slice.
        "#,
    )
}

pub(crate) fn generated_rs() -> String {
    include_str!("json_templates/generated.rs").to_string()
}

pub(crate) fn parser_rs() -> String {
    include_str!("json_templates/parser.rs").to_string()
}

pub(crate) fn scan_rs() -> String {
    include_str!("../../runtime/src/grammars/json/scan.rs").to_string()
}

pub(crate) fn sink_rs() -> String {
    include_str!("../../runtime/src/grammars/json/sink.rs").to_string()
}

pub(crate) fn view_rs() -> String {
    include_str!("json_templates/view.rs").to_string()
}

pub(crate) fn value_rs() -> String {
    include_str!("json_templates/value.rs").to_string()
}

pub(crate) fn visitor_rs() -> String {
    normalize(include_str!("json_templates/visitor.rs"))
}

fn normalize(source: &str) -> String {
    let mut out = String::new();
    out.push_str("// @generated by skinny bbnf-codegen; do not edit by hand.\n");
    let trimmed = source.trim_matches('\n');
    let indent = trimmed
        .lines()
        .filter(|line| !line.trim().is_empty())
        .map(|line| line.chars().take_while(|ch| *ch == ' ').count())
        .min()
        .unwrap_or(0);
    for raw_line in trimmed.lines() {
        let line = raw_line.get(indent..).unwrap_or(raw_line).trim_end();
        if line.is_empty() {
            out.push('\n');
        } else {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}
