pub mod direct_schema;
mod grammar_profile;
pub mod grammar_provider;
mod json_sink_direct;
mod json_typed_direct;
pub(crate) mod lower;
pub(crate) mod runtime_generator;

use direct_schema::DirectSchemaSet;
use ir::{
    BackendIr, BackendShape, CostFacts, PerGrammarPolicyFacts, RuleId, SameSubstrateUnionFacts,
};
use std::collections::BTreeMap;
use std::path::Path;
use thiserror::Error;

pub use grammar_provider::{
    emit_runtime_from_request, RuntimeEmitterKind, RuntimeFrontendRequirements,
    RuntimeGenerationRequest, RuntimeGrammarSource, RuntimeOutputLabels, RuntimeProfileContract,
    RuntimeWorkspaceMetadata,
};

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error(transparent)]
    Grammar(#[from] grammar::GrammarError),
    #[error(transparent)]
    Pass(#[from] passes::PassError),
    #[error("missing generated file `{0}`")]
    MissingFile(String),
    #[error("generated file `{0}` differs")]
    DifferentFile(String),
    #[error("unexpected generated file `{0}`")]
    UnexpectedFile(String),
    #[error("lowering failed: {0}")]
    Lowering(String),
    #[error("{code}: {path}@{offset} source_hash={source_hash}")]
    UnsupportedRuntimeConstruct {
        code: &'static str,
        path: String,
        offset: usize,
        source_hash: String,
    },
    #[error(transparent)]
    Io(#[from] std::io::Error),
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EmittedSource {
    files: BTreeMap<String, String>,
}

impl EmittedSource {
    pub fn files(&self) -> impl Iterator<Item = (&str, &str)> {
        self.files
            .iter()
            .map(|(path, source)| (path.as_str(), source.as_str()))
    }

    pub fn get(&self, path: &str) -> Option<&str> {
        self.files.get(path).map(String::as_str)
    }

    pub fn write_to_dir(&self, output_dir: impl AsRef<Path>) -> Result<(), CodegenError> {
        let output_dir = output_dir.as_ref();
        std::fs::create_dir_all(output_dir)?;
        for (path, source) in &self.files {
            let file = output_dir.join(path);
            std::fs::write(file, source)?;
        }
        Ok(())
    }

    pub fn check_dir(&self, output_dir: impl AsRef<Path>) -> Result<(), CodegenError> {
        let output_dir = output_dir.as_ref();
        for (path, source) in &self.files {
            let file = output_dir.join(path);
            let actual = std::fs::read_to_string(&file)
                .map_err(|_| CodegenError::MissingFile(path.clone()))?;
            if actual != *source {
                return Err(CodegenError::DifferentFile(path.clone()));
            }
        }
        for entry in std::fs::read_dir(output_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
                continue;
            }
            let Some(file_name) = path.file_name().and_then(|name| name.to_str()) else {
                continue;
            };
            if self.files.contains_key(file_name) {
                continue;
            }
            let actual = std::fs::read_to_string(&path)?;
            if actual.starts_with(GENERATED_HEADER) {
                return Err(CodegenError::UnexpectedFile(file_name.to_string()));
            }
        }
        Ok(())
    }
}

const GENERATED_HEADER: &str = "// @generated by skinny bbnf-codegen; do not edit by hand.";

pub fn emit_from_source(grammar_name: &str, source: &str) -> Result<EmittedSource, CodegenError> {
    let grammar = grammar::parse_grammar(grammar_name, source)?;
    let output = passes::compile(&grammar)?;
    emit_with_layout(
        &output.backend_ir,
        &output.layout_facts.backend_shape,
        &output.layout_facts.cost_facts,
        &output.layout_facts.per_grammar_policy,
        &output.layout_facts.same_substrate_union,
        &output.diagnostics,
    )
}

pub fn emit(backend: &BackendIr) -> Result<EmittedSource, CodegenError> {
    let _ = backend;
    Err(CodegenError::Lowering(
        "W7 fail-closed: emit() requires pass-produced backend shape, active-cost, and CSP facts"
            .to_string(),
    ))
}

pub fn emit_runtime_profile(grammar_name: &str) -> Result<EmittedSource, CodegenError> {
    runtime_generator::emit_profile_only(grammar_name)
}

pub fn runtime_profile_expected_files(profile_id: &str) -> Result<Vec<&'static str>, CodegenError> {
    Err(grammar_profile::expected_files_for_error(profile_id))
}

pub fn emit_typed_from_source(
    grammar_name: &str,
    source: &str,
    schema: &DirectSchemaSet,
) -> Result<EmittedSource, CodegenError> {
    let grammar = grammar::parse_grammar(grammar_name, source)?;
    let output = passes::compile(&grammar)?;
    emit_typed_with_layout(
        &output.backend_ir,
        &output.layout_facts.backend_shape,
        &output.layout_facts.cost_facts,
        &output.layout_facts.per_grammar_policy,
        &output.layout_facts.same_substrate_union,
        &output.diagnostics,
        schema,
    )
}

fn emit_with_layout(
    backend: &BackendIr,
    backend_shape: &std::collections::HashMap<RuleId, BackendShape>,
    cost_facts: &std::collections::HashMap<RuleId, CostFacts>,
    per_grammar_policy: &std::collections::HashMap<RuleId, PerGrammarPolicyFacts>,
    same_substrate_union: &std::collections::HashMap<RuleId, SameSubstrateUnionFacts>,
    diagnostics: &[passes::diagnostics::PassDiagnostic],
) -> Result<EmittedSource, CodegenError> {
    let lowered = lower::lower_to_rust(
        backend,
        &lower::LowerCtx {
            backend_shape,
            cost_facts,
            per_grammar_policy,
            same_substrate_union,
            diagnostics,
        },
    )
    .map_err(CodegenError::Lowering)?;
    let sink_only = lowered.sink_only_program.as_ref().ok_or_else(|| {
        CodegenError::Lowering(
            "BackendIr did not contain DirectBuild sink-only program".to_string(),
        )
    })?;
    runtime_generator::emit_compiled(&backend.grammar_name, sink_only)
}

fn emit_typed_with_layout(
    backend: &BackendIr,
    backend_shape: &std::collections::HashMap<RuleId, BackendShape>,
    cost_facts: &std::collections::HashMap<RuleId, CostFacts>,
    per_grammar_policy: &std::collections::HashMap<RuleId, PerGrammarPolicyFacts>,
    same_substrate_union: &std::collections::HashMap<RuleId, SameSubstrateUnionFacts>,
    diagnostics: &[passes::diagnostics::PassDiagnostic],
    schema: &DirectSchemaSet,
) -> Result<EmittedSource, CodegenError> {
    let lowered = lower::lower_to_rust(
        backend,
        &lower::LowerCtx {
            backend_shape,
            cost_facts,
            per_grammar_policy,
            same_substrate_union,
            diagnostics,
        },
    )
    .map_err(CodegenError::Lowering)?;
    let sink_only = lowered.sink_only_program.as_ref().ok_or_else(|| {
        CodegenError::Lowering(
            "BackendIr did not contain DirectBuild sink-only program".to_string(),
        )
    })?;
    let typed =
        lower::schema_direct::lower_program(sink_only, schema).map_err(CodegenError::Lowering)?;
    let mut files = BTreeMap::new();
    files.insert(
        format!("{}.rs", schema.module_name),
        json_typed_direct::render(&typed).map_err(CodegenError::Lowering)?,
    );
    Ok(EmittedSource { files })
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CostFactsSnapshot {
    pub grammar: String,
    pub cost_facts: std::collections::BTreeMap<String, CostFacts>,
    pub diagnostics: Vec<DiagnosticSnapshot>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DiagnosticSnapshot {
    pub code: String,
    pub rule: Option<RuleId>,
    pub message: String,
}

pub fn cost_facts_from_source(
    grammar_name: &str,
    source: &str,
) -> Result<CostFactsSnapshot, CodegenError> {
    let grammar = grammar::parse_grammar(grammar_name, source)?;
    let output = passes::compile(&grammar)?;
    let cost_facts = output
        .layout_facts
        .cost_facts
        .iter()
        .map(|(rule_id, facts)| (rule_id.0.to_string(), facts.clone()))
        .collect();
    let diagnostics = output
        .diagnostics
        .iter()
        .map(|diagnostic| DiagnosticSnapshot {
            code: diagnostic.code().to_string(),
            rule: diagnostic.rule,
            message: diagnostic.message.clone(),
        })
        .collect();
    Ok(CostFactsSnapshot {
        grammar: output.grammar.name,
        cost_facts,
        diagnostics,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use direct_schema::{
        DirectFieldSchema, DirectRootSchema, DirectScalar, DirectTypeKind, DirectTypeRef,
        DirectTypeSchema, DuplicatePolicy, PresencePolicy, UnknownFieldPolicy,
    };
    use ir::BackendExpr;

    const JSON_GRAMMAR: &str = include_str!("../../../grammars/json.bbnf");

    fn w5a_metadata() -> RuntimeWorkspaceMetadata {
        RuntimeWorkspaceMetadata {
            repo_manifest_path: "Cargo.toml".to_string(),
            skinny_manifest_path: "skinny/Cargo.toml".to_string(),
            grammar_manifest_path: "grammar/css/l4/stylesheet.bbnf".to_string(),
            generated_root: "crates/runtime/src/grammars".to_string(),
            host_registry: "skinny-none".to_string(),
            profile: "balanced".to_string(),
        }
    }

    fn compiled_contract() -> RuntimeProfileContract {
        RuntimeProfileContract {
            emitter: RuntimeEmitterKind::CompiledLowering,
            expected_files: grammar_profile::COMPILED_RUNTIME_FILES,
            frontend_requirements: RuntimeFrontendRequirements::none(),
            output_labels: None,
        }
    }

    fn request_facts_contract(profile_id: &str) -> RuntimeProfileContract {
        RuntimeProfileContract {
            emitter: RuntimeEmitterKind::RequestFacts,
            expected_files: grammar_profile::REQUEST_FACTS_RUNTIME_FILES,
            frontend_requirements: RuntimeFrontendRequirements::full_request_facts(),
            output_labels: Some(request_facts_labels(profile_id)),
        }
    }

    fn request_facts_labels(profile_id: &str) -> RuntimeOutputLabels {
        W5C_REQUEST_FACT_PROFILES
            .iter()
            .find(|profile| profile.profile_id == profile_id)
            .map(|profile| profile.labels)
            .unwrap_or_else(|| panic!("missing request-facts profile {profile_id}"))
    }

    fn w5a_css_request(source: &str) -> RuntimeGenerationRequest {
        let mut sources = vec![RuntimeGrammarSource {
            rel_path: "grammar/css/l4/stylesheet.bbnf".to_string(),
            source: source.to_string(),
        }];
        if source.contains("@import \"tokens.bbnf\"") {
            sources.push(RuntimeGrammarSource {
                rel_path: "grammar/css/l4/tokens.bbnf".to_string(),
                source: "ident = /[a-z]+/ ;\n".to_string(),
            });
        }

        RuntimeGenerationRequest {
            grammar_name: "css_l4".to_string(),
            profile_id: "css_l4_declaration_values".to_string(),
            entry_rule: "stylesheet".to_string(),
            source_roots: vec!["grammar/css/l4/stylesheet.bbnf".to_string()],
            sources,
            workspace_metadata: w5a_metadata(),
            output_dir: "crates/runtime/src/grammars/css_l4_declaration_values".to_string(),
            profile_contract: request_facts_contract("css_l4_declaration_values"),
        }
    }

    #[derive(Clone, Copy)]
    struct RequestFactsProfile {
        profile_id: &'static str,
        labels: RuntimeOutputLabels,
    }

    const W5C_REQUEST_FACT_PROFILES: &[RequestFactsProfile] = &[
        RequestFactsProfile {
            profile_id: "css_l4_declaration_values",
            labels: RuntimeOutputLabels {
                fact_schema: "css-l4-declaration-value-facts-v1",
                row_id: "css_l4/declaration_values/direct_to_struct/main",
                output_plane: "css_l4_declaration_value_fact_stream",
            },
        },
        RequestFactsProfile {
            profile_id: "css_l4_declaration_values_extended",
            labels: RuntimeOutputLabels {
                fact_schema: "css-l4-declaration-value-extended-facts-v1",
                row_id: "css_l4/declaration_values_extended/direct_to_struct/main",
                output_plane: "css_l4_declaration_value_extended_fact_stream",
            },
        },
        RequestFactsProfile {
            profile_id: "css_l4_stylesheet_selectors",
            labels: RuntimeOutputLabels {
                fact_schema: "css-l4-stylesheet-selector-facts-v1",
                row_id: "css_l4/stylesheet_and_selectors/direct_to_struct/main",
                output_plane: "css_l4_stylesheet_selector_fact_stream",
            },
        },
        RequestFactsProfile {
            profile_id: "css_l4_visual_functions",
            labels: RuntimeOutputLabels {
                fact_schema: "css-l4-visual-function-facts-v1",
                row_id: "css_l4/visual_functions/direct_to_struct/main",
                output_plane: "css_l4_visual_function_fact_stream",
            },
        },
        RequestFactsProfile {
            profile_id: "css_l4_at_rules_and_media",
            labels: RuntimeOutputLabels {
                fact_schema: "css-l4-at-rules-media-facts-v1",
                row_id: "css_l4/at_rules_and_media/direct_to_struct/main",
                output_plane: "css_l4_at_rules_media_fact_stream",
            },
        },
        RequestFactsProfile {
            profile_id: "css_l4_vendor_and_custom_atrules",
            labels: RuntimeOutputLabels {
                fact_schema: "css-l4-vendor-custom-facts-v1",
                row_id: "css_l4/vendor_and_custom_atrules/direct_to_struct/main",
                output_plane: "css_l4_vendor_custom_fact_stream",
            },
        },
        RequestFactsProfile {
            profile_id: "css_l4_nested_layout",
            labels: RuntimeOutputLabels {
                fact_schema: "css-l4-nested-layout-facts-v1",
                row_id: "css_l4/nested_layout/direct_to_struct/main",
                output_plane: "css_l4_nested_layout_fact_stream",
            },
        },
    ];

    const W5C_CSS_SOURCE: &str = r#"
@import "tokens.bbnf" ;
@token ident ;
@ws /\s*/ ;
@pretty stylesheet block ;
root = @{ "url" , "(" >> ident ?w , "," ?w , ident << ")" } ;
tag = "from" -> 0u8 | "paint" -> crate::paint(input): u32 ;
"#;

    fn w5c_css_request(profile_id: &str, source: &str) -> RuntimeGenerationRequest {
        let mut request = w5a_css_request(source);
        request.profile_id = profile_id.to_string();
        request.output_dir = format!("crates/runtime/src/grammars/{profile_id}");
        request.profile_contract = request_facts_contract(profile_id);
        request
    }

    fn w5c_full_css_request(profile_id: &str) -> RuntimeGenerationRequest {
        let sources = [
            (
                "grammar/css/l4/color.bbnf",
                include_str!("../../../../grammar/css/l4/color.bbnf"),
            ),
            (
                "grammar/css/l4/easing.bbnf",
                include_str!("../../../../grammar/css/l4/easing.bbnf"),
            ),
            (
                "grammar/css/l4/filters.bbnf",
                include_str!("../../../../grammar/css/l4/filters.bbnf"),
            ),
            (
                "grammar/css/l4/func-body.bbnf",
                include_str!("../../../../grammar/css/l4/func-body.bbnf"),
            ),
            (
                "grammar/css/l4/gradients.bbnf",
                include_str!("../../../../grammar/css/l4/gradients.bbnf"),
            ),
            (
                "grammar/css/l4/keyframes.bbnf",
                include_str!("../../../../grammar/css/l4/keyframes.bbnf"),
            ),
            (
                "grammar/css/l4/keywords.bbnf",
                include_str!("../../../../grammar/css/l4/keywords.bbnf"),
            ),
            (
                "grammar/css/l4/media.bbnf",
                include_str!("../../../../grammar/css/l4/media.bbnf"),
            ),
            (
                "grammar/css/l4/properties.bbnf",
                include_str!("../../../../grammar/css/l4/properties.bbnf"),
            ),
            (
                "grammar/css/l4/selectors.bbnf",
                include_str!("../../../../grammar/css/l4/selectors.bbnf"),
            ),
            (
                "grammar/css/l4/stylesheet.bbnf",
                include_str!("../../../../grammar/css/l4/stylesheet.bbnf"),
            ),
            (
                "grammar/css/l4/tokens.bbnf",
                include_str!("../../../../grammar/css/l4/tokens.bbnf"),
            ),
            (
                "grammar/css/l4/transforms.bbnf",
                include_str!("../../../../grammar/css/l4/transforms.bbnf"),
            ),
            (
                "grammar/css/l4/value-unit.bbnf",
                include_str!("../../../../grammar/css/l4/value-unit.bbnf"),
            ),
            (
                "grammar/css/l4/values.bbnf",
                include_str!("../../../../grammar/css/l4/values.bbnf"),
            ),
        ]
        .into_iter()
        .map(|(rel_path, source)| RuntimeGrammarSource {
            rel_path: rel_path.to_string(),
            source: source.to_string(),
        })
        .collect();

        RuntimeGenerationRequest {
            grammar_name: "css_l4".to_string(),
            profile_id: profile_id.to_string(),
            entry_rule: "stylesheet".to_string(),
            source_roots: vec!["grammar/css/l4/stylesheet.bbnf".to_string()],
            sources,
            workspace_metadata: w5a_metadata(),
            output_dir: format!("crates/runtime/src/grammars/{profile_id}"),
            profile_contract: request_facts_contract(profile_id),
        }
    }

    #[test]
    fn emits_expected_file_set_in_order() {
        let emitted = emit_from_source("json", JSON_GRAMMAR).unwrap();
        let names: Vec<_> = emitted.files().map(|(path, _)| path).collect();

        assert_eq!(
            names,
            [
                "config.rs",
                "generated.rs",
                "host.rs",
                "mod.rs",
                "parser.rs",
                "value.rs",
                "view.rs",
                "visitor.rs"
            ]
        );
    }

    #[test]
    fn emission_is_deterministic() {
        let first = emit_from_source("json", JSON_GRAMMAR).unwrap();
        let second = emit_from_source("json", JSON_GRAMMAR).unwrap();

        assert_eq!(first, second);
        assert!(first.get("config.rs").unwrap().contains("STRUCTURAL_BYTES"));
        assert!(first
            .get("generated.rs")
            .unwrap()
            .contains("config::STRUCTURAL_BYTES"));
    }

    #[test]
    fn json_config_policy_fields_are_consumed() {
        let emitted = emit_from_source("json", JSON_GRAMMAR).unwrap();
        let generated = emitted.get("generated.rs").unwrap();
        let view = emitted.get("view.rs").unwrap();
        let config = emitted.get("config.rs").unwrap();

        for (field, consumer) in [
            ("STRUCTURAL_BYTES", "config::STRUCTURAL_BYTES"),
            ("STRING_NEEDS_DECODE", "config::STRING_NEEDS_DECODE"),
            ("TINY_STRING_CAP", "config::TINY_STRING_CAP"),
            ("DIRECT_TINY_STRING_CAP", "config::DIRECT_TINY_STRING_CAP"),
            ("TRUE_LITERAL", "config::TRUE_LITERAL"),
            ("FALSE_LITERAL", "config::FALSE_LITERAL"),
            ("NULL_LITERAL", "config::NULL_LITERAL"),
            ("needs_decode_flags", "config::needs_decode_flags"),
        ] {
            assert!(config.contains(field), "config missing {field}");
            assert!(
                generated.contains(consumer) || view.contains(consumer),
                "{field} has no generated consumer"
            );
        }
    }

    #[test]
    fn grammar_profile_fields_are_consumed() {
        let emitted = emit_from_source("json", JSON_GRAMMAR).unwrap();
        let names = emitted.files().map(|(name, _)| name).collect::<Vec<_>>();

        assert_eq!(names, grammar_profile::COMPILED_RUNTIME_FILES);
        assert!(matches!(
            runtime_profile_expected_files("css_l4"),
            Err(CodegenError::Lowering(message))
                if message.contains("RuntimeGenerationRequest profile contract")
        ));
    }

    #[test]
    fn css_l4_frontend_profiles_are_request_generated() {
        for profile in W5C_REQUEST_FACT_PROFILES {
            let profile_id = profile.profile_id;
            let emitted = emit_runtime_from_request(w5c_css_request(profile_id, W5C_CSS_SOURCE))
                .expect("request generated css runtime");
            let names = emitted.files().map(|(name, _)| name).collect::<Vec<_>>();

            assert_eq!(names, grammar_profile::REQUEST_FACTS_RUNTIME_FILES);
            assert!(emitted
                .get("config.rs")
                .unwrap()
                .contains("FRONTEND_SOURCE_HASH"));
            assert!(emitted
                .get("generated.rs")
                .unwrap()
                .contains("emit_fact_stream"));
            assert!(emitted.get("parser.rs").unwrap().contains("parse_bytes"));
        }
    }

    #[test]
    fn json_and_css_runtime_outputs_consume_w7_policy() {
        let json = emit_from_source("json", JSON_GRAMMAR).unwrap();
        let json_config = json.get("config.rs").unwrap();
        let json_generated = json.get("generated.rs").unwrap();

        assert!(json_config.contains("W7_DIRECT_BACKEND_SHAPE"));
        assert!(json_config.contains("W7_SUBSTRATE_TARGET: &str = \"direct_sink\""));
        assert!(json_generated.contains("config::w7_direct_policy_triad"));
        assert!(json_generated.contains("parse_w11_1_number_array_direct"));

        let css = emit_runtime_from_request(w5c_css_request(
            "css_l4_declaration_values_extended",
            W5C_CSS_SOURCE,
        ))
        .unwrap();
        let css_config = css.get("config.rs").unwrap();
        let css_generated = css.get("generated.rs").unwrap();

        assert!(css_config.contains("W7_SUBSTRATE_TARGET: &str = \"admitted_fact_output\""));
        assert!(css_generated.contains("config::W7_SAME_SUBSTRATE_UNION"));
    }

    #[test]
    fn css_l4_generated_runtimes_reproducible_from_request() {
        for profile in W5C_REQUEST_FACT_PROFILES {
            let profile_id = profile.profile_id;
            let emitted = emit_runtime_from_request(w5c_full_css_request(profile_id))
                .expect("request generated css runtime");
            let runtime_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../runtime/src/grammars")
                .join(profile_id);
            emitted.check_dir(runtime_dir).unwrap();
        }
    }

    #[test]
    fn direct_parser_is_authored_from_sink_only_lowering() {
        let grammar = grammar::parse_grammar("json", JSON_GRAMMAR).unwrap();
        let output = passes::compile(&grammar).unwrap();
        let lowered = lower::lower_to_rust(
            &output.backend_ir,
            &lower::LowerCtx {
                backend_shape: &output.layout_facts.backend_shape,
                cost_facts: &output.layout_facts.cost_facts,
                per_grammar_policy: &output.layout_facts.per_grammar_policy,
                same_substrate_union: &output.layout_facts.same_substrate_union,
                diagnostics: &output.diagnostics,
            },
        )
        .unwrap();
        let program = lowered.sink_only_program.unwrap();

        assert_eq!(program.entry_rule, "json");
        assert!(program.has_shape("JsonObject"));
        assert!(program.has_shape("JsonNull"));
        assert!(program.has_literal(b"true"));
        assert!(program.has_literal(b"false"));
        assert!(program.has_literal(b"null"));

        let emitted = emit_from_source("json", JSON_GRAMMAR).unwrap();
        let generated = emitted.get("generated.rs").unwrap();
        assert!(generated.contains("// sink-only lowered from BackendIr: entry=json"));
        assert!(generated.contains("pub fn parse_direct"));
    }

    #[test]
    fn emits_distinct_json_parse_only_path_without_tape_builder() {
        let emitted = emit_from_source("json", JSON_GRAMMAR).unwrap();
        let parser = emitted.get("parser.rs").unwrap();
        let generated = emitted.get("generated.rs").unwrap();
        let start = generated
            .find("struct ParseOnlyState")
            .expect("parse_only state emitted");
        let end = generated
            .find("// sink-only lowered from BackendIr")
            .unwrap_or(generated.len());
        let parse_only_section = &generated[start..end];

        assert!(parser.contains("pub fn parse_only"));
        assert!(parser.contains("generated::parse_only(input)"));
        assert!(emitted
            .get("mod.rs")
            .unwrap()
            .contains("parse_only, parse_only_bytes"));
        assert!(generated.contains("pub fn parse_only"));
        assert!(parse_only_section.contains("fn parse_only_value_iterative"));
        assert!(parse_only_section.contains("enum ParseOnlyFrame"));
        assert!(parse_only_section.contains("fn parse_only_string"));
        assert!(!parse_only_section.contains("TapeBuilder"));
        assert!(!parse_only_section.contains("emit_plain_offset"));
        assert!(generated.contains(
            "#[cfg_attr(feature = \"parse-attribution\", inline(never))]\n\
             #[cfg_attr(not(feature = \"parse-attribution\"), inline(always))]\n\
             pub fn parse_only"
        ));
    }

    #[test]
    fn bare_emit_fails_closed_without_pass_facts() {
        let grammar = grammar::parse_grammar("json", JSON_GRAMMAR).unwrap();
        let output = passes::compile(&grammar).unwrap();
        let err = emit(&output.backend_ir).unwrap_err();

        assert!(
            matches!(err, CodegenError::Lowering(message) if message.contains("W7 fail-closed"))
        );
    }

    #[test]
    fn lowering_rejects_non_sat_csp_facts() {
        let grammar = grammar::parse_grammar("json", JSON_GRAMMAR).unwrap();
        let mut output = passes::compile(&grammar).unwrap();
        let cost = output.layout_facts.cost_facts.get_mut(&RuleId(0)).unwrap();
        let csp = cost.decision_csp.as_mut().unwrap();
        csp.csp_status = "unsat".into();
        csp.selected_rule_count = 0;

        let err = lower::lower_to_rust(
            &output.backend_ir,
            &lower::LowerCtx {
                backend_shape: &output.layout_facts.backend_shape,
                cost_facts: &output.layout_facts.cost_facts,
                per_grammar_policy: &output.layout_facts.per_grammar_policy,
                same_substrate_union: &output.layout_facts.same_substrate_union,
                diagnostics: &output.diagnostics,
            },
        )
        .unwrap_err();

        assert!(err.contains("W7 fail-closed: decision-CSP status unsat"));
    }

    #[test]
    fn lowering_rejects_missing_w7_policy_facts() {
        let grammar = grammar::parse_grammar("json", JSON_GRAMMAR).unwrap();
        let output = passes::compile(&grammar).unwrap();
        let empty_policy = std::collections::HashMap::new();

        let err = lower::lower_to_rust(
            &output.backend_ir,
            &lower::LowerCtx {
                backend_shape: &output.layout_facts.backend_shape,
                cost_facts: &output.layout_facts.cost_facts,
                per_grammar_policy: &empty_policy,
                same_substrate_union: &output.layout_facts.same_substrate_union,
                diagnostics: &output.diagnostics,
            },
        )
        .unwrap_err();

        assert!(err.contains("W7 fail-closed: missing per-grammar policy facts"));
    }

    #[test]
    fn refuses_direct_parser_without_direct_builds() {
        let grammar = grammar::parse_grammar("json", JSON_GRAMMAR).unwrap();
        let mut output = passes::compile(&grammar).unwrap();
        for rule in &mut output.backend_ir.rules {
            strip_direct_builds(&mut rule.expr);
        }

        let err = emit_with_layout(
            &output.backend_ir,
            &output.layout_facts.backend_shape,
            &output.layout_facts.cost_facts,
            &output.layout_facts.per_grammar_policy,
            &output.layout_facts.same_substrate_union,
            &output.diagnostics,
        )
        .unwrap_err();

        assert!(matches!(err, CodegenError::Lowering(_)));
    }

    #[test]
    fn emits_typed_direct_consumer_module() {
        let schema = tiny_schema();
        let emitted = emit_typed_from_source("json", JSON_GRAMMAR, &schema).unwrap();
        let generated = emitted.get("tiny_typed.rs").unwrap();

        assert!(generated.contains("pub fn parse_tiny"));
        assert!(generated.contains("fn parse_type_tiny_root"));
        assert!(generated.contains("DirectBuildError"));
        assert!(!generated.contains("JsonSink"));
        assert!(!generated.contains("serde_json::Value"));
    }

    #[test]
    fn refuses_typed_emission_without_direct_builds() {
        let schema = tiny_schema();
        let grammar = grammar::parse_grammar("json", JSON_GRAMMAR).unwrap();
        let mut output = passes::compile(&grammar).unwrap();
        for rule in &mut output.backend_ir.rules {
            strip_direct_builds(&mut rule.expr);
        }

        let err = emit_typed_with_layout(
            &output.backend_ir,
            &output.layout_facts.backend_shape,
            &output.layout_facts.cost_facts,
            &output.layout_facts.per_grammar_policy,
            &output.layout_facts.same_substrate_union,
            &output.diagnostics,
            &schema,
        )
        .unwrap_err();

        assert!(matches!(err, CodegenError::Lowering(_)));
    }

    fn tiny_schema() -> DirectSchemaSet {
        DirectSchemaSet {
            module_name: "tiny_typed".to_string(),
            schema_hash: "test-schema".to_string(),
            roots: vec![DirectRootSchema::struct_root(
                "parse_tiny",
                "crate::TinyRoot<'i>",
                "TinyRoot",
            )],
            types: vec![DirectTypeSchema {
                type_id: "TinyRoot".to_string(),
                rust_type: "crate::TinyRoot<'i>".to_string(),
                kind: DirectTypeKind::Struct {
                    unknown_fields: UnknownFieldPolicy::Skip,
                    ignored_fields: Vec::new(),
                    fields: vec![
                        DirectFieldSchema {
                            key_literal: "name".to_string(),
                            rust_field: "name".to_string(),
                            ty: DirectTypeRef::Scalar(DirectScalar::String),
                            presence: PresencePolicy::Required,
                            duplicate: DuplicatePolicy::Reject,
                        },
                        DirectFieldSchema {
                            key_literal: "items".to_string(),
                            rust_field: "items".to_string(),
                            ty: DirectTypeRef::Vec {
                                inner: Box::new(DirectTypeRef::Scalar(DirectScalar::U64)),
                                capacity_hint: None,
                            },
                            presence: PresencePolicy::Default,
                            duplicate: DuplicatePolicy::LastWins,
                        },
                    ],
                },
            }],
        }
    }

    #[test]
    fn emits_typed_direct_collection_roots() {
        let schema = DirectSchemaSet {
            module_name: "root_typed".to_string(),
            schema_hash: "test-root-schema".to_string(),
            roots: vec![
                DirectRootSchema::typed_root(
                    "parse_array_root",
                    "Vec<crate::ArrayEvent<'i>>",
                    DirectTypeRef::Vec {
                        inner: Box::new(DirectTypeRef::Type("ArrayEvent".to_string())),
                        capacity_hint: Some(2),
                    },
                ),
                DirectRootSchema::typed_root(
                    "parse_map_root",
                    "Vec<crate::MapEntry<'i>>",
                    DirectTypeRef::MapEntriesVec {
                        entry_rust_type: "crate::MapEntry<'i>".to_string(),
                        key_field: "key".to_string(),
                        value_field: "value".to_string(),
                        capacity_hint: Some(2),
                        value: Box::new(DirectTypeRef::Type("MapValue".to_string())),
                    },
                ),
            ],
            types: vec![
                DirectTypeSchema {
                    type_id: "ArrayEvent".to_string(),
                    rust_type: "crate::ArrayEvent<'i>".to_string(),
                    kind: DirectTypeKind::Struct {
                        unknown_fields: UnknownFieldPolicy::Skip,
                        ignored_fields: Vec::new(),
                        fields: vec![DirectFieldSchema {
                            key_literal: "name".to_string(),
                            rust_field: "name".to_string(),
                            ty: DirectTypeRef::Scalar(DirectScalar::String),
                            presence: PresencePolicy::Default,
                            duplicate: DuplicatePolicy::LastWins,
                        }],
                    },
                },
                DirectTypeSchema {
                    type_id: "MapValue".to_string(),
                    rust_type: "crate::MapValue<'i>".to_string(),
                    kind: DirectTypeKind::Struct {
                        unknown_fields: UnknownFieldPolicy::Skip,
                        ignored_fields: Vec::new(),
                        fields: vec![DirectFieldSchema {
                            key_literal: "count".to_string(),
                            rust_field: "count".to_string(),
                            ty: DirectTypeRef::Scalar(DirectScalar::U64),
                            presence: PresencePolicy::Default,
                            duplicate: DuplicatePolicy::LastWins,
                        }],
                    },
                },
            ],
        };

        let emitted = emit_typed_from_source("json", JSON_GRAMMAR, &schema).unwrap();
        let generated = emitted.get("root_typed.rs").unwrap();

        assert!(generated.contains("pub fn parse_array_root"));
        assert!(generated.contains("pub fn parse_map_root"));
        assert!(generated.contains("parse_vec_cap_2_type_array_event"));
        assert!(generated.contains("parse_map_entries_crate_map_entry"));
        assert!(!generated.contains("JsonSink"));
        assert!(!generated.contains("serde_json::Value"));
    }

    #[test]
    fn emits_typed_direct_number_string_capture() {
        let schema = DirectSchemaSet {
            module_name: "numeric_typed".to_string(),
            schema_hash: "test-number-string-schema".to_string(),
            roots: vec![DirectRootSchema::struct_root(
                "parse_numeric",
                "crate::NumericRoot<'i>",
                "NumericRoot",
            )],
            types: vec![DirectTypeSchema {
                type_id: "NumericRoot".to_string(),
                rust_type: "crate::NumericRoot<'i>".to_string(),
                kind: DirectTypeKind::Struct {
                    unknown_fields: UnknownFieldPolicy::Skip,
                    ignored_fields: Vec::new(),
                    fields: vec![DirectFieldSchema {
                        key_literal: "coordinate".to_string(),
                        rust_field: "coordinate".to_string(),
                        ty: DirectTypeRef::Scalar(DirectScalar::NumberString),
                        presence: PresencePolicy::Required,
                        duplicate: DuplicatePolicy::Reject,
                    }],
                },
            }],
        };

        let emitted = emit_typed_from_source("json", JSON_GRAMMAR, &schema).unwrap();
        let generated = emitted.get("numeric_typed.rs").unwrap();

        assert!(generated.contains("let mut coordinate: Option<Cow<'i, str>> = None;"));
        assert!(generated.contains("parser.parse_number_string()?"));
        assert!(generated.contains("Ok(Cow::Borrowed(raw))"));
        assert!(!generated.contains("parse_f64()?"));
    }

    #[test]
    fn emits_typed_direct_unknown_string_capture() {
        let schema = DirectSchemaSet {
            module_name: "capture_typed".to_string(),
            schema_hash: "test-capture-schema".to_string(),
            roots: vec![DirectRootSchema::struct_root(
                "parse_capture",
                "crate::CaptureRoot<'i>",
                "CaptureRoot",
            )],
            types: vec![DirectTypeSchema {
                type_id: "CaptureRoot".to_string(),
                rust_type: "crate::CaptureRoot<'i>".to_string(),
                kind: DirectTypeKind::Struct {
                    unknown_fields: UnknownFieldPolicy::CaptureStringEntries {
                        rust_field: "dynamic".to_string(),
                        entry_rust_type: "crate::CapturedField<'i>".to_string(),
                        key_field: "key".to_string(),
                        value_field: "value".to_string(),
                        capacity_hint: Some(4),
                    },
                    ignored_fields: Vec::new(),
                    fields: vec![DirectFieldSchema {
                        key_literal: "status".to_string(),
                        rust_field: "status".to_string(),
                        ty: DirectTypeRef::Scalar(DirectScalar::String),
                        presence: PresencePolicy::Default,
                        duplicate: DuplicatePolicy::LastWins,
                    }],
                },
            }],
        };

        let emitted = emit_typed_from_source("json", JSON_GRAMMAR, &schema).unwrap();
        let generated = emitted.get("capture_typed.rs").unwrap();

        assert!(generated
            .contains("let mut dynamic: Vec<crate::CapturedField<'i>> = Vec::with_capacity(4);"));
        assert!(generated.contains("let value = parser.parse_string()?;"));
        assert!(
            generated.contains("dynamic.push(crate::CapturedField { key: key, value: value });")
        );
        assert!(generated.contains("dynamic,"));
    }

    pub(super) fn w5a_runtime_contract_consumes_source_and_metadata() {
        let source = r#"
@import "tokens.bbnf" ;
@token ident ;
@ws /\s*/ ;
@pretty stylesheet block ;
root = @{ "url" , "(" >> ident ?w , "," ?w , ident << ")" } ;
tag = "from" -> 0u8 | "paint" -> crate::paint(input): u32 ;
"#;
        let emitted = emit_runtime_from_request(w5a_css_request(source)).unwrap();
        assert!(emitted
            .get("generated.rs")
            .unwrap()
            .contains("emit_fact_stream"));

        let mut missing_metadata = w5a_css_request(source);
        missing_metadata.workspace_metadata.generated_root.clear();
        assert!(matches!(
            emit_runtime_from_request(missing_metadata),
            Err(CodegenError::Lowering(message)) if message.contains("generated_root")
        ));

        let missing_fact = w5a_css_request("@import \"tokens.bbnf\" ;\nroot = \"x\" ;\n");
        assert!(matches!(
            emit_runtime_from_request(missing_fact),
            Err(CodegenError::Lowering(message)) if message.contains("frontend closure missing")
        ));
    }

    pub(super) fn w5b_frontend_request_consumes_lowered_ir_before_provider_rendering() {
        let source = r#"
@import "tokens.bbnf" ;
@token ident ;
@ws /\s*/ ;
@pretty stylesheet block ;
root = @{ "url" , "(" >> ident ?w , "," ?w , ident << ")" } ;
tag = "from" -> 0u8 | "paint" -> crate::paint(input): u32 ;
"#;
        let emitted = emit_runtime_from_request(w5a_css_request(source)).unwrap();

        assert!(emitted
            .get("generated.rs")
            .unwrap()
            .contains(GENERATED_HEADER));
        assert!(emitted
            .get("generated.rs")
            .unwrap()
            .contains("emit_fact_stream"));
    }

    pub(super) fn w5b_frontend_request_rejects_missing_closure_materiality() {
        let source = r#"
@import "tokens.bbnf" ;
@token ident ;
@ws /\s*/ ;
@pretty stylesheet block ;
root = "(" >> ident ?w , ")" ;
tag = "from" -> 0u8 | "paint" -> crate::paint(input): u32 ;
"#;

        assert!(matches!(
            emit_runtime_from_request(w5a_css_request(source)),
            Err(CodegenError::Lowering(message))
                if message.contains("frontend closure missing host capture")
        ));
    }

    pub(super) fn w5a_json_request_matches_emit_from_source() {
        let old = emit_from_source("json", JSON_GRAMMAR).unwrap();
        let request = RuntimeGenerationRequest {
            grammar_name: "json".to_string(),
            profile_id: "json".to_string(),
            entry_rule: "json".to_string(),
            source_roots: vec!["skinny/grammars/json.bbnf".to_string()],
            sources: vec![RuntimeGrammarSource {
                rel_path: "skinny/grammars/json.bbnf".to_string(),
                source: JSON_GRAMMAR.to_string(),
            }],
            workspace_metadata: w5a_metadata(),
            output_dir: "crates/runtime/src/grammars/json".to_string(),
            profile_contract: compiled_contract(),
        };
        let new = emit_runtime_from_request(request).unwrap();

        assert_eq!(old, new);
    }

    pub(super) fn w5a_sheets_bbnf_fail_closed_through_runtime_contract() {
        for grammar_name in ["google_sheets", "bbnf"] {
            let request = RuntimeGenerationRequest {
                grammar_name: grammar_name.to_string(),
                profile_id: grammar_name.to_string(),
                entry_rule: "root".to_string(),
                source_roots: vec![format!("grammar/{grammar_name}/root.bbnf")],
                sources: vec![RuntimeGrammarSource {
                    rel_path: format!("grammar/{grammar_name}/root.bbnf"),
                    source: "root = \"x\" -> 0u8 ;".to_string(),
                }],
                workspace_metadata: w5a_metadata(),
                output_dir: format!("crates/runtime/src/grammars/{grammar_name}"),
                profile_contract: request_facts_contract("css_l4_declaration_values"),
            };

            assert!(matches!(
                emit_runtime_from_request(request),
                Err(CodegenError::Lowering(message))
                    if message.contains("frontend closure missing import closure")
            ));
        }
    }

    pub(super) fn w5c_gen_rejects_profile_only_css_emission() {
        assert!(matches!(
            emit_runtime_profile("css_l4_declaration_values"),
            Err(CodegenError::Lowering(message))
                if message.contains("requires RuntimeGenerationRequest")
        ));
    }

    pub(super) fn w5c_gen_css_runtime_output_depends_on_frontend_source_hash() {
        let first =
            emit_runtime_from_request(w5c_css_request("css_l4_declaration_values", W5C_CSS_SOURCE))
                .unwrap();
        let changed = format!("{W5C_CSS_SOURCE}\nextra = ident ;\n");
        let second =
            emit_runtime_from_request(w5c_css_request("css_l4_declaration_values", &changed))
                .unwrap();

        assert_ne!(first.get("config.rs"), second.get("config.rs"));
        assert!(first
            .get("config.rs")
            .unwrap()
            .contains("FRONTEND_SOURCE_HASH"));
        assert!(second
            .get("config.rs")
            .unwrap()
            .contains("FRONTEND_SOURCE_HASH"));
        assert_eq!(first.get("generated.rs"), second.get("generated.rs"));
    }

    fn strip_direct_builds(expr: &mut BackendExpr) {
        match expr {
            BackendExpr::Entry(inner)
            | BackendExpr::OptionalBranch(inner)
            | BackendExpr::RepeatLoop { body: inner, .. } => strip_direct_builds(inner),
            BackendExpr::Seq(children)
            | BackendExpr::Alt {
                branches: children, ..
            } => {
                children.retain(|child| !matches!(child, BackendExpr::DirectBuild { .. }));
                for child in children {
                    strip_direct_builds(child);
                }
            }
            BackendExpr::ByteLiteral(_)
            | BackendExpr::RegexProgram { .. }
            | BackendExpr::CallRule { .. }
            | BackendExpr::SpanMark { .. }
            | BackendExpr::TapeEmit { .. }
            | BackendExpr::DirectBuild { .. }
            | BackendExpr::ValueProject { .. }
            | BackendExpr::Return => {}
        }
    }
}

#[cfg(test)]
#[test]
fn decision_spine_changes_generated_selection_fixture() {
    const JSON_GRAMMAR: &str = include_str!("../../../grammars/json.bbnf");

    let grammar = grammar::parse_grammar("json", JSON_GRAMMAR).unwrap();
    let output = passes::compile(&grammar).unwrap();
    let direct_lowered = lower::lower_to_rust(
        &output.backend_ir,
        &lower::LowerCtx {
            backend_shape: &output.layout_facts.backend_shape,
            cost_facts: &output.layout_facts.cost_facts,
            per_grammar_policy: &output.layout_facts.per_grammar_policy,
            same_substrate_union: &output.layout_facts.same_substrate_union,
            diagnostics: &output.diagnostics,
        },
    )
    .unwrap();

    let retained_plan = passes::recognizers::derive_backend_shape_with_diagnostics(
        &output.grammar,
        &output.backend_ir,
        &output.layout_facts,
        passes::recognizers::TargetFeatures {
            avx512bw: false,
            collapsed_stage_author_declared: false,
            direct_only_output: false,
            direct_build_consumer: false,
            retained_api_consumer: true,
        },
    );
    let retained_lowered = lower::lower_to_rust(
        &output.backend_ir,
        &lower::LowerCtx {
            backend_shape: &retained_plan.backend_shape,
            cost_facts: &retained_plan.cost_facts,
            per_grammar_policy: &retained_plan.per_grammar_policy,
            same_substrate_union: &retained_plan.same_substrate_union,
            diagnostics: &retained_plan.diagnostics,
        },
    )
    .unwrap();

    let object_id = output
        .backend_ir
        .rules
        .iter()
        .position(|rule| rule.name == "object")
        .map(RuleId)
        .expect("object rule");
    let direct_rule = direct_lowered
        .rule_plans
        .iter()
        .find(|rule| rule.rule == "object")
        .expect("direct object plan");
    let retained_rule = retained_lowered
        .rule_plans
        .iter()
        .find(|rule| rule.rule == "object")
        .expect("retained object plan");
    let direct_facts = output.layout_facts.cost_facts.get(&object_id).unwrap();
    let retained_facts = retained_plan.cost_facts.get(&object_id).unwrap();

    assert_eq!(direct_rule.shape, BackendShape::SinkOnly);
    assert_eq!(retained_rule.shape, BackendShape::OffsetTape);
    assert_ne!(direct_rule.body, retained_rule.body);
    assert!(
        direct_facts
            .active_cost
            .as_ref()
            .expect("direct active cost")
            .egraph_rewrite_count
            >= 1
    );
    assert_eq!(
        retained_facts
            .active_cost
            .as_ref()
            .expect("retained active cost")
            .egraph_rewrite_count,
        0
    );
}

#[cfg(test)]
#[test]
fn backend_lowerer_fixture_rejects_label_string_scaffold() {
    let rule = ir::BackendRule {
        name: "sample".to_string(),
        expr: ir::BackendExpr::Seq(vec![
            ir::BackendExpr::ByteLiteral(vec![b'a']),
            ir::BackendExpr::Return,
        ]),
    };

    let eager = lower::eager_tape::lower_rule(&rule);
    let offset = lower::offset_tape::lower_rule(&rule);

    assert!(!eager.contains("-> eager_tape"));
    assert!(!offset.contains("-> offset_tape"));
    assert!(eager.contains("runtime_plan::EagerTapeRule"));
    assert!(offset.contains("runtime_plan::OffsetTapeRule"));
    assert!(eager.contains("eager_match_literal_hex(61)"));
    assert!(offset.contains("offset_match_literal_hex(61)"));
}

#[cfg(test)]
#[test]
fn lower_eager_tape_emits_runtime_relevant_diff() {
    let source = r#"
root = "a" | "ab" ;
"#;
    let grammar = grammar::parse_grammar("root", source).unwrap();
    let output = passes::compile(&grammar).unwrap();
    let lowered = lower::lower_to_rust(
        &output.backend_ir,
        &lower::LowerCtx {
            backend_shape: &output.layout_facts.backend_shape,
            cost_facts: &output.layout_facts.cost_facts,
            per_grammar_policy: &output.layout_facts.per_grammar_policy,
            same_substrate_union: &output.layout_facts.same_substrate_union,
            diagnostics: &output.diagnostics,
        },
    )
    .unwrap();
    let root = lowered
        .rule_plans
        .iter()
        .find(|rule| rule.rule == "root")
        .expect("root plan");

    assert_eq!(root.shape, BackendShape::EagerTape);
    assert!(root.body.contains("runtime_plan::EagerTapeRule"));
    assert!(root.body.contains("alt_"));
    assert!(root.body.contains("eager_match_literal_hex(61)"));
    assert!(!root.body.contains("-> eager_tape"));
}

#[cfg(test)]
#[test]
fn lower_offset_tape_emits_runtime_relevant_diff() {
    let source = r#"
root = "a" "b" ;
"#;
    let grammar = grammar::parse_grammar("root", source).unwrap();
    let output = passes::compile(&grammar).unwrap();
    let lowered = lower::lower_to_rust(
        &output.backend_ir,
        &lower::LowerCtx {
            backend_shape: &output.layout_facts.backend_shape,
            cost_facts: &output.layout_facts.cost_facts,
            per_grammar_policy: &output.layout_facts.per_grammar_policy,
            same_substrate_union: &output.layout_facts.same_substrate_union,
            diagnostics: &output.diagnostics,
        },
    )
    .unwrap();
    let root = lowered
        .rule_plans
        .iter()
        .find(|rule| rule.rule == "root")
        .expect("root plan");

    assert_eq!(root.shape, BackendShape::OffsetTape);
    assert!(root.body.contains("runtime_plan::OffsetTapeRule"));
    assert!(root.body.contains("seq_begin"));
    assert!(root.body.contains("offset_match_literal_hex(61)"));
    assert!(root.body.contains("offset_match_literal_hex(62)"));
    assert!(!root.body.contains("-> offset_tape"));
}

#[cfg(test)]
#[test]
fn w5a_runtime_contract_consumes_source_and_metadata() {
    tests::w5a_runtime_contract_consumes_source_and_metadata();
}

#[cfg(test)]
#[test]
fn w5a_json_request_matches_emit_from_source() {
    tests::w5a_json_request_matches_emit_from_source();
}

#[cfg(test)]
#[test]
fn w5a_sheets_bbnf_fail_closed_through_runtime_contract() {
    tests::w5a_sheets_bbnf_fail_closed_through_runtime_contract();
}

#[cfg(test)]
#[test]
fn w5b_frontend_request_consumes_lowered_ir_before_provider_rendering() {
    tests::w5b_frontend_request_consumes_lowered_ir_before_provider_rendering();
}

#[cfg(test)]
#[test]
fn w5b_frontend_request_rejects_missing_closure_materiality() {
    tests::w5b_frontend_request_rejects_missing_closure_materiality();
}

#[cfg(test)]
#[test]
fn w5c_gen_rejects_profile_only_css_emission() {
    tests::w5c_gen_rejects_profile_only_css_emission();
}

#[cfg(test)]
#[test]
fn w5c_gen_css_runtime_output_depends_on_frontend_source_hash() {
    tests::w5c_gen_css_runtime_output_depends_on_frontend_source_hash();
}
