// @generated by xtask regen-css-pretty; do not edit by hand.
use crate::runtime::css_pretty::arena::CssPrettyCompoundId;
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CssPrettyValue<'p> {
    Span(&'p str),
    Unit,
    Compound(CssPrettyCompoundId),
}
impl<'p> Default for CssPrettyValue<'p> {
    fn default() -> Self {
        Self::Unit
    }
}
