export const PARSER_DESCRIPTIONS: Record<string, string> = {
    "BBNF AOT": "Compile-time codegen via #[derive(Parser)] from .bbnf grammar",
    "parse-that": "Hand-written combinator parser (parse_that crate / @mkbabb/parse-that)",
    "gorgeous": "Grammar-driven formatter generated from @pretty directives",
    "gorgeous (cached)": "gorgeous with pre-parsed AST reused across calls",
    "AOT": "Ahead-of-time compiled native Rust parser",
    "VM": "Bytecode interpreter for dynamically compiled grammars",
    "serde_json": "Rust derive-based JSON deserializer",
    "nom": "Rust function-based parser combinator library",
    "winnow": "Rust streaming parser combinator (nom successor)",
    "pest": "Rust PEG parser generator",
    "sonic-rs": "SIMD-accelerated JSON parser (Rust)",
    "simd-json": "SIMD-accelerated JSON parser based on simdjson",
    "jiter": "Iterator-based JSON parser (Rust)",
    "serde_json_borrow": "Zero-copy JSON parser using borrowed references",
    "cssparser": "Mozilla's CSS parsing library (Servo/Firefox)",
    "lightningcss": "Parcel's CSS parser built on cssparser",
    "Biome": "Rome-derived JS/TS/CSS formatter and linter",
    "JSON.parse": "V8 native JSON parser (C++ implementation)",
    "Chevrotain": "TypeScript lexer + parser toolkit",
    "Peggy": "PEG parser generator for JavaScript",
    "Parsimmon": "Monadic parser combinator library for JS",
    "Nearley+moo": "Earley parser with moo lexer for JS",
};
