// @generated by xtask regen-ebnf; do not edit by hand.
use bbnf_ir::registry::StructLayout;
use crate::runtime::ebnf::value::EbnfValue;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EbnfCompoundKind {
    Letter,
    Digit,
    Symbol,
    Character,
    Identifier,
    S,
    Terminal,
    Terminator,
    Term,
    Factor,
    Concatenation,
    Alternation,
    Rhs,
    Lhs,
    Rule,
    Grammar,
    Other,
}
impl EbnfCompoundKind {
    pub fn from_layout(layout: &StructLayout) -> Self {
        match layout.rule_id {
            0 => Self::Letter,
            2 => Self::Symbol,
            3 => Self::Identifier,
            4 => Self::Character,
            6 => Self::Concatenation,
            7 => Self::Alternation,
            9 => Self::Term,
            10 => Self::Factor,
            11 => Self::Rule,
            12 => Self::Grammar,
            _ => Self::Other,
        }
    }
}
#[derive(Debug, Clone)]
pub struct EbnfCompound<'p> {
    pub kind: EbnfCompoundKind,
    pub branch_tag: Option<u32>,
    pub children: Vec<EbnfValue<'p>>,
}
impl<'p> Default for EbnfCompound<'p> {
    fn default() -> Self {
        Self {
            kind: EbnfCompoundKind::Other,
            branch_tag: None,
            children: Vec::new(),
        }
    }
}
