// @generated by xtask regen-json; do not edit by hand.
use crate::runtime::json::value::{JsonPair, JsonValue};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct JsonArrayId(u32);
impl JsonArrayId {
    pub const EMPTY: Self = Self(0);
    #[inline]
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }
    #[inline]
    fn slab_index(self) -> Option<usize> {
        if self.0 == 0 { None } else { Some((self.0 - 1) as usize) }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct JsonObjectId(u32);
impl JsonObjectId {
    pub const EMPTY: Self = Self(0);
    #[inline]
    pub const fn is_empty(self) -> bool {
        self.0 == 0
    }
    #[inline]
    fn slab_index(self) -> Option<usize> {
        if self.0 == 0 { None } else { Some((self.0 - 1) as usize) }
    }
}
#[derive(Debug, Default)]
pub struct JsonArena<'p> {
    arrays: Vec<Vec<JsonValue<'p>>>,
    objects: Vec<Vec<JsonPair<'p>>>,
}
impl<'p> JsonArena<'p> {
    #[inline]
    pub fn new() -> Self {
        Self::default()
    }
    #[inline]
    pub fn with_capacity(arrays: usize, objects: usize) -> Self {
        Self {
            arrays: Vec::with_capacity(arrays),
            objects: Vec::with_capacity(objects),
        }
    }
    #[inline]
    pub fn push_array(&mut self, items: Vec<JsonValue<'p>>) -> JsonArrayId {
        if items.is_empty() {
            return JsonArrayId::EMPTY;
        }
        self.arrays.push(items);
        JsonArrayId(self.arrays.len() as u32)
    }
    #[inline]
    pub fn push_object(&mut self, pairs: Vec<JsonPair<'p>>) -> JsonObjectId {
        if pairs.is_empty() {
            return JsonObjectId::EMPTY;
        }
        self.objects.push(pairs);
        JsonObjectId(self.objects.len() as u32)
    }
    #[inline]
    pub fn array(&self, id: JsonArrayId) -> &[JsonValue<'p>] {
        match id.slab_index() {
            None => &[],
            Some(i) => self.arrays[i].as_slice(),
        }
    }
    #[inline]
    pub fn object(&self, id: JsonObjectId) -> &[JsonPair<'p>] {
        match id.slab_index() {
            None => &[],
            Some(i) => self.objects[i].as_slice(),
        }
    }
    #[inline]
    pub fn array_count(&self) -> usize {
        self.arrays.len()
    }
    #[inline]
    pub fn object_count(&self) -> usize {
        self.objects.len()
    }
    #[inline]
    pub fn truncate(&mut self, arrays: usize, objects: usize) {
        self.arrays.truncate(arrays);
        self.objects.truncate(objects);
    }
}
