// @generated by xtask regen-json; do not edit by hand.
use crate::runtime::RuntimeView;
use crate::runtime::json::document::{JsonKind, JsonView};
use crate::runtime::json::value::JsonValue;
impl<'a, 'p: 'a> RuntimeView<'p> for JsonView<'a, 'p> {
    type Kind = JsonKind;
    #[inline]
    fn kind(&self) -> Self::Kind {
        match self.focus {
            JsonValue::Null => JsonKind::Null,
            JsonValue::Bool(_) => JsonKind::Bool,
            JsonValue::Number(_) => JsonKind::Number,
            JsonValue::String(_) => JsonKind::String,
            JsonValue::Array(_) => JsonKind::Array,
            JsonValue::Object(_) => JsonKind::Object,
        }
    }
    #[inline]
    fn span(&self) -> Option<&'p str> {
        match self.focus {
            JsonValue::String(s) => Some(s),
            _ => None,
        }
    }
    #[inline]
    fn input(&self) -> &'p str {
        self.doc.input
    }
    fn children(&self) -> impl Iterator<Item = Self> + '_ {
        let doc = self.doc;
        let focus = self.focus;
        JsonChildrenIter {
            doc,
            focus,
            index: 0,
        }
    }
}
pub struct JsonChildrenIter<'a, 'p: 'a> {
    doc: &'a crate::runtime::json::JsonDocument<'p>,
    focus: JsonValue<'p>,
    index: usize,
}
impl<'a, 'p: 'a> Iterator for JsonChildrenIter<'a, 'p> {
    type Item = JsonView<'a, 'p>;
    fn next(&mut self) -> Option<Self::Item> {
        match self.focus {
            JsonValue::Array(id) => {
                let items = self.doc.array(id);
                let item = items.get(self.index)?;
                self.index += 1;
                Some(JsonView::focused(self.doc, *item))
            }
            JsonValue::Object(id) => {
                let pairs = self.doc.object(id);
                let pair = pairs.get(self.index)?;
                self.index += 1;
                Some(JsonView::focused(self.doc, pair.value))
            }
            _ => None,
        }
    }
}
