// @generated by xtask regen-google-sheets; do not edit by hand.
use bbnf_ir::registry::StructLayout;
use crate::runtime::builder::StructBuilder;
use crate::runtime::handle::CompoundHandle;
use crate::runtime::google_sheets::arena::{SheetsArena, SheetsCompoundKind};
use crate::runtime::google_sheets::document::SheetsDocument;
use crate::runtime::google_sheets::value::SheetsValue;
#[derive(Debug, Clone, Copy)]
struct Frame {
    kind: SheetsCompoundKind,
    children_base: usize,
    #[allow(dead_code)]
    handle_token: u64,
}
#[derive(Debug)]
pub struct SheetsStructBuilder<'p> {
    arena: SheetsArena<'p>,
    stack: Vec<Frame>,
    pending_children: Vec<SheetsValue<'p>>,
    root: Option<SheetsValue<'p>>,
    next_handle: u64,
}
#[derive(Debug, Clone)]
pub struct SheetsStructCheckpoint<'p> {
    compounds: usize,
    stack: Vec<Frame>,
    root: Option<SheetsValue<'p>>,
    next_handle: u64,
    pending_children_len: usize,
}
impl<'p> Default for SheetsStructBuilder<'p> {
    fn default() -> Self {
        Self::new()
    }
}
impl<'p> SheetsStructBuilder<'p> {
    #[inline]
    pub fn new() -> Self {
        Self {
            arena: SheetsArena::new(),
            stack: Vec::with_capacity(8),
            pending_children: Vec::with_capacity(32),
            root: None,
            next_handle: 0,
        }
    }
    #[inline]
    pub fn with_capacity(compounds: usize) -> Self {
        Self {
            arena: SheetsArena::with_capacity(compounds),
            stack: Vec::with_capacity(8),
            pending_children: Vec::with_capacity(32),
            root: None,
            next_handle: 0,
        }
    }
    #[inline]
    pub fn finalise(mut self, input: &'p str) -> SheetsDocument<'p> {
        debug_assert!(
            self.stack.is_empty(),
            "SheetsStructBuilder::finalise called with open frames"
        );
        let root = self
            .root
            .take()
            .expect("SheetsStructBuilder::finalise called before value emission");
        SheetsDocument::new(self.arena, root, input)
    }
    #[inline]
    fn deposit(&mut self, value: SheetsValue<'p>) {
        if self.stack.is_empty() {
            self.root = Some(value);
        } else {
            self.pending_children.push(value);
        }
    }
}
impl<'p> StructBuilder for SheetsStructBuilder<'p> {
    type Checkpoint = SheetsStructCheckpoint<'p>;
    #[inline]
    fn checkpoint(&self) -> Self::Checkpoint {
        SheetsStructCheckpoint {
            compounds: self.arena.compound_count(),
            stack: self.stack.clone(),
            root: self.root,
            next_handle: self.next_handle,
            pending_children_len: self.pending_children.len(),
        }
    }
    #[inline]
    fn rollback(&mut self, checkpoint: Self::Checkpoint) {
        self.arena.truncate(checkpoint.compounds);
        self.stack = checkpoint.stack;
        self.root = checkpoint.root;
        self.next_handle = checkpoint.next_handle;
        self.pending_children.truncate(checkpoint.pending_children_len);
    }
    fn begin_compound(&mut self, layout: &StructLayout) -> CompoundHandle {
        let kind = SheetsCompoundKind::from_layout(layout);
        self.next_handle = self.next_handle.wrapping_add(1);
        let handle_token = self.next_handle;
        self.stack
            .push(Frame {
                kind,
                children_base: self.pending_children.len(),
                handle_token,
            });
        CompoundHandle::new(handle_token, 0)
    }
    fn end_compound(&mut self, _handle: CompoundHandle) {
        let frame = self
            .stack
            .pop()
            .expect("SheetsStructBuilder::end_compound on empty stack");
        let children: Vec<SheetsValue<'p>> = self
            .pending_children
            .split_off(frame.children_base);
        let value = if frame.kind.is_transparent_wrap() && children.len() == 1 {
            children[0]
        } else {
            let id = self.arena.push_compound(frame.kind, children);
            SheetsValue::Compound(id)
        };
        self.deposit(value);
    }
    #[inline]
    fn push_leaf_with_f64(&mut self, value: f64) {
        self.deposit(SheetsValue::Number(value));
    }
    #[inline]
    fn push_leaf_with_i64(&mut self, value: i64) {
        self.deposit(SheetsValue::Number(value as f64));
    }
    #[inline]
    fn push_leaf_with_u64(&mut self, value: u64) {
        self.deposit(SheetsValue::Number(value as f64));
    }
    #[inline]
    fn push_leaf_with_bool(&mut self, value: bool) {
        self.deposit(SheetsValue::Bool(value));
    }
    #[inline]
    fn push_leaf_with_str(&mut self, value: &str) {
        let extended: &'p str = unsafe { core::mem::transmute(value) };
        self.deposit(SheetsValue::String(extended));
    }
    #[inline]
    fn push_leaf_with_unit(&mut self) {
        self.deposit(SheetsValue::Tag(0));
    }
    #[inline]
    fn push_branch_tag(&mut self, branch_index: u32) {
        debug_assert!(branch_index < 256);
        self.deposit(SheetsValue::Tag(branch_index as u8));
    }
}
impl<'p> SheetsStructBuilder<'p> {
    #[inline]
    pub fn push_leaf_cell_ref(&mut self, value: &str) {
        let extended: &'p str = unsafe { core::mem::transmute(value) };
        self.deposit(SheetsValue::CellRef(extended));
    }
    #[inline]
    pub fn push_leaf_identifier(&mut self, value: &str) {
        let extended: &'p str = unsafe { core::mem::transmute(value) };
        self.deposit(SheetsValue::Identifier(extended));
    }
    #[inline]
    pub fn push_leaf_sheet_prefix(&mut self, tag: u8, value: &str) {
        let extended: &'p str = unsafe { core::mem::transmute(value) };
        self.deposit(SheetsValue::SheetPrefix {
            tag,
            text: extended,
        });
    }
    #[inline]
    pub fn push_leaf_error(&mut self, value: u8) {
        self.deposit(SheetsValue::Error(value));
    }
}
