// @generated by xtask regen-google-sheets; do not edit by hand.
use super::document::{SheetsDocument, SheetsPathQuery};
use crate::grammar::generated::google_sheets::{
    __path_plan, __shape_support_GoogleSheetsParser, parse_GoogleSheetsParser_formula,
};
use crate::path::cursor::Decision;
use crate::path::executor::PathExecutor;
use crate::path::ir::{PathSegment as TypedSegment, TypedPath};
use crate::path::markers::Sheets;
use crate::runtime::google_sheets::SheetsStructBuilder;
use crate::runtime::path::{Path, PathSegment};
fn lower<'a>(seg: &TypedSegment<'a>) -> Option<PathSegment<'a>> {
    match seg {
        TypedSegment::Field(s) => Some(PathSegment::Field(s)),
        TypedSegment::Index(i) => Some(PathSegment::Index(*i)),
        TypedSegment::VariantName(s) => Some(PathSegment::Field(s)),
        TypedSegment::Wildcard => None,
    }
}
pub fn parse_with<T>(input: &str, path: &TypedPath<Sheets, T>) -> Option<T>
where
    T: SheetsPathQuery,
{
    PathExecutor::execute(
        input,
        path,
        |rule_id, kind, _idx| {
            __path_plan::lookup(rule_id, kind)
                .map(|e| e.decision)
                .unwrap_or(Decision::ParseFully)
        },
        |src, cursor| {
            let mut state = __shape_support_GoogleSheetsParser::ScanState::new();
            let mut builder = SheetsStructBuilder::new();
            let mut pos: usize = 0;
            parse_GoogleSheetsParser_formula(
                    src.as_bytes(),
                    &mut pos,
                    &mut state,
                    &mut builder,
                    cursor,
                )
                .ok()?;
            let doc: SheetsDocument<'_> = builder.finalise(src);
            let mut segments: Vec<PathSegment<'_>> = Vec::with_capacity(path.len());
            for owned in path.owned_segments() {
                segments.push(lower(&owned.as_borrowed())?);
            }
            doc.get::<T>(Path::new(&segments))
        },
    )
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::path::ir::OwnedPathSegment;
    #[test]
    #[ignore = "Flat-shape lazy honoring: formula is a flat compound."]
    fn parse_with_resolves_number_leaf() {
        let src = "=42";
        let path: TypedPath<Sheets, f64> = TypedPath::from_owned(
            vec![OwnedPathSegment::Index(0), OwnedPathSegment::Index(0)],
        );
        let lazy = parse_with::<f64>(src, &path);
        assert_eq!(lazy, Some(42.0));
    }
    #[test]
    fn parse_with_returns_none_on_invalid_input() {
        let path: TypedPath<Sheets, f64> = TypedPath::from_owned(Vec::new());
        let out = parse_with::<f64>("not a formula @@@", &path);
        assert!(out.is_none());
    }
}
