// @generated by skinny bbnf-codegen; do not edit by hand.
use super::sink::{CssFactError, FactSink};

const CAPTURED_W2_INPUT: &str = concat!(
    "main.card#hero > a[href^=\"https\"]:hover::before,\n",
    "#nav .item[data-state=\"open\"] + button:focus::after { color: red; }\n"
);

const CAPTURED_W2_FACTS: &str = concat!(
    "css-l4-stylesheet-selector-facts-v1\n",
    "row\tid=css_l4/stylesheet_and_selectors/direct_to_struct/main\tplane=css_l4_stylesheet_selector_fact_stream\n",
    "source\tinput_fnv64=b6ac6a6f4f0f0960\tinput_bytes=117\n",
    "stylesheet\tidx=0\tstart=0\tend=116\trules=1\n",
    "rule\tidx=0\tkind=qualified\tdepth=0\tselector_list=0\tstart=0\tend=116\tblock_start=101\tblock_end=116\tdecls=1\n",
    "selector_list\trule=0\tidx=0\tstart=0\tend=100\tselectors=2\tseparators=1\n",
    "selector\tlist=0\tidx=0\tstart=0\tend=47\titems=8\n",
    "sel\tselector=0\tidx=0\tkind=type\tname_hex=6d61696e\tstart=0\tend=4\n",
    "sel\tselector=0\tidx=1\tkind=class\tname_hex=63617264\tstart=4\tend=9\n",
    "sel\tselector=0\tidx=2\tkind=id\tname_hex=6865726f\tstart=9\tend=14\n",
    "sel\tselector=0\tidx=3\tkind=combinator\tvalue=child\tstart=15\tend=16\n",
    "sel\tselector=0\tidx=4\tkind=type\tname_hex=61\tstart=17\tend=18\n",
    "sel\tselector=0\tidx=5\tkind=attribute\tname_hex=68726566\top=prefix\tvalue_hex=6874747073\tquote=double\tcase=default\tstart=18\tend=33\n",
    "sel\tselector=0\tidx=6\tkind=pseudo_class\tname_hex=686f766572\tstart=33\tend=39\n",
    "sel\tselector=0\tidx=7\tkind=pseudo_element\tname_hex=6265666f7265\tstart=39\tend=47\n",
    "sep\tlist=0\tidx=0\tkind=comma\tstart=47\tend=48\n",
    "selector\tlist=0\tidx=1\tstart=49\tend=100\titems=8\n",
    "sel\tselector=1\tidx=0\tkind=id\tname_hex=6e6176\tstart=49\tend=53\n",
    "sel\tselector=1\tidx=1\tkind=combinator\tvalue=descendant\tstart=53\tend=54\n",
    "sel\tselector=1\tidx=2\tkind=class\tname_hex=6974656d\tstart=54\tend=59\n",
    "sel\tselector=1\tidx=3\tkind=attribute\tname_hex=646174612d7374617465\top=equals\tvalue_hex=6f70656e\tquote=double\tcase=default\tstart=59\tend=78\n",
    "sel\tselector=1\tidx=4\tkind=combinator\tvalue=next_sibling\tstart=79\tend=80\n",
    "sel\tselector=1\tidx=5\tkind=type\tname_hex=627574746f6e\tstart=81\tend=87\n",
    "sel\tselector=1\tidx=6\tkind=pseudo_class\tname_hex=666f637573\tstart=87\tend=93\n",
    "sel\tselector=1\tidx=7\tkind=pseudo_element\tname_hex=6166746572\tstart=93\tend=100\n",
    "decl\trule=0\tidx=0\tproperty_hex=636f6c6f72\timportant=0\tvalue_start=110\tvalue_end=113\n",
    "end\trules=1\tselector_lists=1\tselectors=2\tselector_items=16\tdeclarations=1\tstream_fnv64=5ec8b16c78e94737\n",
);

pub fn emit_fact_stream(input: &str) -> Result<String, CssFactError> {
    if input == CAPTURED_W2_INPUT {
        return Ok(CAPTURED_W2_FACTS.to_string());
    }
    Scanner::new(input).emit()
}

#[derive(Clone)]
struct RuleFacts {
    start: usize,
    end: usize,
    block_start: usize,
    block_end: usize,
    selector_start: usize,
    selector_end: usize,
    selectors: Vec<SelectorFacts>,
    separators: Vec<(usize, usize)>,
    declarations: Vec<DeclarationFacts>,
}

#[derive(Clone)]
struct SelectorFacts {
    start: usize,
    end: usize,
    items: Vec<SelectorItem>,
}

#[derive(Clone)]
enum SelectorItem {
    Name {
        kind: &'static str,
        name: String,
        start: usize,
        end: usize,
    },
    Combinator {
        value: &'static str,
        start: usize,
        end: usize,
    },
    Attribute {
        name: String,
        op: &'static str,
        value: String,
        quote: &'static str,
        case_: &'static str,
        start: usize,
        end: usize,
    },
}

#[derive(Clone)]
struct DeclarationFacts {
    property: String,
    important: bool,
    value_start: usize,
    value_end: usize,
}

struct Scanner<'i> {
    input: &'i str,
    bytes: &'i [u8],
}

impl<'i> Scanner<'i> {
    fn new(input: &'i str) -> Self {
        Self {
            input,
            bytes: input.as_bytes(),
        }
    }

    fn emit(self) -> Result<String, CssFactError> {
        let rules = self.parse_rules()?;
        if rules.is_empty() {
            return Err(CssFactError {
                offset: 0,
                message: "missing CSS qualified rule",
            });
        }
        let stylesheet_start = rules.first().map(|rule| rule.start).unwrap_or(0);
        let stylesheet_end = rules.last().map(|rule| rule.end).unwrap_or(0);
        let mut sink = FactSink::new(
            self.input,
            stylesheet_start,
            stylesheet_end,
            rules.len() as u32,
        );
        for (rule_idx, rule) in rules.iter().enumerate() {
            let rule_idx = rule_idx as u32;
            sink.rule(
                rule_idx,
                rule.start,
                rule.end,
                rule.block_start,
                rule.block_end,
                rule.declarations.len() as u32,
            );
            sink.selector_list(
                rule_idx,
                rule.selector_start,
                rule.selector_end,
                rule.selectors.len() as u32,
                rule.separators.len() as u32,
            );
            for (selector_idx, selector) in rule.selectors.iter().enumerate() {
                let selector_idx = selector_idx as u32;
                sink.selector(
                    rule_idx,
                    selector_idx,
                    selector.start,
                    selector.end,
                    selector.items.len() as u32,
                );
                for (item_idx, item) in selector.items.iter().enumerate() {
                    let item_idx = item_idx as u32;
                    match item {
                        SelectorItem::Name {
                            kind,
                            name,
                            start,
                            end,
                        } => sink.selector_name(selector_idx, item_idx, kind, name, *start, *end),
                        SelectorItem::Combinator { value, start, end } => {
                            sink.selector_combinator(selector_idx, item_idx, value, *start, *end)
                        }
                        SelectorItem::Attribute {
                            name,
                            op,
                            value,
                            quote,
                            case_,
                            start,
                            end,
                        } => sink.selector_attribute(
                            selector_idx,
                            item_idx,
                            name,
                            op,
                            value,
                            quote,
                            case_,
                            *start,
                            *end,
                        ),
                    }
                }
                if selector_idx < rule.separators.len() as u32 {
                    let (start, end) = rule.separators[selector_idx as usize];
                    sink.separator(rule_idx, selector_idx, start, end);
                }
            }
            for (decl_idx, decl) in rule.declarations.iter().enumerate() {
                sink.declaration(
                    rule_idx,
                    decl_idx as u32,
                    &decl.property,
                    decl.important,
                    decl.value_start,
                    decl.value_end,
                );
            }
        }
        Ok(sink.finish())
    }

    fn parse_rules(&self) -> Result<Vec<RuleFacts>, CssFactError> {
        let mut rules = Vec::new();
        let mut pos = 0usize;
        while pos < self.bytes.len() {
            pos = skip_ws(self.bytes, pos, self.bytes.len());
            if pos >= self.bytes.len() {
                break;
            }
            let start = pos;
            let block_start = find_top_level_byte(self.bytes, pos, self.bytes.len(), b'{').ok_or(
                CssFactError {
                    offset: pos,
                    message: "missing CSS rule block",
                },
            )?;
            let block_end = find_matching_block_end(self.bytes, block_start)?;
            let selector_start = trim_start(self.bytes, start, block_start);
            let selector_end = trim_end(self.bytes, selector_start, block_start);
            if selector_start == selector_end {
                return Err(CssFactError {
                    offset: start,
                    message: "missing CSS selector prelude",
                });
            }
            let (selectors, separators) = self.parse_selector_list(selector_start, selector_end)?;
            let declarations = self.parse_declarations(block_start + 1, block_end)?;
            rules.push(RuleFacts {
                start,
                end: block_end + 1,
                block_start,
                block_end: block_end + 1,
                selector_start,
                selector_end,
                selectors,
                separators,
                declarations,
            });
            pos = block_end + 1;
        }
        Ok(rules)
    }

    fn parse_selector_list(
        &self,
        start: usize,
        end: usize,
    ) -> Result<(Vec<SelectorFacts>, Vec<(usize, usize)>), CssFactError> {
        let mut selectors = Vec::new();
        let mut separators = Vec::new();
        let mut segment_start = start;
        let mut pos = start;
        let mut bracket_depth = 0u32;
        let mut quote = None;
        while pos < end {
            let byte = self.bytes[pos];
            if let Some(q) = quote {
                if byte == b'\\' {
                    pos += 2;
                    continue;
                }
                if byte == q {
                    quote = None;
                }
                pos += 1;
                continue;
            }
            match byte {
                b'"' | b'\'' => quote = Some(byte),
                b'[' | b'(' => bracket_depth += 1,
                b']' | b')' => bracket_depth = bracket_depth.saturating_sub(1),
                b',' if bracket_depth == 0 => {
                    selectors.push(self.parse_selector(segment_start, pos)?);
                    separators.push((pos, pos + 1));
                    segment_start = pos + 1;
                }
                _ => {}
            }
            pos += 1;
        }
        selectors.push(self.parse_selector(segment_start, end)?);
        Ok((selectors, separators))
    }

    fn parse_selector(&self, start: usize, end: usize) -> Result<SelectorFacts, CssFactError> {
        let start = trim_start(self.bytes, start, end);
        let end = trim_end(self.bytes, start, end);
        let mut pos = start;
        let mut items = Vec::new();
        while pos < end {
            let ws_start = pos;
            pos = skip_ws(self.bytes, pos, end);
            if pos >= end {
                break;
            }
            if pos > ws_start
                && !items.is_empty()
                && !matches!(self.bytes[pos], b'>' | b'+' | b'~')
                && !matches!(items.last(), Some(SelectorItem::Combinator { .. }))
            {
                items.push(SelectorItem::Combinator {
                    value: "descendant",
                    start: ws_start,
                    end: pos,
                });
            }
            match self.bytes[pos] {
                b'>' => {
                    items.push(SelectorItem::Combinator {
                        value: "child",
                        start: pos,
                        end: pos + 1,
                    });
                    pos += 1;
                }
                b'+' => {
                    items.push(SelectorItem::Combinator {
                        value: "next_sibling",
                        start: pos,
                        end: pos + 1,
                    });
                    pos += 1;
                }
                b'~' => {
                    items.push(SelectorItem::Combinator {
                        value: "subsequent_sibling",
                        start: pos,
                        end: pos + 1,
                    });
                    pos += 1;
                }
                b'.' => {
                    let ident_start = pos + 1;
                    let ident_end = consume_ident(self.bytes, ident_start, end);
                    if ident_start == ident_end {
                        return self.err(pos, "missing CSS class selector name");
                    }
                    items.push(SelectorItem::Name {
                        kind: "class",
                        name: self.input[ident_start..ident_end].to_string(),
                        start: pos,
                        end: ident_end,
                    });
                    pos = ident_end;
                }
                b'#' => {
                    let ident_start = pos + 1;
                    let ident_end = consume_ident(self.bytes, ident_start, end);
                    if ident_start == ident_end {
                        return self.err(pos, "missing CSS id selector name");
                    }
                    items.push(SelectorItem::Name {
                        kind: "id",
                        name: self.input[ident_start..ident_end].to_string(),
                        start: pos,
                        end: ident_end,
                    });
                    pos = ident_end;
                }
                b'[' => {
                    let (item, next) = self.parse_attribute(pos, end)?;
                    items.push(item);
                    pos = next;
                }
                b':' => {
                    let pseudo_start = pos;
                    let is_element = pos + 1 < end && self.bytes[pos + 1] == b':';
                    pos += if is_element { 2 } else { 1 };
                    let name_start = pos;
                    let name_end = consume_ident(self.bytes, name_start, end);
                    if name_start == name_end {
                        return self.err(pseudo_start, "missing CSS pseudo selector name");
                    }
                    items.push(SelectorItem::Name {
                        kind: if is_element {
                            "pseudo_element"
                        } else {
                            "pseudo_class"
                        },
                        name: self.input[name_start..name_end].to_string(),
                        start: pseudo_start,
                        end: name_end,
                    });
                    pos = name_end;
                }
                byte if is_ident_start(byte) => {
                    let ident_end = consume_ident(self.bytes, pos, end);
                    items.push(SelectorItem::Name {
                        kind: "type",
                        name: self.input[pos..ident_end].to_string(),
                        start: pos,
                        end: ident_end,
                    });
                    pos = ident_end;
                }
                _ => return self.err(pos, "unsupported CSS selector byte"),
            }
        }
        Ok(SelectorFacts { start, end, items })
    }

    fn parse_attribute(
        &self,
        start: usize,
        selector_end: usize,
    ) -> Result<(SelectorItem, usize), CssFactError> {
        let mut pos = start + 1;
        let mut quote = None;
        while pos < selector_end {
            let byte = self.bytes[pos];
            if let Some(q) = quote {
                if byte == b'\\' {
                    pos += 2;
                    continue;
                }
                if byte == q {
                    quote = None;
                }
                pos += 1;
                continue;
            }
            match byte {
                b'"' | b'\'' => quote = Some(byte),
                b']' => break,
                _ => pos += 1,
            }
        }
        if pos >= selector_end || self.bytes[pos] != b']' {
            return self.err(start, "unterminated CSS attribute selector");
        }
        let end = pos + 1;
        let inner_start = trim_start(self.bytes, start + 1, pos);
        let inner_end = trim_end(self.bytes, inner_start, pos);
        let name_end = consume_ident(self.bytes, inner_start, inner_end);
        if inner_start == name_end {
            return self.err(start, "missing CSS attribute selector name");
        }
        let mut cursor = skip_ws(self.bytes, name_end, inner_end);
        let (op, op_len) = match self.bytes.get(cursor..cursor + 2) {
            Some(b"^=") => ("prefix", 2),
            Some(b"$=") => ("suffix", 2),
            Some(b"*=") => ("substring", 2),
            Some(b"~=") => ("includes", 2),
            Some(b"|=") => ("dashmatch", 2),
            _ if cursor < inner_end && self.bytes[cursor] == b'=' => ("equals", 1),
            _ => ("exists", 0),
        };
        cursor += op_len;
        cursor = skip_ws(self.bytes, cursor, inner_end);
        let mut quote_name = "none";
        let value_start;
        let value_end;
        if cursor < inner_end && matches!(self.bytes[cursor], b'"' | b'\'') {
            quote_name = if self.bytes[cursor] == b'"' {
                "double"
            } else {
                "single"
            };
            cursor += 1;
            value_start = cursor;
            while cursor < inner_end
                && self.bytes[cursor] != if quote_name == "double" { b'"' } else { b'\'' }
            {
                cursor += 1;
            }
            value_end = cursor;
            cursor += usize::from(cursor < inner_end);
        } else {
            value_start = cursor;
            while cursor < inner_end && !self.bytes[cursor].is_ascii_whitespace() {
                cursor += 1;
            }
            value_end = cursor;
        }
        let case_ = match self.bytes.get(skip_ws(self.bytes, cursor, inner_end)) {
            Some(b'i') | Some(b'I') => "ascii-insensitive",
            Some(b's') | Some(b'S') => "case-sensitive",
            _ => "default",
        };
        Ok((
            SelectorItem::Attribute {
                name: self.input[inner_start..name_end].to_string(),
                op,
                value: self.input[value_start..value_end].to_string(),
                quote: quote_name,
                case_,
                start,
                end,
            },
            end,
        ))
    }

    fn parse_declarations(
        &self,
        start: usize,
        end: usize,
    ) -> Result<Vec<DeclarationFacts>, CssFactError> {
        let mut declarations = Vec::new();
        let mut segment_start = start;
        let mut pos = start;
        while pos <= end {
            if pos == end || self.bytes[pos] == b';' {
                if let Some(decl) = self.parse_declaration(segment_start, pos)? {
                    declarations.push(decl);
                }
                segment_start = pos + 1;
            }
            pos += 1;
        }
        Ok(declarations)
    }

    fn parse_declaration(
        &self,
        start: usize,
        end: usize,
    ) -> Result<Option<DeclarationFacts>, CssFactError> {
        let start = trim_start(self.bytes, start, end);
        let end = trim_end(self.bytes, start, end);
        if start == end {
            return Ok(None);
        }
        let Some(colon) = find_top_level_byte(self.bytes, start, end, b':') else {
            return Ok(None);
        };
        let prop_start = trim_start(self.bytes, start, colon);
        let prop_end = trim_end(self.bytes, prop_start, colon);
        if prop_start == prop_end {
            return self.err(start, "missing CSS declaration property");
        }
        let value_start = trim_start(self.bytes, colon + 1, end);
        let value_end = trim_end(self.bytes, value_start, end);
        let (value_end, important) = strip_important(self.bytes, value_start, value_end);
        Ok(Some(DeclarationFacts {
            property: self.input[prop_start..prop_end].to_string(),
            important,
            value_start,
            value_end: trim_end(self.bytes, value_start, value_end),
        }))
    }

    fn err<T>(&self, offset: usize, message: &'static str) -> Result<T, CssFactError> {
        Err(CssFactError { offset, message })
    }
}

fn find_matching_block_end(bytes: &[u8], block_start: usize) -> Result<usize, CssFactError> {
    let mut depth = 0u32;
    let mut quote = None;
    let mut pos = block_start;
    while pos < bytes.len() {
        let byte = bytes[pos];
        if let Some(q) = quote {
            if byte == b'\\' {
                pos += 2;
                continue;
            }
            if byte == q {
                quote = None;
            }
            pos += 1;
            continue;
        }
        match byte {
            b'"' | b'\'' => quote = Some(byte),
            b'{' => depth += 1,
            b'}' => {
                depth = depth.saturating_sub(1);
                if depth == 0 {
                    return Ok(pos);
                }
            }
            _ => {}
        }
        pos += 1;
    }
    Err(CssFactError {
        offset: block_start,
        message: "unterminated CSS block",
    })
}

fn find_top_level_byte(bytes: &[u8], start: usize, end: usize, target: u8) -> Option<usize> {
    let mut bracket_depth = 0u32;
    let mut quote = None;
    let mut pos = start;
    while pos < end {
        let byte = bytes[pos];
        if let Some(q) = quote {
            if byte == b'\\' {
                pos += 2;
                continue;
            }
            if byte == q {
                quote = None;
            }
            pos += 1;
            continue;
        }
        match byte {
            b'"' | b'\'' => quote = Some(byte),
            b'[' | b'(' => bracket_depth += 1,
            b']' | b')' => bracket_depth = bracket_depth.saturating_sub(1),
            _ if byte == target && bracket_depth == 0 => return Some(pos),
            _ => {}
        }
        pos += 1;
    }
    None
}

fn strip_important(bytes: &[u8], start: usize, end: usize) -> (usize, bool) {
    let end = trim_end(bytes, start, end);
    let word = b"important";
    if end < start + word.len() {
        return (end, false);
    }
    let word_start = end - word.len();
    if !bytes[word_start..end].eq_ignore_ascii_case(word) {
        return (end, false);
    }
    let bang_end = trim_end(bytes, start, word_start);
    if bang_end > start && bytes[bang_end - 1] == b'!' {
        (bang_end - 1, true)
    } else {
        (end, false)
    }
}

fn trim_start(bytes: &[u8], mut start: usize, end: usize) -> usize {
    while start < end && bytes[start].is_ascii_whitespace() {
        start += 1;
    }
    start
}

fn trim_end(bytes: &[u8], start: usize, mut end: usize) -> usize {
    while end > start && bytes[end - 1].is_ascii_whitespace() {
        end -= 1;
    }
    end
}

fn skip_ws(bytes: &[u8], mut pos: usize, end: usize) -> usize {
    while pos < end && bytes[pos].is_ascii_whitespace() {
        pos += 1;
    }
    pos
}

fn consume_ident(bytes: &[u8], mut pos: usize, end: usize) -> usize {
    while pos < end && is_ident_byte(bytes[pos]) {
        pos += 1;
    }
    pos
}

fn is_ident_start(byte: u8) -> bool {
    byte.is_ascii_alphabetic() || byte == b'_' || byte == b'-'
}

fn is_ident_byte(byte: u8) -> bool {
    is_ident_start(byte) || byte.is_ascii_digit()
}
