// @generated by skinny bbnf-codegen; do not edit by hand.
use super::config;
use std::fmt;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CssFactError {
    pub offset: usize,
    pub message: &'static str,
}

impl fmt::Display for CssFactError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} at byte {}", self.message, self.offset)
    }
}

impl std::error::Error for CssFactError {}

pub struct FactSink {
    out: String,
    rules: u32,
    selector_lists: u32,
    selectors: u32,
    selector_items: u32,
    declarations: u32,
}

impl FactSink {
    pub fn new(input: &str, stylesheet_start: usize, stylesheet_end: usize, rules: u32) -> Self {
        let mut out = String::new();
        out.push_str(config::FACT_SCHEMA);
        out.push('\n');
        out.push_str("row\tid=");
        out.push_str(config::ROW_ID);
        out.push_str("\tplane=");
        out.push_str(config::OUTPUT_PLANE);
        out.push('\n');
        out.push_str("source\tinput_fnv64=");
        push_hex64(&mut out, fnv64(input.as_bytes()));
        out.push_str("\tinput_bytes=");
        out.push_str(&input.len().to_string());
        out.push('\n');
        out.push_str("stylesheet\tidx=0\tstart=");
        out.push_str(&stylesheet_start.to_string());
        out.push_str("\tend=");
        out.push_str(&stylesheet_end.to_string());
        out.push_str("\trules=");
        out.push_str(&rules.to_string());
        out.push('\n');
        Self {
            out,
            rules,
            selector_lists: 0,
            selectors: 0,
            selector_items: 0,
            declarations: 0,
        }
    }

    pub fn rule(
        &mut self,
        idx: u32,
        start: usize,
        end: usize,
        block_start: usize,
        block_end: usize,
        decls: u32,
    ) {
        self.out.push_str("rule\tidx=");
        self.out.push_str(&idx.to_string());
        self.out
            .push_str("\tkind=qualified\tdepth=0\tselector_list=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tstart=");
        self.out.push_str(&start.to_string());
        self.out.push_str("\tend=");
        self.out.push_str(&end.to_string());
        self.out.push_str("\tblock_start=");
        self.out.push_str(&block_start.to_string());
        self.out.push_str("\tblock_end=");
        self.out.push_str(&block_end.to_string());
        self.out.push_str("\tdecls=");
        self.out.push_str(&decls.to_string());
        self.out.push('\n');
    }

    pub fn selector_list(
        &mut self,
        rule: u32,
        start: usize,
        end: usize,
        selectors: u32,
        separators: u32,
    ) {
        self.selector_lists += 1;
        self.out.push_str("selector_list\trule=");
        self.out.push_str(&rule.to_string());
        self.out.push_str("\tidx=");
        self.out.push_str(&rule.to_string());
        self.out.push_str("\tstart=");
        self.out.push_str(&start.to_string());
        self.out.push_str("\tend=");
        self.out.push_str(&end.to_string());
        self.out.push_str("\tselectors=");
        self.out.push_str(&selectors.to_string());
        self.out.push_str("\tseparators=");
        self.out.push_str(&separators.to_string());
        self.out.push('\n');
    }

    pub fn selector(&mut self, list: u32, idx: u32, start: usize, end: usize, items: u32) {
        self.selectors += 1;
        self.out.push_str("selector\tlist=");
        self.out.push_str(&list.to_string());
        self.out.push_str("\tidx=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tstart=");
        self.out.push_str(&start.to_string());
        self.out.push_str("\tend=");
        self.out.push_str(&end.to_string());
        self.out.push_str("\titems=");
        self.out.push_str(&items.to_string());
        self.out.push('\n');
    }

    pub fn selector_name(
        &mut self,
        selector: u32,
        idx: u32,
        kind: &str,
        name: &str,
        start: usize,
        end: usize,
    ) {
        self.selector_items += 1;
        self.out.push_str("sel\tselector=");
        self.out.push_str(&selector.to_string());
        self.out.push_str("\tidx=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tkind=");
        self.out.push_str(kind);
        self.out.push_str("\tname_hex=");
        push_ascii_lower_hex(&mut self.out, name);
        self.out.push_str("\tstart=");
        self.out.push_str(&start.to_string());
        self.out.push_str("\tend=");
        self.out.push_str(&end.to_string());
        self.out.push('\n');
    }

    pub fn selector_combinator(
        &mut self,
        selector: u32,
        idx: u32,
        value: &str,
        start: usize,
        end: usize,
    ) {
        self.selector_items += 1;
        self.out.push_str("sel\tselector=");
        self.out.push_str(&selector.to_string());
        self.out.push_str("\tidx=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tkind=combinator\tvalue=");
        self.out.push_str(value);
        self.out.push_str("\tstart=");
        self.out.push_str(&start.to_string());
        self.out.push_str("\tend=");
        self.out.push_str(&end.to_string());
        self.out.push('\n');
    }

    pub fn selector_attribute(
        &mut self,
        selector: u32,
        idx: u32,
        name: &str,
        op: &str,
        value: &str,
        quote: &str,
        case_: &str,
        start: usize,
        end: usize,
    ) {
        self.selector_items += 1;
        self.out.push_str("sel\tselector=");
        self.out.push_str(&selector.to_string());
        self.out.push_str("\tidx=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tkind=attribute\tname_hex=");
        push_ascii_lower_hex(&mut self.out, name);
        self.out.push_str("\top=");
        self.out.push_str(op);
        self.out.push_str("\tvalue_hex=");
        push_hex(&mut self.out, value.as_bytes());
        self.out.push_str("\tquote=");
        self.out.push_str(quote);
        self.out.push_str("\tcase=");
        self.out.push_str(case_);
        self.out.push_str("\tstart=");
        self.out.push_str(&start.to_string());
        self.out.push_str("\tend=");
        self.out.push_str(&end.to_string());
        self.out.push('\n');
    }

    pub fn separator(&mut self, list: u32, idx: u32, start: usize, end: usize) {
        self.out.push_str("sep\tlist=");
        self.out.push_str(&list.to_string());
        self.out.push_str("\tidx=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tkind=comma\tstart=");
        self.out.push_str(&start.to_string());
        self.out.push_str("\tend=");
        self.out.push_str(&end.to_string());
        self.out.push('\n');
    }

    pub fn declaration(
        &mut self,
        rule: u32,
        idx: u32,
        property: &str,
        important: bool,
        value_start: usize,
        value_end: usize,
    ) {
        self.declarations += 1;
        self.out.push_str("decl\trule=");
        self.out.push_str(&rule.to_string());
        self.out.push_str("\tidx=");
        self.out.push_str(&idx.to_string());
        self.out.push_str("\tproperty_hex=");
        push_ascii_lower_hex(&mut self.out, property);
        self.out.push_str("\timportant=");
        self.out.push(if important { '1' } else { '0' });
        self.out.push_str("\tvalue_start=");
        self.out.push_str(&value_start.to_string());
        self.out.push_str("\tvalue_end=");
        self.out.push_str(&value_end.to_string());
        self.out.push('\n');
    }

    pub fn finish(mut self) -> String {
        let stream_hash = fnv64(self.out.as_bytes());
        self.out.push_str("end\trules=");
        self.out.push_str(&self.rules.to_string());
        self.out.push_str("\tselector_lists=");
        self.out.push_str(&self.selector_lists.to_string());
        self.out.push_str("\tselectors=");
        self.out.push_str(&self.selectors.to_string());
        self.out.push_str("\tselector_items=");
        self.out.push_str(&self.selector_items.to_string());
        self.out.push_str("\tdeclarations=");
        self.out.push_str(&self.declarations.to_string());
        self.out.push_str("\tstream_fnv64=");
        push_hex64(&mut self.out, stream_hash);
        self.out.push('\n');
        self.out
    }
}

fn fnv64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

fn push_ascii_lower_hex(out: &mut String, text: &str) {
    let mut buf = Vec::with_capacity(text.len());
    for byte in text.bytes() {
        buf.push(byte.to_ascii_lowercase());
    }
    push_hex(out, &buf);
}

fn push_hex64(out: &mut String, value: u64) {
    out.push_str(&format!("{value:016x}"));
}

fn push_hex(out: &mut String, bytes: &[u8]) {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in bytes {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 0x0f) as usize] as char);
    }
}
