// @generated by xtask regen-css; do not edit by hand.
use bbnf_ir::registry::StructLayout;
use crate::runtime::builder::StructBuilder;
use crate::runtime::css_l4::arena::CssArena;
use crate::runtime::css_l4::document::CssDocument;
use crate::runtime::css_l4::value::{
    CssAngle, CssAngleUnit, CssColor, CssColorFunction, CssColorMix, CssColorPredefined,
    CssColorSpace, CssColorType, CssDimension, CssFlex, CssFrequency, CssFrequencyUnit,
    CssFunction, CssHueMethod, CssLength, CssLengthUnit, CssPercentage, CssResolution,
    CssResolutionUnit, CssRule, CssTime, CssTimeUnit, CssTypedValue, Declaration,
    GenericAtRule, KeyframeBlock, KeyframesRule, MediaRule, Selector, StyleRule,
    StyleSheet,
};
use crate::runtime::handle::CompoundHandle;
#[derive(Debug, Clone, Copy)]
enum OpenFrame<'p> {
    StyleSheet { rules_base: usize },
    StyleRule { selectors_base: usize, decls_base: usize, span: &'p str },
    MediaRule { query: &'p str, rules_base: usize },
    KeyframesRule { name: &'p str, blocks_base: usize },
    KeyframeBlock { selector: &'p str, decls_base: usize },
    GenericAtRule { name: &'p str, prelude: &'p str, body: &'p str },
    Declaration { property: Option<&'p str>, values_base: usize, important: bool },
    SelectorList { selectors_base: usize, span: &'p str },
    Wrap { value: Option<CssTypedValue<'p>> },
    Numeric { kind: NumericKind, magnitude: Option<f64>, unit: Option<u8> },
    ColorFunction {
        kind_tag: Option<u8>,
        space_tag: Option<u8>,
        components_base: usize,
    },
    ColorMix {
        mix_space: Option<u8>,
        hue_method: Option<u8>,
        left: Option<&'p CssColor<'p>>,
        left_pct: Option<f64>,
        right: Option<&'p CssColor<'p>>,
        right_pct: Option<f64>,
    },
    Function { kind: FunctionKind, name: &'p str, args_base: usize },
    HexColor { hex_span: Option<&'p str> },
    DirPseudo { kind_tag: Option<u8> },
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum NumericKind {
    Length,
    Angle,
    Time,
    Frequency,
    Resolution,
    Flex,
    Percentage,
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum FunctionKind {
    Calc,
    Min,
    Max,
    Clamp,
    Var,
    Env,
    Url,
    Generic,
}
#[derive(Debug)]
pub struct CssStructBuilder<'p> {
    arena: CssArena<'p>,
    stack: Vec<OpenFrame<'p>>,
    root: Option<StyleSheet>,
    next_handle: u64,
    pending_value: Option<CssTypedValue<'p>>,
    input: &'p [u8],
    span_starts: Vec<u32>,
    pending_rules: Vec<CssRule<'p>>,
    pending_decls: Vec<Declaration<'p>>,
    pending_selectors: Vec<Selector<'p>>,
    pending_values: Vec<CssTypedValue<'p>>,
    pending_blocks: Vec<KeyframeBlock<'p>>,
    pending_components: Vec<f64>,
}
#[derive(Debug, Clone)]
pub struct CssStructCheckpoint<'p> {
    rules: usize,
    decls: usize,
    selectors: usize,
    values: usize,
    keyframes: usize,
    colors: usize,
    stack: Vec<OpenFrame<'p>>,
    root: Option<StyleSheet>,
    next_handle: u64,
    pending_value: Option<CssTypedValue<'p>>,
    span_starts_len: usize,
    pending_rules_len: usize,
    pending_decls_len: usize,
    pending_selectors_len: usize,
    pending_values_len: usize,
    pending_blocks_len: usize,
    pending_components_len: usize,
}
impl<'p> Default for CssStructBuilder<'p> {
    fn default() -> Self {
        Self::new()
    }
}
impl<'p> CssStructBuilder<'p> {
    pub fn new() -> Self {
        Self {
            arena: CssArena::new(),
            stack: Vec::with_capacity(16),
            root: None,
            next_handle: 0,
            pending_value: None,
            input: &[],
            span_starts: Vec::with_capacity(16),
            pending_rules: Vec::with_capacity(64),
            pending_decls: Vec::with_capacity(64),
            pending_selectors: Vec::with_capacity(32),
            pending_values: Vec::with_capacity(32),
            pending_blocks: Vec::with_capacity(16),
            pending_components: Vec::with_capacity(8),
        }
    }
    pub fn with_capacity(
        rules: usize,
        decls: usize,
        selectors: usize,
        values: usize,
        keyframes: usize,
    ) -> Self {
        Self {
            arena: CssArena::with_capacity(rules, decls, selectors, values, keyframes),
            stack: Vec::with_capacity(16),
            root: None,
            next_handle: 0,
            pending_value: None,
            input: &[],
            span_starts: Vec::with_capacity(16),
            pending_rules: Vec::with_capacity(64),
            pending_decls: Vec::with_capacity(64),
            pending_selectors: Vec::with_capacity(32),
            pending_values: Vec::with_capacity(32),
            pending_blocks: Vec::with_capacity(16),
            pending_components: Vec::with_capacity(8),
        }
    }
    pub fn finalise(mut self, input: &'p str) -> CssDocument<'p> {
        debug_assert!(
            self.stack.is_empty(),
            "CssStructBuilder::finalise called with {} open frame(s)", self.stack.len()
        );
        let root = self
            .root
            .take()
            .unwrap_or(StyleSheet {
                rules: crate::runtime::css_l4::arena::CssRuleListId::EMPTY,
            });
        CssDocument::new(self.arena, root, input)
    }
    fn deposit_value(&mut self, value: CssTypedValue<'p>) {
        if matches!(
            self.stack.last(), Some(OpenFrame::Declaration { .. } | OpenFrame::Function {
            .. })
        ) {
            self.pending_values.push(value);
            return;
        }
        match self.stack.last_mut() {
            Some(OpenFrame::Wrap { value: slot }) => *slot = Some(value),
            _ => self.pending_value = Some(value),
        }
    }
    fn deposit_declaration(&mut self, decl: Declaration<'p>) {
        if self
            .stack
            .iter()
            .rev()
            .any(|f| {
                matches!(
                    f, OpenFrame::StyleRule { .. } | OpenFrame::KeyframeBlock { .. }
                )
            })
        {
            self.pending_decls.push(decl);
        }
    }
    fn deposit_rule(&mut self, rule: CssRule<'p>) {
        if self
            .stack
            .iter()
            .rev()
            .any(|f| {
                matches!(f, OpenFrame::StyleSheet { .. } | OpenFrame::MediaRule { .. })
            })
        {
            self.pending_rules.push(rule);
        }
    }
}
impl<'p> StructBuilder for CssStructBuilder<'p> {
    type Checkpoint = CssStructCheckpoint<'p>;
    fn checkpoint(&self) -> Self::Checkpoint {
        CssStructCheckpoint {
            rules: self.arena.rule_slab_count(),
            decls: self.arena.decl_slab_count(),
            selectors: self.arena.selector_slab_count(),
            values: self.arena.value_slab_count(),
            keyframes: self.arena.keyframe_slab_count(),
            colors: self.arena.color_count(),
            stack: self.stack.clone(),
            root: self.root,
            next_handle: self.next_handle,
            pending_value: self.pending_value,
            span_starts_len: self.span_starts.len(),
            pending_rules_len: self.pending_rules.len(),
            pending_decls_len: self.pending_decls.len(),
            pending_selectors_len: self.pending_selectors.len(),
            pending_values_len: self.pending_values.len(),
            pending_blocks_len: self.pending_blocks.len(),
            pending_components_len: self.pending_components.len(),
        }
    }
    fn rollback(&mut self, checkpoint: Self::Checkpoint) {
        self.arena
            .truncate(
                checkpoint.rules,
                checkpoint.decls,
                checkpoint.selectors,
                checkpoint.values,
                checkpoint.keyframes,
                checkpoint.colors,
            );
        self.stack = checkpoint.stack;
        self.root = checkpoint.root;
        self.next_handle = checkpoint.next_handle;
        self.pending_value = checkpoint.pending_value;
        self.span_starts.truncate(checkpoint.span_starts_len);
        self.pending_rules.truncate(checkpoint.pending_rules_len);
        self.pending_decls.truncate(checkpoint.pending_decls_len);
        self.pending_selectors.truncate(checkpoint.pending_selectors_len);
        self.pending_values.truncate(checkpoint.pending_values_len);
        self.pending_blocks.truncate(checkpoint.pending_blocks_len);
        self.pending_components.truncate(checkpoint.pending_components_len);
    }
    fn bind_input(&mut self, input: &[u8]) {
        self.input = unsafe { core::mem::transmute::<&[u8], &'p [u8]>(input) };
    }
    fn record_compound_bounds_start(&mut self, offset: u32) {
        self.span_starts.push(offset);
    }
    fn record_compound_bounds_end(&mut self, offset: u32) {
        let Some(start) = self.span_starts.pop() else { return };
        let s = start as usize;
        let e = offset as usize;
        let captured: Option<&'p str> = if s <= e && e <= self.input.len() {
            core::str::from_utf8(&self.input[s..e]).ok()
        } else {
            None
        };
        match (captured, self.stack.last_mut()) {
            (Some(text), Some(OpenFrame::SelectorList { span, .. })) => {
                if span.is_empty() {
                    *span = text;
                }
            }
            (Some(text), Some(OpenFrame::GenericAtRule { name, .. })) => {
                if name.is_empty() || *name == ";" {
                    *name = text;
                }
            }
            _ => {}
        }
    }
    fn begin_compound(&mut self, layout: &StructLayout) -> CompoundHandle {
        let frame = match layout.rule_id {
            3 => {
                OpenFrame::HexColor {
                    hex_span: None,
                }
            }
            53 => {
                OpenFrame::Numeric {
                    kind: NumericKind::Percentage,
                    magnitude: None,
                    unit: None,
                }
            }
            55 => {
                OpenFrame::Function {
                    kind: FunctionKind::Url,
                    name: "",
                    args_base: self.pending_values.len(),
                }
            }
            57 => {
                OpenFrame::Numeric {
                    kind: NumericKind::Angle,
                    magnitude: None,
                    unit: None,
                }
            }
            58 => {
                OpenFrame::Numeric {
                    kind: NumericKind::Time,
                    magnitude: None,
                    unit: None,
                }
            }
            59 => {
                OpenFrame::Numeric {
                    kind: NumericKind::Frequency,
                    magnitude: None,
                    unit: None,
                }
            }
            60 => {
                OpenFrame::Numeric {
                    kind: NumericKind::Resolution,
                    magnitude: None,
                    unit: None,
                }
            }
            61 => {
                OpenFrame::Numeric {
                    kind: NumericKind::Flex,
                    magnitude: None,
                    unit: None,
                }
            }
            72 => {
                OpenFrame::DirPseudo {
                    kind_tag: None,
                }
            }
            74 => {
                OpenFrame::Function {
                    kind: FunctionKind::Generic,
                    name: "",
                    args_base: self.pending_values.len(),
                }
            }
            82 => {
                OpenFrame::Function {
                    kind: FunctionKind::Var,
                    name: "",
                    args_base: self.pending_values.len(),
                }
            }
            83 => {
                OpenFrame::Function {
                    kind: FunctionKind::Env,
                    name: "",
                    args_base: self.pending_values.len(),
                }
            }
            84 => {
                OpenFrame::Numeric {
                    kind: NumericKind::Length,
                    magnitude: None,
                    unit: None,
                }
            }
            87 => {
                OpenFrame::ColorFunction {
                    kind_tag: None,
                    space_tag: None,
                    components_base: self.pending_components.len(),
                }
            }
            105 => {
                OpenFrame::Function {
                    kind: FunctionKind::Calc,
                    name: "",
                    args_base: self.pending_values.len(),
                }
            }
            106 => {
                OpenFrame::Function {
                    kind: FunctionKind::Min,
                    name: "",
                    args_base: self.pending_values.len(),
                }
            }
            107 => {
                OpenFrame::Function {
                    kind: FunctionKind::Max,
                    name: "",
                    args_base: self.pending_values.len(),
                }
            }
            108 => {
                OpenFrame::Function {
                    kind: FunctionKind::Clamp,
                    name: "",
                    args_base: self.pending_values.len(),
                }
            }
            139 => {
                OpenFrame::KeyframeBlock {
                    selector: "",
                    decls_base: self.pending_decls.len(),
                }
            }
            140 => {
                OpenFrame::KeyframesRule {
                    name: "",
                    blocks_base: self.pending_blocks.len(),
                }
            }
            142 => {
                OpenFrame::GenericAtRule {
                    name: "",
                    prelude: "",
                    body: "",
                }
            }
            144 => {
                OpenFrame::StyleRule {
                    selectors_base: self.pending_selectors.len(),
                    decls_base: self.pending_decls.len(),
                    span: "",
                }
            }
            145 => {
                OpenFrame::MediaRule {
                    query: "",
                    rules_base: self.pending_rules.len(),
                }
            }
            149 => {
                OpenFrame::StyleSheet {
                    rules_base: self.pending_rules.len(),
                }
            }
            143 => OpenFrame::Wrap { value: None },
            63 | 64 | 112 | 113 | 114 | 115 | 116 | 117 | 118 | 119 | 120 | 121 | 122
            | 123 | 124 | 125 | 126 | 127 | 128 | 129 | 130 | 131 | 132 | 133 | 134 | 135
            | 136 | 137 => {
                OpenFrame::Declaration {
                    property: None,
                    values_base: self.pending_values.len(),
                    important: false,
                }
            }
            96 => {
                OpenFrame::SelectorList {
                    selectors_base: self.pending_selectors.len(),
                    span: "",
                }
            }
            _ => {
                let _ = layout.kind;
                OpenFrame::Wrap { value: None }
            }
        };
        self.stack.push(frame);
        self.next_handle = self.next_handle.wrapping_add(1);
        CompoundHandle::new(self.next_handle, 0)
    }
    fn end_compound(&mut self, _handle: CompoundHandle) {
        let frame = self
            .stack
            .pop()
            .expect("CssStructBuilder::end_compound on empty stack");
        match frame {
            OpenFrame::StyleSheet { rules_base } => {
                let rules: Vec<CssRule<'p>> = self.pending_rules.split_off(rules_base);
                let id = self.arena.push_rules(rules);
                let sheet = StyleSheet { rules: id };
                if self.stack.is_empty() {
                    self.root = Some(sheet);
                }
            }
            OpenFrame::StyleRule { selectors_base, decls_base, span } => {
                let declarations: Vec<Declaration<'p>> = self
                    .pending_decls
                    .split_off(decls_base);
                let selectors: Vec<Selector<'p>> = self
                    .pending_selectors
                    .split_off(selectors_base);
                let sel_id = self.arena.push_selectors(selectors);
                let decl_id = self.arena.push_decls(declarations);
                self.deposit_rule(
                    CssRule::Style(StyleRule {
                        selectors: sel_id,
                        declarations: decl_id,
                        span,
                    }),
                );
            }
            OpenFrame::MediaRule { query, rules_base } => {
                let rules: Vec<CssRule<'p>> = self.pending_rules.split_off(rules_base);
                let id = self.arena.push_rules(rules);
                self.deposit_rule(CssRule::Media(MediaRule { query, rules: id }));
            }
            OpenFrame::KeyframesRule { name, blocks_base } => {
                let blocks: Vec<KeyframeBlock<'p>> = self
                    .pending_blocks
                    .split_off(blocks_base);
                let id = self.arena.push_keyframes(blocks);
                self.deposit_rule(
                    CssRule::Keyframes(KeyframesRule { name, blocks: id }),
                );
            }
            OpenFrame::KeyframeBlock { selector, decls_base } => {
                let declarations: Vec<Declaration<'p>> = self
                    .pending_decls
                    .split_off(decls_base);
                let id = self.arena.push_decls(declarations);
                let block = KeyframeBlock {
                    selector,
                    declarations: id,
                };
                if matches!(self.stack.last(), Some(OpenFrame::KeyframesRule { .. })) {
                    self.pending_blocks.push(block);
                }
            }
            OpenFrame::GenericAtRule { name, prelude, body } => {
                self.deposit_rule(
                    CssRule::GenericAt(GenericAtRule {
                        name,
                        prelude,
                        body,
                    }),
                );
            }
            OpenFrame::Declaration { property, values_base, important } => {
                let values: Vec<CssTypedValue<'p>> = self
                    .pending_values
                    .split_off(values_base);
                let property = property.unwrap_or("");
                let value = match values.len() {
                    0 => CssTypedValue::Span(""),
                    1 => values.into_iter().next().unwrap_or(CssTypedValue::Span("")),
                    _ => CssTypedValue::List(self.arena.push_values(values)),
                };
                self.deposit_declaration(Declaration {
                    property,
                    value,
                    important,
                });
            }
            OpenFrame::SelectorList { selectors_base, span } => {
                let selectors: Vec<Selector<'p>> = self
                    .pending_selectors
                    .split_off(selectors_base);
                let unit = if span.is_empty() {
                    selectors.into_iter().next().unwrap_or(Selector::Universal)
                } else {
                    Selector::Span(span)
                };
                match self.stack.last() {
                    Some(OpenFrame::StyleRule { .. }) => {
                        self.pending_selectors.push(unit)
                    }
                    Some(OpenFrame::KeyframeBlock { .. }) => {}
                    Some(OpenFrame::SelectorList { .. }) => {}
                    _ => {}
                }
            }
            OpenFrame::Wrap { value } => {
                if let Some(value) = value {
                    self.deposit_value(value);
                }
            }
            OpenFrame::Numeric { kind, magnitude, unit } => {
                let value = magnitude.unwrap_or(0.0);
                let dim = match (kind, unit) {
                    (NumericKind::Length, Some(u)) => {
                        CssDimension::Length(CssLength {
                            value,
                            unit: CssLengthUnit::from_discriminant(u),
                        })
                    }
                    (NumericKind::Angle, Some(u)) => {
                        CssDimension::Angle(CssAngle {
                            value,
                            unit: CssAngleUnit::from_discriminant(u)
                                .unwrap_or(CssAngleUnit::Deg),
                        })
                    }
                    (NumericKind::Time, Some(u)) => {
                        CssDimension::Time(CssTime {
                            value,
                            unit: CssTimeUnit::from_discriminant(u)
                                .unwrap_or(CssTimeUnit::S),
                        })
                    }
                    (NumericKind::Frequency, Some(u)) => {
                        CssDimension::Frequency(CssFrequency {
                            value,
                            unit: CssFrequencyUnit::from_discriminant(u)
                                .unwrap_or(CssFrequencyUnit::Hz),
                        })
                    }
                    (NumericKind::Resolution, Some(u)) => {
                        CssDimension::Resolution(CssResolution {
                            value,
                            unit: CssResolutionUnit::from_discriminant(u)
                                .unwrap_or(CssResolutionUnit::Dppx),
                        })
                    }
                    (NumericKind::Flex, _) => CssDimension::Flex(CssFlex { value }),
                    (NumericKind::Percentage, _) => {
                        CssDimension::Percentage(CssPercentage { value })
                    }
                    _ => CssDimension::Unitless(value),
                };
                self.deposit_value(CssTypedValue::Dimension(dim));
            }
            OpenFrame::ColorFunction { kind_tag, space_tag, components_base } => {
                let components: Vec<f64> = self
                    .pending_components
                    .split_off(components_base);
                let c1 = components.first().copied().unwrap_or(0.0);
                let c2 = components.get(1).copied().unwrap_or(0.0);
                let c3 = components.get(2).copied().unwrap_or(0.0);
                let alpha = components.get(3).copied();
                let color = if let Some(kind) = kind_tag {
                    CssColor::Function(CssColorFunction {
                        kind: CssColorType::from_discriminant(kind)
                            .unwrap_or(CssColorType::Rgb),
                        c1,
                        c2,
                        c3,
                        alpha,
                    })
                } else if let Some(space) = space_tag {
                    CssColor::Predefined(CssColorPredefined {
                        space: CssColorSpace::from_discriminant(space)
                            .unwrap_or(CssColorSpace::Srgb),
                        c1,
                        c2,
                        c3,
                        alpha,
                    })
                } else {
                    CssColor::Function(CssColorFunction {
                        kind: CssColorType::Rgb,
                        c1,
                        c2,
                        c3,
                        alpha,
                    })
                };
                self.deposit_value(CssTypedValue::Color(color));
            }
            OpenFrame::ColorMix {
                mix_space,
                hue_method,
                left,
                left_pct,
                right,
                right_pct,
            } => {
                let mix_space = mix_space
                    .and_then(CssColorSpace::from_discriminant)
                    .unwrap_or(CssColorSpace::Srgb);
                let hue_method = hue_method.and_then(CssHueMethod::from_discriminant);
                let fallback = self.arena.push_color(CssColor::Hex(0x00000000));
                let left = left.unwrap_or(fallback);
                let right = right.unwrap_or(fallback);
                self.deposit_value(
                    CssTypedValue::Color(
                        CssColor::Mix(CssColorMix {
                            mix_space,
                            hue_method,
                            left,
                            left_pct,
                            right,
                            right_pct,
                        }),
                    ),
                );
            }
            OpenFrame::Function { kind, name, args_base } => {
                let args: Vec<CssTypedValue<'p>> = self
                    .pending_values
                    .split_off(args_base);
                let id = self.arena.push_values(args);
                let func = match kind {
                    FunctionKind::Calc => CssFunction::Calc { args: id },
                    FunctionKind::Min => CssFunction::Min { args: id },
                    FunctionKind::Max => CssFunction::Max { args: id },
                    FunctionKind::Clamp => CssFunction::Clamp { args: id },
                    FunctionKind::Var => {
                        CssFunction::Var {
                            name: "",
                            fallback: id,
                        }
                    }
                    FunctionKind::Env => {
                        CssFunction::Env {
                            name: "",
                            fallback: id,
                        }
                    }
                    FunctionKind::Url => CssFunction::Url { raw: "" },
                    FunctionKind::Generic => {
                        CssFunction::Generic {
                            name,
                            args: id,
                        }
                    }
                };
                self.deposit_value(CssTypedValue::Function(func));
            }
            OpenFrame::DirPseudo { kind_tag } => {
                let text: &'p str = match kind_tag {
                    Some(1) => ":dir(rtl)",
                    Some(0) => ":dir(ltr)",
                    _ => ":dir()",
                };
                if matches!(
                    self.stack.last(), Some(OpenFrame::SelectorList { .. } |
                    OpenFrame::StyleRule { .. })
                ) {
                    self.pending_selectors.push(Selector::PseudoClass(text));
                } else {
                    self.deposit_value(CssTypedValue::Span(text));
                }
            }
            OpenFrame::HexColor { hex_span } => {
                let packed = hex_span
                    .map(|s| {
                        let digits = s.strip_prefix('#').unwrap_or(s);
                        crate::css_types::parse_hex_color(digits)
                    })
                    .unwrap_or(0);
                self.deposit_value(CssTypedValue::Color(CssColor::Hex(packed)));
            }
        }
    }
    fn push_leaf_with_f64(&mut self, value: f64) {
        if matches!(self.stack.last(), Some(OpenFrame::ColorFunction { .. })) {
            self.pending_components.push(value);
            return;
        }
        match self.stack.last_mut() {
            Some(OpenFrame::Numeric { magnitude, .. }) => *magnitude = Some(value),
            Some(OpenFrame::ColorMix { left_pct, right_pct, left, right, .. }) => {
                if left.is_some() && left_pct.is_none() {
                    *left_pct = Some(value);
                } else if right.is_some() && right_pct.is_none() {
                    *right_pct = Some(value);
                }
            }
            _ => self.deposit_value(CssTypedValue::Number(value)),
        }
    }
    fn push_leaf_with_i64(&mut self, value: i64) {
        self.deposit_value(CssTypedValue::Integer(value));
    }
    fn push_leaf_with_u64(&mut self, value: u64) {
        if value <= u32::MAX as u64 {
            self.deposit_value(CssTypedValue::Color(CssColor::Hex(value as u32)));
        } else {
            self.deposit_value(CssTypedValue::Number(value as f64));
        }
    }
    fn push_leaf_with_bool(&mut self, _value: bool) {}
    fn push_leaf_with_str(&mut self, value: &str) {
        let lifetime_extended: &'p str = unsafe { core::mem::transmute(value) };
        if matches!(self.stack.last(), Some(OpenFrame::SelectorList { .. })) {
            self.pending_selectors.push(Selector::Span(lifetime_extended));
            return;
        }
        match self.stack.last_mut() {
            Some(OpenFrame::Declaration { property, .. }) if property.is_none() => {
                *property = Some(lifetime_extended);
            }
            Some(OpenFrame::Function { name, .. }) if name.is_empty() => {
                *name = lifetime_extended;
            }
            Some(OpenFrame::KeyframesRule { name, .. }) if name.is_empty() => {
                *name = lifetime_extended;
            }
            Some(OpenFrame::KeyframeBlock { selector, .. }) if selector.is_empty() => {
                *selector = lifetime_extended;
            }
            Some(OpenFrame::MediaRule { query, .. }) if query.is_empty() => {
                *query = lifetime_extended;
            }
            Some(OpenFrame::GenericAtRule { name, .. }) if name.is_empty() => {
                *name = lifetime_extended;
            }
            Some(OpenFrame::HexColor { hex_span }) if hex_span.is_none() => {
                *hex_span = Some(lifetime_extended);
            }
            _ => self.deposit_value(CssTypedValue::Span(lifetime_extended)),
        }
    }
    fn push_leaf_with_unit(&mut self) {}
    fn push_branch_tag(&mut self, branch_index: u32) {
        match self.stack.last_mut() {
            Some(OpenFrame::Numeric { unit, .. }) => *unit = Some(branch_index as u8),
            Some(OpenFrame::ColorFunction { kind_tag, space_tag, .. }) => {
                if kind_tag.is_none() && space_tag.is_none() {
                    *kind_tag = Some(branch_index as u8);
                }
            }
            Some(OpenFrame::ColorMix { mix_space, hue_method, .. }) => {
                if mix_space.is_none() {
                    *mix_space = Some(branch_index as u8);
                } else if hue_method.is_none() {
                    *hue_method = Some(branch_index as u8);
                }
            }
            Some(OpenFrame::DirPseudo { kind_tag }) => {
                if kind_tag.is_none() {
                    *kind_tag = Some(branch_index as u8);
                }
            }
            _ => {}
        }
    }
}
