// @generated by xtask regen-css; do not edit by hand.
use crate::runtime::css_l4::arena::{
    CssDeclListId, CssRuleListId, CssSelectorListId, CssValueListId,
};
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssLengthUnit {
    Px = 0,
    Em = 1,
    Rem = 2,
    Vh = 3,
    Vw = 4,
    Vmin = 5,
    Vmax = 6,
    Ch = 7,
    Ex = 8,
    Cm = 9,
    Mm = 10,
    In = 11,
    Pt = 12,
    Pc = 13,
    Lh = 14,
    Rlh = 15,
    Svw = 16,
    Svh = 17,
    Dvw = 18,
    Dvh = 19,
    Lvw = 20,
    Lvh = 21,
    Cqw = 22,
    Cqh = 23,
    Cqi = 24,
    Cqb = 25,
    Q = 26,
    Other(u8) = 255,
}
impl CssLengthUnit {
    pub fn from_discriminant(d: u8) -> Self {
        match d {
            0 => Self::Px,
            1 => Self::Em,
            2 => Self::Rem,
            3 => Self::Vh,
            4 => Self::Vw,
            5 => Self::Vmin,
            6 => Self::Vmax,
            7 => Self::Ch,
            8 => Self::Ex,
            9 => Self::Cm,
            10 => Self::Mm,
            11 => Self::In,
            12 => Self::Pt,
            13 => Self::Pc,
            14 => Self::Lh,
            15 => Self::Rlh,
            16 => Self::Svw,
            17 => Self::Svh,
            18 => Self::Dvw,
            19 => Self::Dvh,
            20 => Self::Lvw,
            21 => Self::Lvh,
            22 => Self::Cqw,
            23 => Self::Cqh,
            24 => Self::Cqi,
            25 => Self::Cqb,
            26 => Self::Q,
            other => Self::Other(other),
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssAngleUnit {
    Deg = 0,
    Rad = 1,
    Grad = 2,
    Turn = 3,
}
impl CssAngleUnit {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::Deg),
            1 => Some(Self::Rad),
            2 => Some(Self::Grad),
            3 => Some(Self::Turn),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssTimeUnit {
    Ms = 0,
    S = 1,
}
impl CssTimeUnit {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::Ms),
            1 => Some(Self::S),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssFrequencyUnit {
    Hz = 0,
    KHz = 1,
}
impl CssFrequencyUnit {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::Hz),
            1 => Some(Self::KHz),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssResolutionUnit {
    Dpi = 0,
    Dpcm = 1,
    Dppx = 2,
    X = 3,
}
impl CssResolutionUnit {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::Dpi),
            1 => Some(Self::Dpcm),
            2 => Some(Self::Dppx),
            3 => Some(Self::X),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssColorType {
    Rgb = 0,
    Rgba = 1,
    Hsl = 2,
    Hsla = 3,
    Hwb = 4,
    Lab = 5,
    Lch = 6,
    Oklab = 7,
    Oklch = 8,
}
impl CssColorType {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::Rgb),
            1 => Some(Self::Rgba),
            2 => Some(Self::Hsl),
            3 => Some(Self::Hsla),
            4 => Some(Self::Hwb),
            5 => Some(Self::Lab),
            6 => Some(Self::Lch),
            7 => Some(Self::Oklab),
            8 => Some(Self::Oklch),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssColorSpace {
    Srgb = 0,
    SrgbLinear = 1,
    DisplayP3 = 2,
    A98Rgb = 3,
    ProphotoRgb = 4,
    Rec2020 = 5,
    XyzD50 = 6,
    XyzD65 = 7,
    Xyz = 8,
    Lch = 9,
    Lab = 10,
    Oklab = 11,
    Oklch = 12,
    Hsl = 13,
    Hwb = 14,
}
impl CssColorSpace {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::Srgb),
            1 => Some(Self::SrgbLinear),
            2 => Some(Self::DisplayP3),
            3 => Some(Self::A98Rgb),
            4 => Some(Self::ProphotoRgb),
            5 => Some(Self::Rec2020),
            6 => Some(Self::XyzD50),
            7 => Some(Self::XyzD65),
            8 => Some(Self::Xyz),
            9 => Some(Self::Lch),
            10 => Some(Self::Lab),
            11 => Some(Self::Oklab),
            12 => Some(Self::Oklch),
            13 => Some(Self::Hsl),
            14 => Some(Self::Hwb),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssHueMethod {
    Shorter = 0,
    Longer = 1,
    Increasing = 2,
    Decreasing = 3,
}
impl CssHueMethod {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::Shorter),
            1 => Some(Self::Longer),
            2 => Some(Self::Increasing),
            3 => Some(Self::Decreasing),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssMathOperator {
    Add = 0,
    Sub = 1,
    Mul = 2,
    Div = 3,
}
impl CssMathOperator {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::Add),
            1 => Some(Self::Sub),
            2 => Some(Self::Mul),
            3 => Some(Self::Div),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum CssGlobalKeyword {
    RevertLayer = 0,
    Inherit = 1,
    Initial = 2,
    Unset = 3,
    Revert = 4,
}
impl CssGlobalKeyword {
    pub fn from_discriminant(d: u8) -> Option<Self> {
        match d {
            0 => Some(Self::RevertLayer),
            1 => Some(Self::Inherit),
            2 => Some(Self::Initial),
            3 => Some(Self::Unset),
            4 => Some(Self::Revert),
            _ => None,
        }
    }
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssLength {
    pub value: f64,
    pub unit: CssLengthUnit,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssAngle {
    pub value: f64,
    pub unit: CssAngleUnit,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssTime {
    pub value: f64,
    pub unit: CssTimeUnit,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssFrequency {
    pub value: f64,
    pub unit: CssFrequencyUnit,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssResolution {
    pub value: f64,
    pub unit: CssResolutionUnit,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssFlex {
    pub value: f64,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssPercentage {
    pub value: f64,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssColorFunction {
    pub kind: CssColorType,
    pub c1: f64,
    pub c2: f64,
    pub c3: f64,
    pub alpha: Option<f64>,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssColorPredefined {
    pub space: CssColorSpace,
    pub c1: f64,
    pub c2: f64,
    pub c3: f64,
    pub alpha: Option<f64>,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct CssColorMix<'p> {
    pub mix_space: CssColorSpace,
    pub hue_method: Option<CssHueMethod>,
    pub left: &'p CssColor<'p>,
    pub left_pct: Option<f64>,
    pub right: &'p CssColor<'p>,
    pub right_pct: Option<f64>,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Declaration<'p> {
    pub property: &'p str,
    pub value: CssTypedValue<'p>,
    pub important: bool,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct StyleRule<'p> {
    pub selectors: CssSelectorListId,
    pub declarations: CssDeclListId,
    pub span: &'p str,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct MediaRule<'p> {
    pub query: &'p str,
    pub rules: CssRuleListId,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct KeyframeBlock<'p> {
    pub selector: &'p str,
    pub declarations: CssDeclListId,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct KeyframesRule<'p> {
    pub name: &'p str,
    pub blocks: CssKeyframeListId,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct GenericAtRule<'p> {
    pub name: &'p str,
    pub prelude: &'p str,
    pub body: &'p str,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct StyleSheet {
    pub rules: CssRuleListId,
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CssDimension {
    Length(CssLength),
    Angle(CssAngle),
    Time(CssTime),
    Frequency(CssFrequency),
    Resolution(CssResolution),
    Flex(CssFlex),
    Percentage(CssPercentage),
    Unitless(f64),
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CssColor<'p> {
    Hex(u32),
    Named { name: &'p str, packed: u32 },
    Function(CssColorFunction),
    Predefined(CssColorPredefined),
    Mix(CssColorMix<'p>),
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CssFunction<'p> {
    Calc { args: CssValueListId },
    Min { args: CssValueListId },
    Max { args: CssValueListId },
    Clamp { args: CssValueListId },
    Var { name: &'p str, fallback: CssValueListId },
    Env { name: &'p str, fallback: CssValueListId },
    Url { raw: &'p str },
    Gradient { name: &'p str, args: CssValueListId },
    Generic { name: &'p str, args: CssValueListId },
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Selector<'p> {
    Universal,
    Type(&'p str),
    Class(&'p str),
    Id(&'p str),
    Attribute(&'p str),
    PseudoClass(&'p str),
    PseudoElement(&'p str),
    Combinator(&'p str),
    Span(&'p str),
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CssRule<'p> {
    Style(StyleRule<'p>),
    Media(MediaRule<'p>),
    Keyframes(KeyframesRule<'p>),
    GenericAt(GenericAtRule<'p>),
}
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum CssTypedValue<'p> {
    Dimension(CssDimension),
    Number(f64),
    Integer(i64),
    String(&'p str),
    Ident(&'p str),
    GlobalKeyword(CssGlobalKeyword),
    Color(CssColor<'p>),
    Function(CssFunction<'p>),
    List(CssValueListId),
    Span(&'p str),
}
pub use crate::runtime::css_l4::arena::CssKeyframeListId;
