#[cfg(target_arch = "aarch64")]
pub mod byte_class_from_eq_set_64;
#[cfg(target_arch = "aarch64")]
pub mod byte_context;
#[cfg(target_arch = "aarch64")]
pub mod cache_hints;
#[cfg(target_arch = "aarch64")]
pub mod classify_tbl4;
#[cfg(target_arch = "aarch64")]
pub mod digit_mac;
#[cfg(target_arch = "aarch64")]
pub mod match_tiny_plain_string;
#[cfg(target_arch = "aarch64")]
pub mod movemask;
#[cfg(target_arch = "aarch64")]
pub mod quad_load;
#[cfg(target_arch = "aarch64")]
pub mod string_block;
#[cfg(target_arch = "aarch64")]
pub mod unescape_uxxxx;
#[cfg(target_arch = "aarch64")]
pub mod utf8;
